#!/usr/bin/env python3
"""
Dynamic Sitemap Generator for Leenardo Graded Multilingual Reader.
Generates a sitemaps.org compliant XML sitemap covering all article URLs
across all CEFR levels and target/support language permutations.
"""

import json
import os
import sys
from datetime import datetime, timezone
import xml.etree.ElementTree as ET
from xml.dom import minidom

BASE_URL = "https://leenardo.com"
SUPPORTED_LANGUAGES = ["tr", "en", "es", "de", "fr"]
SUPPORTED_LEVELS = ["A1", "A2", "B1", "B2", "C1"]

def generate_sitemap(json_path="articles.json", output_path="sitemap.xml"):
    if not os.path.exists(json_path):
        print(f"Error: {json_path} not found.")
        sys.exit(1)

    with open(json_path, "r", encoding="utf-8") as f:
        articles = json.load(f)

    # Current date formatted for sitemap (YYYY-MM-DD)
    now_date = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    # XML root element
    urlset = ET.Element("urlset", xmlns="http://www.sitemaps.org/schemas/sitemap/0.9")

    # 1. Main Homepage
    home_url = ET.SubElement(urlset, "url")
    ET.SubElement(home_url, "loc").text = f"{BASE_URL}/"
    ET.SubElement(home_url, "lastmod").text = now_date
    ET.SubElement(home_url, "changefreq").text = "daily"
    ET.SubElement(home_url, "priority").text = "1.0"

    # Homepage language combinations
    for target in SUPPORTED_LANGUAGES:
        for support in SUPPORTED_LANGUAGES:
            if target == support:
                continue
            hl_url = ET.SubElement(urlset, "url")
            ET.SubElement(hl_url, "loc").text = f"{BASE_URL}/index.html?target={target}&support={support}"
            ET.SubElement(hl_url, "lastmod").text = now_date
            ET.SubElement(hl_url, "changefreq").text = "daily"
            ET.SubElement(hl_url, "priority").text = "0.9"

    # 2. Articles across all target, support, and level permutations
    article_count = 0
    url_count = 0

    for art in articles:
        art_id = art.get("id")
        if not art_id or art.get("hidden"):
            continue
        article_count += 1

        for target in SUPPORTED_LANGUAGES:
            for support in SUPPORTED_LANGUAGES:
                if target == support:
                    continue
                for level in SUPPORTED_LEVELS:
                    art_url = ET.SubElement(urlset, "url")
                    loc = f"{BASE_URL}/article.html?id={art_id}&target={target}&support={support}&level={level}"
                    ET.SubElement(art_url, "loc").text = loc
                    ET.SubElement(art_url, "lastmod").text = now_date
                    ET.SubElement(art_url, "changefreq").text = "weekly"
                    ET.SubElement(art_url, "priority").text = "0.8"
                    url_count += 1

    # Pretty-print XML
    raw_xml = ET.tostring(urlset, encoding="utf-8")
    parsed_dom = minidom.parseString(raw_xml)
    pretty_xml = parsed_dom.toprettyxml(indent="  ", encoding="utf-8").decode("utf-8")

    # Remove extra blank lines generated by minidom
    cleaned_lines = [line for line in pretty_xml.splitlines() if line.strip()]
    final_xml = "\n".join(cleaned_lines) + "\n"

    with open(output_path, "w", encoding="utf-8") as out:
        out.write(final_xml)

    print(f"✓ Successfully generated {output_path}")
    print(f"  • Total Articles: {article_count}")
    print(f"  • Total URLs generated: {len(urlset)}")
    print(f"  • File size: {os.path.getsize(output_path):,} bytes")

if __name__ == "__main__":
    generate_sitemap()
