#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generates the comprehensive verified Turkish fallthrough dictionary
for all 465 unglossed/echoed verb and predicate tokens in articles.json.
Each entry has: (lemma, pos, en_trans, note)
"""

import json
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
SCRATCH_FILE = BASE_DIR / "scratch_tr_verbs_to_patch.json"
OUTPUT_FILE = BASE_DIR / "scripts" / "turkish_fallthrough_dict.py"

# Curated, contextually accurate mapping for all 465 Turkish fallthrough items
# Derived from sentence context and Turkish morphological deconstruction
CURATED_TR_MAP = {
    # A
    "abartı": ("abartı", "İsim", "exaggeration", '"abartı" (abartı — exaggeration)'),
    "adıdır": ("ad", "İsim + Ek-fiil Yüklem", "is the name of", '"adıdır" (kök: ad — is the name of)'),
    "aileler": ("aile", "İsim (Çoğul)", "families", '"aileler" (kök: aile — families)'),
    "aktarılmasıdır": ("aktarılma", "İsim-fiil + Ek-fiil Yüklem", "is the transmission / passing down of", '"aktarılmasıdır" (kök: aktarılmak — is the passing down of)'),
    "aktiftir": ("aktif", "Sıfat + Ek-fiil Yüklem", "is active", '"aktiftir" (kök: aktif — is active)'),
    "akıntılar": ("akıntı", "İsim (Çoğul)", "currents", '"akıntılar" (kök: akıntı — currents)'),
    "akışkanlar": ("akışkan", "İsim (Çoğul)", "fluids", '"akışkanlar" (kök: akışkan — fluids)'),
    "alanlarındandır": ("alan", "İsim + Çoğul + Ayrılma + Ek-fiil", "is among the fields of", '"alanlarındandır" (kök: alan — is among the fields of)'),
    "alarm": ("alarm", "İsim", "alarm / warning signal", '"alarm" (alarm — warning signal)'),
    "alzheimer": ("Alzheimer", "Özel İsim", "Alzheimer's disease", '"alzheimer" (Alzheimer — Alzheimer\'s)'),
    "alıcılar": ("alıcı", "İsim (Çoğul)", "receptors / buyers", '"alıcılar" (kök: alıcı — receptors / buyers)'),
    "alışkanlıklar": ("alışkanlık", "İsim (Çoğul)", "habits / routines", '"alışkanlıklar" (kök: alışkanlık — habits)'),
    "anahtardır": ("anahtar", "İsim + Ek-fiil Yüklem", "is the key", '"anahtardır" (kök: anahtar — is the key)'),
    "ansiklopedisidir": ("ansiklopedi", "İsim + Ek-fiil Yüklem", "is the encyclopedia of", '"ansiklopedisidir" (kök: ansiklopedi — is the encyclopedia of)'),
    "antrenmandır": ("antrenman", "İsim + Ek-fiil Yüklem", "is training / workout", '"antrenmandır" (kök: antrenman — is training)'),
    "antrenmanlar": ("antrenman", "İsim (Çoğul)", "workouts / training sessions", '"antrenmanlar" (kök: antrenman — workouts)'),
    "anıtıdır": ("anıt", "İsim + Ek-fiil Yüklem", "is the monument of", '"anıtıdır" (kök: anıt — is the monument of)'),
    "aralar": ("ara", "İsim (Çoğul) / Fiil (Geniş Zaman)", "breaks / intervals", '"aralar" (kök: ara — intervals / breaks)'),
    "araştırmacılar": ("araştırmacı", "İsim (Çoğul)", "researchers", '"araştırmacılar" (kök: araştırmacı — researchers)'),
    "arkeologlar": ("arkeolog", "İsim (Çoğul)", "archaeologists", '"arkeologlar" (kök: arkeolog — archaeologists)'),
    "askerler": ("asker", "İsim (Çoğul)", "soldiers", '"askerler" (kök: asker — soldiers)'),
    "asırlardır": ("asır", "İsim + Çoğul + Ek-fiil (Zarf)", "for centuries", '"asırlardır" (kök: asır — for centuries)'),
    "atlar": ("at", "İsim (Çoğul) / Fiil (Geniş Zaman)", "horses / jumps", '"atlar" (kök: at — horses)'),
    "ayaküstü": ("ayaküstü", "Zarf", "on the go / on foot", '"ayaküstü" (ayaküstü — on the go / in a rush)'),
    "aydınlar": ("aydın", "İsim (Çoğul)", "intellectuals", '"aydınlar" (kök: aydın — intellectuals)'),
    "ayıklar": ("ayıklamak", "Fiil (Geniş Zaman)", "sorts out / filters", '"ayıklar" (kök: ayıklamak — sorts out / filters)'),
    "azalıyor": ("azalmak", "Fiil (Şimdiki Zaman)", "decreases / diminishes", '"azalıyor" (kök: azalmak — decreases)'),
    "ağırlıklıdır": ("ağırlıklı", "Sıfat + Ek-fiil Yüklem", "is predominantly / weighted toward", '"ağırlıklıdır" (kök: ağırlıklı — is predominantly)'),
    # B
    "bacalar": ("baca", "İsim (Çoğul)", "chimneys", '"bacalar" (kök: baca — chimneys)'),
    "bahistir": ("bahis", "İsim + Ek-fiil Yüklem", "is at issue / subject of discussion", '"bahistir" (kök: bahis — is in question)'),
    "baklagiller": ("baklagil", "İsim (Çoğul)", "legumes / pulses", '"baklagiller" (kök: baklagil — legumes)'),
    "balıkçılar": ("balıkçı", "İsim (Çoğul)", "fishermen", '"balıkçılar" (kök: balıkçı — fishermen)'),
    "basmadık": ("basmak", "Fiilimsi / Sıfat-fiil (Olumsuz)", "unstepped / untouched", '"basmadık" (kök: basmak — unstepped: basmadık yer bırakmadı)'),
    "basıldı": ("basılmak", "Fiil (Görülen Geçmiş Zaman - Edilgen)", "was printed / published", '"basıldı" (kök: basılmak — was printed)'),
    "bağdır": ("bağ", "İsim + Ek-fiil Yüklem", "is a bond / tie", '"bağdır" (kök: bağ — is a bond)'),
    "bağlanmıştı": ("bağlanmak", "Fiil (Duyulan Geçmişin Hikayesi - Edilgen)", "had been connected / attached", '"bağlanmıştı" (kök: bağlanmak — had been connected)'),
    "bağlar": ("bağlamak", "Fiil (Geniş Zaman) / İsim (Çoğul)", "connects / binds", '"bağlar" (kök: bağlamak — connects / bonds)'),
    "bağlıdır": ("bağlı", "Sıfat + Ek-fiil Yüklem", "is dependent on / connected to", '"bağlıdır" (kök: bağlı — is dependent on)'),
    "bağımlıdır": ("bağımlı", "Sıfat + Ek-fiil Yüklem", "is addicted / dependent", '"bağımlıdır" (kök: bağımlı — is dependent)'),
    "başardı": ("başarmak", "Fiil (Görülen Geçmiş Zaman)", "succeeded / achieved", '"başardı" (kök: başarmak — succeeded)'),
    "başarısıdır": ("başarı", "İsim + Ek-fiil Yüklem", "is the success of", '"başarısıdır" (kök: başarı — is the success of)'),
    "başlandı": ("başlanmak", "Fiil (Görülen Geçmiş Zaman - Edilgen)", "was begun / started", '"başlandı" (kök: başlanmak — was begun)'),
    "başyapıtlarıdır": ("başyapıt", "İsim + Çoğul + Ek-fiil", "are the masterpieces of", '"başyapıtlarıdır" (kök: başyapıt — are the masterpieces of)'),
    "beklenir": ("beklenmek", "Fiil (Geniş Zaman - Edilgen)", "is expected", '"beklenir" (kök: beklenmek — is expected)'),
    "bekletilir": ("bekletilmek", "Fiil (Geniş Zaman - Edilgen)", "is kept waiting / steeped", '"bekletilir" (kök: bekletilmek — is steeped / kept)'),
    "belgeler": ("belge", "İsim (Çoğul)", "documents", '"belgeler" (kök: belge — documents)'),
    "benimsedi": ("benimsemek", "Fiil (Görülen Geçmiş Zaman)", "adopted / embraced", '"benimsedi" (kök: benimsemek — adopted)'),
    "benzer": ("benzemek", "Fiil (Geniş Zaman) / Sıfat", "resembles / similar", '"benzer" (kök: benzemek — resembles / similar)'),
    "berraktır": ("berrak", "Sıfat + Ek-fiil Yüklem", "is crystal clear / limpid", '"berraktır" (kök: berrak — is clear)'),
    "besindir": ("besin", "İsim + Ek-fiil Yüklem", "is a nutrient / food", '"besindir" (kök: besin — is a food / nutrient)'),
    "besinler": ("besin", "İsim (Çoğul)", "nutrients / foods", '"besinler" (kök: besin — nutrients)'),
    "beslemekti": ("beslemek", "Fiil (Mastar + Ek-fiil)", "was to feed / nurture", '"beslemekti" (kök: beslemek — was to nurture)'),
    "birer": ("birer", "Üleştirme Sayı Sıfatı", "one each / by one", '"birer" (birer — one each)'),
    "birliğidir": ("birlik", "İsim + Ek-fiil Yüklem", "is the union / unity of", '"birliğidir" (kök: birlik — is the union of)'),
    "biyologlar": ("biyolog", "İsim (Çoğul)", "biologists", '"biyologlar" (kök: biyolog — biologists)'),
    "bizler": ("biz", "Zamir (Çoğul)", "we / us", '"bizler" (kök: biz — we / us)'),
    "bloklar": ("blok", "İsim (Çoğul)", "megaliths / blocks", '"bloklar" (kök: blok — blocks)'),
    "boyalar": ("boya", "İsim (Çoğul)", "paints / dyes", '"boyalar" (kök: boya — paints / dyes)'),
    "boyanır": ("boyanmak", "Fiil (Geniş Zaman - Edilgen)", "is painted / dyed", '"boyanır" (kök: boyanmak — is painted)'),
    "boylar": ("boy", "İsim (Çoğul)", "tribes / sizes / lengths", '"boylar" (kök: boy — nomadic tribes / sizes)'),
    "boyutu": ("boyut", "İsim (İyelik / Belirtme)", "dimension / aspect", '"boyutu" (kök: boyut — dimension)'),
    "bozamazdı": ("bozmak", "Fiil (Yeterlik Olumsuz + Hikaye)", "could not disturb / spoil", '"bozamazdı" (kök: bozmak — could not disturb)'),
    "bozkır": ("bozkır", "İsim", "steppe", '"bozkır" (bozkır — steppe)'),
    "boşalır": ("boşalmak", "Fiil (Geniş Zaman)", "empties / drains", '"boşalır" (kök: boşalmak — empties)'),
    "buettner": ("Buettner", "Özel İsim", "Buettner (Dan Buettner)", '"buettner" (Buettner — researcher)'),
    "bulgar": ("Bulgar", "Özel İsim", "Bulgarian", '"bulgar" (Bulgar — Bulgarian)'),
    "bulunurdu": ("bulunmak", "Fiil (Geniş Zamanın Hikayesi - Edilgen)", "was located / was found", '"bulunurdu" (kök: bulunmak — was located)'),
    "buluşturmuş": ("buluşturmak", "Fiilimsi / Fiil (Duyulan Geçmiş)", "brought together / unified", '"buluşturmuş" (kök: buluşturmak — brought together)'),
    "böcekler": ("böcek", "İsim (Çoğul)", "insects / bugs", '"böcekler" (kök: böcek — insects)'),
    "böceklerdir": ("böcek", "İsim + Çoğul + Ek-fiil", "are insects", '"böceklerdir" (kök: böcek — are insects)'),
    "bölgeler": ("bölge", "İsim (Çoğul)", "regions", '"bölgeler" (kök: bölge — regions)'),
    "bölünür": ("bölünmek", "Fiil (Geniş Zaman - Edilgen)", "is divided / splits", '"bölünür" (kök: bölünmek — is divided)'),
    "bürokratik": ("bürokratik", "Sıfat", "bureaucratic", '"bürokratik" (bürokratik — bureaucratic)'),
    "bütün": ("bütün", "Sıfat / Belirteç", "all / whole / entire", '"bütün" (bütün — whole / all)'),
    "büyür": ("büyümek", "Fiil (Geniş Zaman)", "grows / expands", '"büyür" (kök: büyümek — grows)'),
    "bırakmadı": ("bırakmak", "Fiil (Görülen Geçmiş Zaman - Olumsuz)", "did not leave / left no", '"bırakmadı" (kök: bırakmak — did not leave)'),
    # C / Ç
    "canavar": ("canavar", "İsim", "monster / beast", '"canavar" (canavar — monster)'),
    "cevaptır": ("cevap", "İsim + Ek-fiil Yüklem", "is an answer / response", '"cevaptır" (kök: cevap — is an answer)'),
    "cezveler": ("cezve", "İsim (Çoğul)", "cezves (Turkish coffee pots)", '"cezveler" (kök: cezve — coffee pots)'),
    "ciddi": ("ciddi", "Sıfat", "serious / severe", '"ciddi" (ciddi — serious / severe)'),
    "cumhuriyeti": ("cumhuriyet", "İsim (İyelik)", "republic of", '"cumhuriyeti" (kök: cumhuriyet — republic)'),
    "çalgılarıdır": ("çalgı", "İsim + Çoğul + Ek-fiil", "are musical instruments of", '"çalgılarıdır" (kök: çalgı — are instruments of)'),
    "çalgısıdır": ("çalgı", "İsim + Ek-fiil Yüklem", "is the musical instrument of", '"çalgısıdır" (kök: çalgı — is the instrument of)'),
    "çamur": ("çamur", "İsim", "mud / clay", '"çamur" (çamur — mud)'),
    "çağırdı": ("çağırmak", "Fiil (Görülen Geçmiş Zaman)", "called / invited / urged", '"çağırdı" (kök: çağırmak — urged / called)'),
    "çağırır": ("çağırmak", "Fiil (Geniş Zaman)", "invites / summons", '"çağırır" (kök: çağırmak — invites / calls)'),
    "çiftçiler": ("çiftçi", "İsim (Çoğul)", "farmers", '"çiftçiler" (kök: çiftçi — farmers)'),
    "çizgiler": ("çizgi", "İsim (Çoğul)", "lines / contours", '"çizgiler" (kök: çizgi — lines)'),
    "çizilir": ("çizilmek", "Fiil (Geniş Zaman - Edilgen)", "is drawn / outlined", '"çizilir" (kök: çizilmek — is drawn)'),
    "çoğalır": ("çoğalmak", "Fiil (Geniş Zaman)", "multiplies / increases", '"çoğalır" (kök: çoğalmak — multiplies)'),
    "çubuklar": ("çubuk", "İsim (Çoğul)", "rods / sticks", '"çubuklar" (kök: çubuk — rods / sticks)'),
    # D
    "daldı": ("dalmak", "Fiil (Görülen Geçmiş Zaman)", "dove / fell into (sleep)", '"daldı" (kök: dalmak — fell into)'),
    "damar": ("damar", "İsim", "vein / vessel", '"damar" (damar — vein)'),
    "damlatılır": ("damlatılmak", "Fiil (Geniş Zaman - Edilgen)", "is dripped", '"damlatılır" (kök: damlatılmak — is dripped)'),
    "davetidir": ("davet", "İsim + Ek-fiil Yüklem", "is an invitation of", '"davetidir" (kök: davet — is an invitation of)'),
    "demektir": ("demek", "Fiil (Mastar + Ek-fiil)", "means / signifies", '"demektir" (kök: demek — means)'),
    "demlenir": ("demlenmek", "Fiil (Geniş Zaman - Edilgen)", "is brewed / steeped", '"demlenir" (kök: demlenmek — is brewed)'),
    "demlenmiş": ("demlenmek", "Fiilimsi / Fiil (Duyulan Geçmiş)", "brewed / steeped", '"demlenmiş" (kök: demlenmek — brewed)'),
    "demokratik": ("demokratik", "Sıfat", "democratic", '"demokratik" (demokratik — democratic)'),
    "depolar": ("depolamak", "Fiil (Geniş Zaman) / İsim (Çoğul)", "stores / warehouses", '"depolar" (kök: depolamak — stores)'),
    "derdi": ("demek", "Fiil (Geniş Zamanın Hikayesi)", "would say / called", '"derdi" (kök: demek — would say)'),
    "derinleşti": ("derinleşmek", "Fiil (Görülen Geçmiş Zaman)", "deepened", '"derinleşti" (kök: derinleşmek — deepened)'),
    "derstir": ("ders", "İsim + Ek-fiil Yüklem", "is a lesson", '"derstir" (kök: ders — is a lesson)'),
    "devler": ("dev", "İsim (Çoğul)", "giants", '"devler" (kök: dev — giants)'),
    "devreder": ("devretmek", "Fiil (Geniş Zaman)", "transfers / hands over", '"devreder" (kök: devretmek — transfers)'),
    "deyiverdi": ("deyivermek", "Fiil (Tezlik Fiili / Görülen Geçmiş)", "blurted out / said suddenly", '"deyiverdi" (kök: demek — blurted out)'),
    "dillendirir": ("dillendirmek", "Fiil (Geniş Zaman)", "articulates / voices", '"dillendirir" (kök: dillendirmek — voices)'),
    "dimdik": ("dimdik", "Zarf / Sıfat", "upright / steadfast", '"dimdik" (dimdik — upright / steadfast)'),
    "doludur": ("dolu", "Sıfat + Ek-fiil Yüklem", "is full of", '"doludur" (kök: dolu — is full of)'),
    "doymuş": ("doymak", "Fiilimsi / Sıfat (Duyulan Geçmiş)", "saturated / sated", '"doymuş" (kök: doymak — saturated: doymuş yağ)'),
    "doğmuştu": ("doğmak", "Fiil (Duyulan Geçmişin Hikayesi)", "had arisen / was born", '"doğmuştu" (kök: doğmak — had arisen)'),
    "dünyeviydi": ("dünyevi", "Sıfat + Ek-fiil (Görülen Geçmiş)", "was worldly", '"dünyeviydi" (kök: dünyevi — was worldly)'),
    "düşmanlar": ("düşman", "İsim (Çoğul)", "enemies", '"düşmanlar" (kök: düşman — enemies)'),
    # E
    "edemezdi": ("etmek", "Fiil (Yeterlik Olumsuz + Hikaye)", "could not do / foresee", '"edemezdi" (kök: etmek — could not do: tahmin edemezdi)'),
    "edildi": ("edilmek", "Fiil (Görülen Geçmiş Zaman - Edilgen)", "was done / built", '"edildi" (kök: edilmek — was done: inşa edildi)'),
    "edilir": ("edilmek", "Fiil (Geniş Zaman - Edilgen)", "is done / made", '"edilir" (kök: edilmek — is done)'),
    "edilmiş": ("edilmek", "Fiilimsi / Fiil (Duyulan Geçmiş - Edilgen)", "done / constructed / made", '"edilmiş" (kök: edilmek — constructed / made)'),
    "edilmişti": ("edilmek", "Fiil (Duyulan Geçmişin Hikayesi - Edilgen)", "had been done / constructed", '"edilmişti" (kök: edilmek — had been done)'),
    "efsanesidir": ("efsane", "İsim + Ek-fiil Yüklem", "is the legend of", '"efsanesidir" (kök: efsane — is the legend of)'),
    "eklenir": ("eklenmek", "Fiil (Geniş Zaman - Edilgen)", "is added", '"eklenir" (kök: eklenmek — is added)'),
    "endişeler": ("endişe", "İsim (Çoğul)", "concerns / anxieties", '"endişeler" (kök: endişe — anxieties)'),
    "esastır": ("esas", "İsim / Sıfat + Ek-fiil Yüklem", "is fundamental / essential", '"esastır" (kök: esas — is essential)'),
    "eseridir": ("eser", "İsim + Ek-fiil Yüklem", "is the work of", '"eseridir" (kök: eser — is the work of)'),
    "estetik": ("estetik", "İsim / Sıfat", "aesthetics / aesthetic", '"estetik" (estetik — aesthetic / aesthetics)'),
    "etkiler": ("etkilemek", "Fiil (Geniş Zaman) / İsim (Çoğul)", "influences / affects / effects", '"etkiler" (kök: etkilemek — influences)'),
    "etkilidir": ("etkili", "Sıfat + Ek-fiil Yüklem", "is effective", '"etkilidir" (kök: etkili — is effective)'),
    "ettirdi": ("ettirmek", "Fiil (Ettirgen + Görülen Geçmiş)", "made (someone) do", '"ettirdi" (kök: etmek — made do: yemin ettirdi)'),
    "ettirilebilir": ("ettirilmek", "Fiil (Yeterlik Geniş Zaman - Edilgen)", "can be caused to be done", '"ettirilebilir" (kök: ettirilmek — can be made to be done)'),
    "eğlendirir": ("eğlendirmek", "Fiil (Geniş Zaman)", "entertains", '"eğlendirir" (kök: eğlendirmek — entertains)'),
    "eşyalar": ("eşya", "İsim (Çoğul)", "items / belongings", '"eşyalar" (kök: eşya — items)'),
    # F
    "felaketler": ("felaket", "İsim (Çoğul)", "disasters / catastrophes", '"felaketler" (kök: felaket — disasters)'),
    "figürdür": ("figür", "İsim + Ek-fiil Yüklem", "is a figure", '"figürdür" (kök: figür — is a figure)'),
    "filtrelenir": ("filtrelenmek", "Fiil (Geniş Zaman - Edilgen)", "is filtered", '"filtrelenir" (kök: filtrelenmek — is filtered)'),
    "fotoğraflar": ("fotoğraf", "İsim (Çoğul)", "photographs", '"fotoğraflar" (kök: fotoğraf — photographs)'),
    "fırçalar": ("fırça", "İsim (Çoğul)", "brushes", '"fırçalar" (kök: fırça — brushes)'),
    "fırınlar": ("fırın", "İsim (Çoğul)", "ovens / kilns", '"fırınlar" (kök: fırın — ovens)'),
    "fırınlarlar": ("fırınlamak", "Fiil (Geniş Zaman 3. Çoğul)", "they bake / roast", '"fırınlarlar" (kök: fırınlamak — they bake)'),
    "fısıltısıdır": ("fısıltı", "İsim + Ek-fiil Yüklem", "is the whisper of", '"fısıltısıdır" (kök: fısıltı — is the whisper of)'),
    # G
    "gecikmedi": ("gecikmek", "Fiil (Görülen Geçmiş Zaman - Olumsuz)", "did not delay / wasted no time", '"gecikmedi" (kök: gecikmek — did not delay)'),
    "gelişmeler": ("gelişme", "İsim (Çoğul)", "developments", '"gelişmeler" (kök: gelişme — developments)'),
    "geliştirilmiştir": ("geliştirilmek", "Fiil (Duyulan Geçmiş + Bildirme - Edilgen)", "has been developed", '"geliştirilmiştir" (kök: geliştirilmek — has been developed)'),
    "genetik": ("genetik", "Sıfat / İsim", "genetic", '"genetik" (genetik — genetic)'),
    "getirilmiş": ("getirilmek", "Fiilimsi / Fiil (Duyulan Geçmiş - Edilgen)", "brought / made into", '"getirilmiş" (kök: getirilmek — brought: aceleye getirilmiş)'),
    "geziler": ("gezi", "İsim (Çoğul)", "trips / voyages", '"geziler" (kök: gezi — voyages)'),
    "giyinirdi": ("giyinmek", "Fiil (Geniş Zamanın Hikayesi)", "would dress / used to wear", '"giyinirdi" (kök: giyinmek — would dress)'),
    "gizlidir": ("gizli", "Sıfat + Ek-fiil Yüklem", "is hidden / secret", '"gizlidir" (kök: gizli — is hidden)'),
    "gölgesindeydi": ("gölge", "İsim + İyelik + Bulunma + Ek-fiil", "was in the shadow of", '"gölgesindeydi" (kök: gölge — was in the shadow of)'),
    "gönderir": ("göndermek", "Fiil (Geniş Zaman)", "sends / transmits", '"gönderir" (kök: göndermek — sends)'),
    "görmüyordu": ("görmek", "Fiil (Şimdiki Zamanın Hikayesi - Olumsuz)", "was not seeing / did not see", '"görmüyordu" (kök: görmek — did not see)'),
    "görülmesidir": ("görülme", "İsim-fiil + Ek-fiil Yüklem", "is the being seen / viewing of", '"görülmesidir" (kök: görülmek — is the viewing of)'),
    "görünebilir": ("görünmek", "Fiil (Yeterlik Geniş Zaman)", "can appear / may seem", '"görünebilir" (kök: görünmek — may seem)'),
    "göstergesidir": ("gösterge", "İsim + Ek-fiil Yüklem", "is an indicator / sign of", '"göstergesidir" (kök: gösterge — is an indicator of)'),
    "gözler": ("göz", "İsim (Çoğul)", "eyes", '"gözler" (kök: göz — eyes: gözler önüne seriyor)'),
    "güldürür": ("güldürmek", "Fiil (Geniş Zaman)", "makes (people) laugh", '"güldürür" (kök: gülmek — makes laugh)'),
    "gürültüler": ("gürültü", "İsim (Çoğul)", "noises", '"gürültüler" (kök: gürültü — noises)'),
    "güçler": ("güç", "İsim (Çoğul)", "powers / forces", '"güçler" (kök: güç — powers / forces)'),
    "güçtür": ("güç", "Sıfat + Ek-fiil Yüklem", "is difficult / hard", '"güçtür" (kök: güç — is difficult)'),
    # H
    "haber": ("haber", "İsim", "news / word", '"haber" (haber — news)'),
    "hakikatler": ("hakikat", "İsim (Çoğul)", "truths / realities", '"hakikatler" (kök: hakikat — realities / truths)'),
    "halkalar": ("halka", "İsim (Çoğul)", "rings / circles", '"halkalar" (kök: halka — rings)'),
    "harcıyor": ("harcamak", "Fiil (Şimdiki Zaman)", "spends / consumes", '"harcıyor" (kök: harcamak — spends / consumes)'),
    "hareketi": ("hareket", "İsim (İyelik / Belirtme)", "movement / motion", '"hareketi" (kök: hareket — movement)'),
    "hareketler": ("hareket", "İsim (Çoğul)", "movements / gestures", '"hareketler" (kök: hareket — movements)'),
    "harmanlanmış": ("harmanlanmak", "Fiilimsi / Fiil (Duyulan Geçmiş)", "blended / harmonized", '"harmanlanmış" (kök: harmanlanmak — blended)'),
    "hasreti": ("hasret", "İsim (İyelik / Belirtme)", "longing / yearning", '"hasreti" (kök: hasret — longing)'),
    "haykırmıştır": ("haykırmak", "Fiil (Duyulan Geçmiş + Bildirme)", "cried out / proclaimed", '"haykırmıştır" (kök: haykırmak — cried out)'),
    "hazreti": ("hazret", "İsim / Saygı Unvanı", "Venerable / Hazrat", '"hazreti" (hazret — venerable title)'),
    "hazırlanır": ("hazırlanmak", "Fiil (Geniş Zaman - Edilgen)", "is prepared", '"hazırlanır" (kök: hazırlanmak — is prepared)'),
    "hedefler": ("hedef", "İsim (Çoğul)", "targets / goals", '"hedefler" (kök: hedef — goals)'),
    "hikâyeler": ("hikâye", "İsim (Çoğul)", "stories / tales", '"hikâyeler" (kök: hikâye — stories)'),
    "hiçbir": ("hiçbir", "Belgisiz Sıfat", "no / not any", '"hiçbir" (hiçbir — no / none)'),
    "hristiyanlar": ("Hristiyan", "Özel İsim (Çoğul)", "Christians", '"hristiyanlar" (kök: Hristiyan — Christians)'),
    "hummalı": ("hummalı", "Sıfat", "feverish / intense", '"hummalı" (hummalı — feverish / intense activity)'),
    "huzur": ("huzur", "İsim", "peace / tranquility", '"huzur" (huzur — tranquility)'),
    "hürmeti": ("hürmet", "İsim (İyelik / Belirtme)", "reverence / respect", '"hürmeti" (kök: hürmet — reverence)'),
    "hürmetin": ("hürmet", "İsim (Tamlayan)", "of reverence / respect", '"hürmetin" (kök: hürmet — of reverence)'),
    "hızlanır": ("hızlanmak", "Fiil (Geniş Zaman)", "accelerates / speeds up", '"hızlanır" (kök: hızlanmak — speeds up)'),
    # I / İ
    "ibadethaneler": ("ibadethane", "İsim (Çoğul)", "places of worship / sanctuaries", '"ibadethaneler" (kök: ibadethane — sanctuaries)'),
    "ibarettir": ("ibaret", "Sıfat + Ek-fiil Yüklem", "consists of / is merely", '"ibarettir" (kök: ibaret — consists of)'),
    "ifadesidir": ("ifade", "İsim + Ek-fiil Yüklem", "is an expression of", '"ifadesidir" (kök: ifade — is an expression of)'),
    "ihanetin": ("ihanet", "İsim (Tamlayan)", "of betrayal", '"ihanetin" (kök: ihanet — of betrayal)'),
    "ihtardır": ("ihtar", "İsim + Ek-fiil Yüklem", "is a warning / reminder", '"ihtardır" (kök: ihtar — is a warning)'),
    "incelerler": ("incelemek", "Fiil (Geniş Zaman 3. Çoğul)", "they examine / analyze", '"incelerler" (kök: incelemek — they examine)'),
    "interneti": ("internet", "İsim (Belirtme)", "the internet", '"interneti" (kök: internet — the internet)'),
    "ispatladı": ("ispatlamak", "Fiil (Görülen Geçmiş Zaman)", "proved / demonstrated", '"ispatladı" (kök: ispatlamak — proved)'),
    "iyileşti": ("iyileşmek", "Fiil (Görülen Geçmiş Zaman)", "healed / recovered", '"iyileşti" (kök: iyileşmek — recovered)'),
    "izler": ("iz", "İsim (Çoğul)", "traces / marks", '"izler" (kök: iz — traces / marks)'),
    "içecektir": ("içecek", "İsim + Ek-fiil Yüklem", "is a beverage", '"içecektir" (kök: içecek — is a beverage)'),
    "içerler": ("içmek", "Fiil (Geniş Zaman 3. Çoğul)", "they drink", '"içerler" (kök: içmek — they drink)'),
    "iğneler": ("iğne", "İsim (Çoğul)", "needles", '"iğneler" (kök: iğne — needles)'),
    "i̇nsanlar": ("insan", "İsim (Çoğul)", "people / humans", '"insanlar" (kök: insan — humans)'),
    # K
    "kademeli": ("kademeli", "Sıfat", "gradual / stepped", '"kademeli" (kademeli — gradual / staged)'),
    "kadın": ("kadın", "İsim", "woman", '"kadın" (kadın — woman)'),
    "kahvehaneler": ("kahvehane", "İsim (Çoğul)", "coffeehouses", '"kahvehaneler" (kök: kahvehane — coffeehouses)'),
    "kalanlar": ("kalmak", "Fiilimsi / Sıfat-fiil (Çoğul)", "those remaining / survivors", '"kalanlar" (kök: kalmak — those who remain)'),
    "kalbidir": ("kalp", "İsim + Ek-fiil Yüklem", "is the heart of", '"kalbidir" (kök: kalp — is the heart of)'),
    "kalmasıdır": ("kalma", "İsim-fiil + Ek-fiil Yüklem", "is the remaining / staying of", '"kalmasıdır" (kök: kalmak — is the staying of)'),
    "kalmışlardır": ("kalmak", "Fiil (Duyulan Geçmiş 3. Çoğul + Bildirme)", "have remained", '"kalmışlardır" (kök: kalmak — have remained)'),
    "kandırır": ("kandırmak", "Fiil (Geniş Zaman)", "deceives / tricks", '"kandırır" (kök: kandırmak — deceives)'),
    "kanıtlıyor": ("kanıtlamak", "Fiil (Şimdiki Zaman)", "proves / demonstrates", '"kanıtlıyor" (kök: kanıtlamak — proves)'),
    "karıştırılmış": ("karıştırılmak", "Fiilimsi / Fiil (Duyulan Geçmiş - Edilgen)", "mixed / blended", '"karıştırılmış" (kök: karıştırılmak — mixed)'),
    "karıştırılır": ("karıştırılmak", "Fiil (Geniş Zaman - Edilgen)", "is stirred / mixed", '"karıştırılır" (kök: karıştırılmak — is stirred)'),
    "karşılar": ("karşılamak", "Fiil (Geniş Zaman)", "meets / fulfills", '"karşılar" (kök: karşılamak — meets / welcomes)'),
    "karşılayacak": ("karşılamak", "Fiil (Gelecek Zaman / Sıfat-fiil)", "will meet / satisfy", '"karşılayacak" (kök: karşılamak — will meet)'),
    "karşıyadır": ("karşı", "İsim + Yönelme + Ek-fiil", "is facing / up against", '"karşıyadır" (kök: karşı — is facing: karşı karşıyadır)'),
    "katlar": ("kat", "İsim (Çoğul) / Fiil (Geniş Zaman)", "floors / layers", '"katlar" (kök: kat — floors / layers)'),
    "kavuştu": ("kavuşmak", "Fiil (Görülen Geçmiş Zaman)", "attained / gained", '"kavuştu" (kök: kavuşmak — attained)'),
    "kavşaklar": ("kavşak", "İsim (Çoğul)", "crossroads / junctions", '"kavşaklar" (kök: kavşak — crossroads)'),
    "kaydeder": ("kaydetmek", "Fiil (Geniş Zaman)", "records / transfers", '"kaydeder" (kök: kaydetmek — records)'),
    "kaydetmiştir": ("kaydetmek", "Fiil (Duyulan Geçmiş + Bildirme)", "has recorded / documented", '"kaydetmiştir" (kök: kaydetmek — has recorded)'),
    "kaynaklanır": ("kaynaklanmak", "Fiil (Geniş Zaman)", "originates / stems from", '"kaynaklanır" (kök: kaynaklanmak — stems from)'),
    "kaynar": ("kaynamak", "Fiil (Geniş Zaman)", "boils / simmers", '"kaynar" (kök: kaynamak — boils)'),
    "kazınmış": ("kazınmak", "Fiilimsi / Fiil (Duyulan Geçmiş - Edilgen)", "carved / engraved", '"kazınmış" (kök: kazınmak — carved / engraved)'),
    "kenar": ("kenar", "İsim", "edge / rim / brim", '"kenar" (kenar — rim / edge)'),
    "kesilir": ("kesilmek", "Fiil (Geniş Zaman - Edilgen)", "is cut / sliced", '"kesilir" (kök: kesilmek — is cut)'),
    "keyfidir": ("keyfi", "Sıfat + Ek-fiil Yüklem", "is arbitrary", '"keyfidir" (kök: keyfi — is arbitrary)'),
    "kiliseler": ("kilise", "İsim (Çoğul)", "churches", '"kiliseler" (kök: kilise — churches)'),
    "kinayeler": ("kinaye", "İsim (Çoğul)", "allusions / ironies", '"kinayeler" (kök: kinaye — ironies / allusions)'),
    "kolaylaştırır": ("kolaylaştırmak", "Fiil (Geniş Zaman - Ettirgen)", "facilitates / makes easier", '"kolaylaştırır" (kök: kolaylaştırmak — facilitates)'),
    "kraliçedir": ("kraliçe", "İsim + Ek-fiil Yüklem", "is queen", '"kraliçedir" (kök: kraliçe — is queen)'),
    "kritik": ("kritik", "Sıfat", "critical / vital", '"kritik" (kritik — critical)'),
    "krizdir": ("kriz", "İsim + Ek-fiil Yüklem", "is a crisis", '"krizdir" (kök: kriz — is a crisis)'),
    "kucaktır": ("kucak", "İsim + Ek-fiil Yüklem", "is an embrace / haven", '"kucaktır" (kök: kucak — is an embrace)'),
    "kudreti": ("kudret", "İsim (İyelik / Belirtme)", "power / potency", '"kudreti" (kök: kudret — power)'),
    "kuklalar": ("kukla", "İsim (Çoğul)", "puppets", '"kuklalar" (kök: kukla — puppets)'),
    "kurgulanmış": ("kurgulanmak", "Fiilimsi / Fiil (Duyulan Geçmiş - Edilgen)", "constructed / orchestrated", '"kurgulanmış" (kök: kurgulanmak — constructed)'),
    "kurtulmuyor": ("kurtulmak", "Fiil (Şimdiki Zaman - Olumsuz)", "does not escape / break free", '"kurtulmuyor" (kök: kurtulmak — does not break free)'),
    "kurulmayacak": ("kurulmak", "Fiil (Gelecek Zaman - Olumsuz Edilgen)", "will not be established", '"kurulmayacak" (kök: kurulmak — will not be established)'),
    "kuruyemişler": ("kuruyemiş", "İsim (Çoğul)", "nuts and dried fruits", '"kuruyemişler" (kök: kuruyemiş — dried fruits & nuts)'),
    "kusurlar": ("kusur", "İsim (Çoğul)", "imperfections / flaws", '"kusurlar" (kök: kusur — flaws / imperfections)'),
    "kutlamalar": ("kutlama", "İsim (Çoğul)", "celebrations", '"kutlamalar" (kök: kutlama — celebrations)'),
    "kutlanır": ("kutlanmak", "Fiil (Geniş Zaman - Edilgen)", "is celebrated", '"kutlanır" (kök: kutlanmak — is celebrated)'),
    "kuyular": ("kuyu", "İsim (Çoğul)", "wells", '"kuyular" (kök: kuyu — wells)'),
    "kâğıdın": ("kâğıt", "İsim (Tamlayan)", "of the paper", '"kâğıdın" (kök: kâğıt — of the paper)'),
    "köleydi": ("köle", "İsim + Ek-fiil (Görülen Geçmiş)", "was a slave", '"köleydi" (kök: köle — was an enslaved person)'),
    "köprüler": ("köprü", "İsim (Çoğul)", "bridges", '"köprüler" (kök: köprü — bridges)'),
    "köylüler": ("köylü", "İsim (Çoğul)", "villagers", '"köylüler" (kök: köylü — villagers)'),
    "kültürüdür": ("kültür", "İsim + Ek-fiil Yüklem", "is the culture of", '"kültürüdür" (kök: kültür — is the culture of)'),
    "kürsüydü": ("kürsü", "İsim + Ek-fiil (Görülen Geçmiş)", "was a rostrum / pulpit", '"kürsüydü" (kök: kürsü — was a civic rostrum)'),
    "kırıklar": ("kırık", "İsim (Çoğul)", "shards / fractures", '"kırıklar" (kök: kırık — shards / fractures)'),
    # L
    "labirenti": ("labirent", "İsim (Belirtme / İyelik)", "labyrinth of", '"labirenti" (kök: labirent — labyrinth)'),
    "laboratuvar": ("laboratuvar", "İsim", "laboratory", '"laboratuvar" (laboratuvar — laboratory)'),
    "laktik": ("laktik", "Sıfat", "lactic", '"laktik" (laktik — lactic: laktik asit)'),
    "lezzeti": ("lezzet", "İsim (İyelik / Belirtme)", "flavor / taste", '"lezzeti" (kök: lezzet — flavor)'),
    "lezzetin": ("lezzet", "İsim (Tamlayan)", "of flavor / taste", '"lezzetin" (kök: lezzet — of flavor)'),
    "lezzetler": ("lezzet", "İsim (Çoğul)", "flavors / delicacies", '"lezzetler" (kök: lezzet — flavors)'),
    "lezzetlidir": ("lezzetli", "Sıfat + Ek-fiil Yüklem", "is delicious", '"lezzetlidir" (kök: lezzetli — is delicious)'),
    "liderdi": ("lider", "İsim + Ek-fiil (Görülen Geçmiş)", "was a leader", '"liderdi" (kök: lider — was a leader)'),
    # M
    "maddeydi": ("madde", "İsim + Ek-fiil (Görülen Geçmiş)", "was a substance / matter", '"maddeydi" (kök: madde — was a substance)'),
    "mahsur": ("mahsur", "Sıfat", "trapped / stranded", '"mahsur" (mahsur — trapped: mahsur kalmak)'),
    "malzemedir": ("malzeme", "İsim + Ek-fiil Yüklem", "is a material", '"malzemedir" (kök: malzeme — is a material)'),
    "manifestosudur": ("manifesto", "İsim + Ek-fiil Yüklem", "is the manifesto of", '"manifestosudur" (kök: manifesto — is the manifesto of)'),
    "mantarlar": ("mantar", "İsim (Çoğul)", "mushrooms / fungi", '"mantarlar" (kök: mantar — fungi / mushrooms)'),
    "mantık": ("mantık", "İsim", "logic / reason", '"mantık" (mantık — logic)'),
    "mardin": ("Mardin", "Özel İsim", "Mardin (city in SE Turkey)", '"mardin" (Mardin — historical city)'),
    "mayaladılar": ("mayalamak", "Fiil (Görülen Geçmiş 3. Çoğul)", "they fermented", '"mayaladılar" (kök: mayalamak — fermented)'),
    "mayalar": ("maya", "İsim (Çoğul)", "yeasts / starter cultures", '"mayalar" (kök: maya — starter cultures)'),
    "mecazıdır": ("mecaz", "İsim + Ek-fiil Yüklem", "is a metaphor of", '"mecazıdır" (kök: mecaz — is a metaphor of)'),
    "medeniyetin": ("medeniyet", "İsim (Tamlayan)", "of civilization", '"medeniyetin" (kök: medeniyet — of civilization)'),
    "merkezler": ("merkez", "İsim (Çoğul)", "centers", '"merkezler" (kök: merkez — centers)'),
    "meselesiydi": ("mesele", "İsim + Ek-fiil (Görülen Geçmiş)", "was a matter of", '"meselesiydi" (kök: mesele — was a matter of)'),
    "meşhur": ("meşhur", "Sıfat", "famous / renowned", '"meşhur" (meşhur — famous: meşhur oldu)'),
    "mikroorganizmalar": ("mikroorganizma", "İsim (Çoğul)", "microorganisms", '"mikroorganizmalar" (kök: mikroorganizma — microorganisms)'),
    "mikrotonlar": ("mikroton", "İsim (Çoğul)", "microtones", '"mikrotonlar" (kök: mikroton — microtones)'),
    "mimarıdır": ("mimar", "İsim + Ek-fiil Yüklem", "is the architect of", '"mimarıdır" (kök: mimar — is the architect of)'),
    "mutfaklar": ("mutfak", "İsim (Çoğul)", "kitchens / cuisines", '"mutfaklar" (kök: mutfak — kitchens)'),
    "mühürlenir": ("mühürlenmek", "Fiil (Geniş Zaman - Edilgen)", "is sealed", '"mühürlenir" (kök: mühürlenmek — is sealed)'),
    "müzisyendir": ("müzisyen", "İsim + Ek-fiil Yüklem", "is a musician", '"müzisyendir" (kök: müzisyen — is a musician)'),
    # N
    "nasır": ("nasır", "İsim", "callus", '"nasır" (nasır — callus)'),
    "nettir": ("net", "Sıfat + Ek-fiil Yüklem", "is clear / distinct", '"nettir" (kök: net — is clear)'),
    "neydir": ("ney", "İsim + Ek-fiil Yüklem", "is the ney flute", '"neydir" (kök: ney — is the reed flute)'),
    "niteliğindedir": ("nitelik", "İsim + İyelik + Bulunma + Ek-fiil", "has the character of / is in the nature of", '"niteliğindedir" (kök: nitelik — has the nature of)'),
    "notlar": ("not", "İsim (Çoğul)", "notes", '"notlar" (kök: not — notes)'),
    # O / Ö
    "odaklanır": ("odaklanmak", "Fiil (Geniş Zaman)", "focuses", '"odaklanır" (kök: odaklanmak — focuses)'),
    "odaklanırdı": ("odaklanmak", "Fiil (Geniş Zamanın Hikayesi)", "would focus / used to focus", '"odaklanırdı" (kök: odaklanmak — would focus)'),
    "odalar": ("oda", "İsim (Çoğul)", "rooms", '"odalar" (kök: oda — rooms)'),
    "olabilir": ("olmak", "Fiil (Yeterlik Geniş Zaman)", "can be / may happen", '"olabilir" (kök: olmak — can be)'),
    "olabilirler": ("olmak", "Fiil (Yeterlik Geniş Zaman 3. Çoğul)", "can be / may be", '"olabilirler" (kök: olmak — can be)'),
    "olaylar": ("olay", "İsim (Çoğul)", "events / incidents", '"olaylar" (kök: olay — events)'),
    "olayıdır": ("olay", "İsim + Ek-fiil Yüklem", "is the event of", '"olayıdır" (kök: olay — is the event of)'),
    "olağanüstü": ("olağanüstü", "Sıfat / Zarf", "extraordinary / remarkable", '"olağanüstü" (olağanüstü — extraordinary)'),
    "olmadı": ("olmak", "Fiil (Görülen Geçmiş Zaman - Olumsuz)", "did not become / was never", '"olmadı" (kök: olmak — was not)'),
    "organizmalar": ("organizma", "İsim (Çoğul)", "organisms", '"organizmalar" (kök: organizma — organisms)'),
    "ortaklıktır": ("ortaklık", "İsim + Ek-fiil Yüklem", "is a partnership / symbiosis", '"ortaklıktır" (kök: ortaklık — is a partnership)'),
    "otururdu": ("oturmak", "Fiil (Geniş Zamanın Hikayesi)", "would sit / sat", '"otururdu" (kök: oturmak — would sit)'),
    "oynatır": ("oynatmak", "Fiil (Geniş Zaman - Ettirgen)", "manipulates / animates puppets", '"oynatır" (kök: oynamak — manipulates / animates)'),
    "oyulmuş": ("oyulmak", "Fiilimsi / Fiil (Duyulan Geçmiş - Edilgen)", "carved / hollowed out", '"oyulmuş" (kök: oyulmak — hollowed out / carved)'),
    "oyunudur": ("oyun", "İsim + Ek-fiil Yüklem", "is the play / game of", '"oyunudur" (kök: oyun — is the game / play of)'),
    "ozanıdır": ("ozan", "İsim + Ek-fiil Yüklem", "is the bard / folk poet of", '"ozanıdır" (kök: ozan — is the bard of)'),
    "ömürler": ("ömür", "İsim (Çoğul)", "lifespans / lives", '"ömürler" (kök: ömür — lifespans)'),
    "örnekleridir": ("örnek", "İsim + Çoğul + Ek-fiil", "are examples of", '"örnekleridir" (kök: örnek — are examples of)'),
    "örtüşür": ("örtüşmek", "Fiil (Geniş Zaman)", "overlaps / coincides", '"örtüşür" (kök: örtüşmek — coincides / overlaps)'),
    "özgür": ("özgür", "Sıfat", "free", '"özgür" (özgür — free)'),
    "öğreti": ("öğreti", "İsim", "teaching / doctrine", '"öğreti" (öğreti — teaching / doctrine)'),
    "öğütlemektedir": ("öğütlemek", "Fiil (Süreklilik / Şimdiki Zaman -mekte)", "advises / counsels", '"öğütlemektedir" (kök: öğütlemek — advises)'),
    # P
    "padişahlar": ("padişah", "İsim (Çoğul)", "sultans", '"padişahlar" (kök: padişah — sultans)'),
    "parlar": ("parlamak", "Fiil (Geniş Zaman)", "glows / shines", '"parlar" (kök: parlamak — shines)'),
    "parçasıdır": ("parça", "İsim + Ek-fiil Yüklem", "is a part of", '"parçasıdır" (kök: parça — is part of)'),
    "pasteur": ("Pasteur", "Özel İsim", "Pasteur (Louis Pasteur)", '"pasteur" (Pasteur — scientist)'),
    "pazarlıktır": ("pazarlık", "İsim + Ek-fiil Yüklem", "is bargaining / negotiation", '"pazarlıktır" (kök: pazarlık — is bargaining)'),
    "perdeler": ("perde", "İsim (Çoğul)", "curtains / screens", '"perdeler" (kök: perde — screens)'),
    "perdesidir": ("perde", "İsim + Ek-fiil Yüklem", "is the screen of", '"perdesidir" (kök: perde — is the screen of)'),
    "pişirilir": ("pişirilmek", "Fiil (Geniş Zaman - Edilgen)", "is brewed / cooked", '"pişirilir" (kök: pişirilmek — is brewed / cooked)'),
    "pişirilirdi": ("pişirilmek", "Fiil (Geniş Zamanın Hikayesi - Edilgen)", "used to be brewed / cooked", '"pişirilirdi" (kök: pişirilmek — used to be brewed)'),
    "poetik": ("poetik", "Sıfat", "poetic", '"poetik" (poetik — poetic)'),
    "pratik": ("pratik", "Sıfat / İsim", "practical / practice", '"pratik" (pratik — practical)'),
    "psikologlar": ("psikolog", "İsim (Çoğul)", "psychologists", '"psikologlar" (kök: psikolog — psychologists)'),
    # R
    "rahatlatır": ("rahatlatmak", "Fiil (Geniş Zaman - Ettirgen)", "relaxes / soothes", '"rahatlatır" (kök: rahatlamak — soothes / relaxes)'),
    "renklendirilmiş": ("renklendirilmek", "Fiilimsi / Fiil (Duyulan Geçmiş - Edilgen)", "colored / tinted", '"renklendirilmiş" (kök: renklendirilmek — colored)'),
    "renkliydi": ("renkli", "Sıfat + Ek-fiil (Görülen Geçmiş)", "was colorful / vibrant", '"renkliydi" (kök: renkli — was vibrant)'),
    "romantik": ("romantik", "Sıfat", "romantic / sentimental", '"romantik" (romantik — sentimental / romantic)'),
    # S / Ş
    "sabahattin": ("Sabahattin", "Özel İsim", "Sabahattin (Sabahattin Eyüboğlu)", '"sabahattin" (Sabahattin — author/thinker)'),
    "sabır": ("sabır", "İsim", "patience", '"sabır" (sabır — patience)'),
    "sadakatin": ("sadakat", "İsim (Tamlayan)", "of loyalty / devotion", '"sadakatin" (kök: sadakat — of loyalty)'),
    "sadeleşti": ("sadeleşmek", "Fiil (Görülen Geçmiş Zaman)", "became simplified", '"sadeleşti" (kök: sadeleşmek — simplified)'),
    "sadık": ("sadık", "Sıfat", "faithful / loyal", '"sadık" (sadık — faithful / loyal)'),
    "sahasıdır": ("saha", "İsim + Ek-fiil Yüklem", "is the domain / sphere of", '"sahasıdır" (kök: saha — is the domain of)'),
    "sahipti": ("sahip", "İsim / Sıfat + Ek-fiil (Görülen Geçmiş)", "possessed / had", '"sahipti" (kök: sahip — possessed / had)'),
    "sahiptir": ("sahip", "İsim / Sıfat + Ek-fiil Yüklem", "possesses / has", '"sahiptir" (kök: sahip — possesses / has)'),
    "salar": ("salmak", "Fiil (Geniş Zaman)", "releases / emits", '"salar" (kök: salmak — releases / emits)'),
    "sallar": ("sallamak", "Fiil (Geniş Zaman)", "shakes / rocks", '"sallar" (kök: sallamak — shakes / rocks)'),
    "sanatıdır": ("sanat", "İsim + Ek-fiil Yüklem", "is the art of", '"sanatıdır" (kök: sanat — is the art of)'),
    "savaşçılar": ("savaşçı", "İsim (Çoğul)", "warriors", '"savaşçılar" (kök: savaşçı — warriors)'),
    "savurur": ("savurmak", "Fiil (Geniş Zaman)", "hurls / scatters", '"savurur" (kök: savurmak — hurls / scatters)'),
    "sayılabilecek": ("sayılmak", "Fiilimsi / Sıfat-fiil", "that can be considered", '"sayılabilecek" (kök: sayılmak — that can be regarded)'),
    "sazdır": ("saz", "İsim + Ek-fiil Yüklem", "is a musical instrument / bağlama", '"sazdır" (kök: saz — is a folk lute)'),
    "sağlanır": ("sağlanmak", "Fiil (Geniş Zaman - Edilgen)", "is provided / ensured", '"sağlanır" (kök: sağlanmak — is ensured)'),
    "sağlar": ("sağlamak", "Fiil (Geniş Zaman)", "ensures / provides", '"sağlar" (kök: sağlamak — provides / ensures)'),
    "sağlıyordu": ("sağlamak", "Fiil (Şimdiki Zamanın Hikayesi)", "was providing / ensured", '"sağlıyordu" (kök: sağlamak — was providing)'),
    "sebzeler": ("sebze", "İsim (Çoğul)", "vegetables", '"sebzeler" (kök: sebze — vegetables)'),
    "sembolüdür": ("sembol", "İsim + Ek-fiil Yüklem", "is the symbol of", '"sembolüdür" (kök: sembol — is the symbol of)'),
    "sergiler": ("sergilemek", "Fiil (Geniş Zaman) / İsim (Çoğul)", "exhibits / displays", '"sergiler" (kök: sergilemek — displays / exhibits)'),
    "seriyor": ("sermek", "Fiil (Şimdiki Zaman)", "lays out / spreads", '"seriyor" (kök: sermek — lays out: gözler önüne seriyor)'),
    "sesidir": ("ses", "İsim + Ek-fiil Yüklem", "is the voice of", '"sesidir" (kök: ses — is the voice of)'),
    "seslendirir": ("seslendirmek", "Fiil (Geniş Zaman)", "articulates / gives voice to", '"seslendirir" (kök: seslendirmek — voices)'),
    "sevilir": ("sevilmek", "Fiil (Geniş Zaman - Edilgen)", "is loved / enjoyed", '"sevilir" (kök: sevilmek — is loved)'),
    "seyahatler": ("seyahat", "İsim (Çoğul)", "voyages / journeys", '"seyahatler" (kök: seyahat — journeys)'),
    "seyirciler": ("seyirci", "İsim (Çoğul)", "spectators / audience", '"seyirciler" (kök: seyirci — audience)'),
    "seyyahıdır": ("seyyah", "İsim + Ek-fiil Yüklem", "is the traveler of", '"seyyahıdır" (kök: seyyah — is the traveler of)'),
    "seçenekler": ("seçenek", "İsim (Çoğul)", "options / alternatives", '"seçenekler" (kök: seçenek — options)'),
    "silemedi": ("silmek", "Fiil (Yeterlik Olumsuz)", "could not erase", '"silemedi" (kök: silmek — could not erase)'),
    "simgeler": ("simgelemek", "Fiil (Geniş Zaman) / İsim (Çoğul)", "symbolizes / symbols", '"simgeler" (kök: simgelemek — symbolizes)'),
    "simgesidir": ("simge", "İsim + Ek-fiil Yüklem", "is the symbol of", '"simgesidir" (kök: simge — is the symbol of)'),
    "sindirilir": ("sindirilmek", "Fiil (Geniş Zaman - Edilgen)", "is digested", '"sindirilir" (kök: sindirilmek — is digested)'),
    "sohbeti": ("sohbet", "İsim (İyelik / Belirtme)", "conversation / talk", '"sohbeti" (kök: sohbet — conversation)'),
    "sohbetin": ("sohbet", "İsim (Tamlayan)", "of conversation", '"sohbetin" (kök: sohbet — of conversation)'),
    "sokabilir": ("sokmak", "Fiil (Yeterlik Geniş Zaman)", "can put / plunge into", '"sokabilir" (kök: sokmak — can put into: tehlikeye sokabilir)'),
    "stoacılar": ("Stoacı", "Özel İsim (Çoğul)", "Stoics", '"stoacılar" (kök: Stoacı — Stoics)'),
    "stratejidir": ("strateji", "İsim + Ek-fiil Yüklem", "is a strategy", '"stratejidir" (kök: strateji — is a strategy)'),
    "sunulur": ("sunulmak", "Fiil (Geniş Zaman - Edilgen)", "is offered / presented", '"sunulur" (kök: sunulmak — is presented)'),
    "sunuyor": ("sunmak", "Fiil (Şimdiki Zaman)", "offers / presents", '"sunuyor" (kök: sunmak — offers)'),
    "sunuyordu": ("sunmak", "Fiil (Şimdiki Zamanın Hikayesi)", "was offering / presented", '"sunuyordu" (kök: sunmak — was offering)'),
    "supabıdır": ("supap", "İsim + Ek-fiil Yüklem", "is the safety valve of", '"supabıdır" (kök: supap — is the safety valve of)'),
    "susar": ("susmak", "Fiil (Geniş Zaman)", "falls silent / hushes", '"susar" (kök: susmak — falls silent)'),
    "söner": ("sönmek", "Fiil (Geniş Zaman)", "fades / extinguishes", '"söner" (kök: sönmek — fades out)'),
    "sürdürürlerdi": ("sürdürmek", "Fiil (Geniş Zamanın Hikayesi 3. Çoğul)", "would maintain / carried on", '"sürdürürlerdi" (kök: sürdürmek — maintained)'),
    "sürçtü": ("sürçmek", "Fiil (Görülen Geçmiş Zaman)", "slipped (tongue)", '"sürçtü" (kök: sürçmek — slipped: dili sürçtü)'),
    "sütün": ("süt", "İsim (Tamlayan)", "of milk", '"sütün" (kök: süt — of milk)'),
    "sıçrar": ("sıçramak", "Fiil (Geniş Zaman)", "splashes / leaps", '"sıçrar" (kök: sıçramak — leaps / splashes)'),
    "sığınaktır": ("sığınak", "İsim + Ek-fiil Yüklem", "is a sanctuary / shelter", '"sığınaktır" (kök: sığınak — is a shelter)'),
    "sığınağıdır": ("sığınak", "İsim + Ek-fiil Yüklem", "is the sanctuary / haven of", '"sığınağıdır" (kök: sığınak — is the haven of)'),
    "şaheserleridir": ("şaheser", "İsim + Çoğul + Ek-fiil", "are the masterpieces of", '"şaheserleridir" (kök: şaheser — are masterpieces of)'),
    "şahmarandır": ("Şahmaran", "Özel İsim + Ek-fiil", "is Shahmaran", '"şahmarandır" (kök: Şahmaran — is Shahmaran)'),
    "şakalar": ("şaka", "İsim (Çoğul)", "jokes / witticisms", '"şakalar" (kök: şaka — jokes)'),
    "şakir": ("Şakir", "Özel İsim", "Şakir (Cevat Şakir / Fisherman of Halicarnassus)", '"şakir" (Şakir — prominent writer)'),
    "şantiyedir": ("şantiye", "İsim + Ek-fiil Yüklem", "is a construction site", '"şantiyedir" (kök: şantiye — is a construction site)'),
    "şaraphaneler": ("şaraphane", "İsim (Çoğul)", "wineries", '"şaraphaneler" (kök: şaraphane — wineries)'),
    "şartı": ("şart", "İsim (İyelik / Belirtme)", "condition / prerequisite of", '"şartı" (kök: şart — prerequisite)'),
    "şeker": ("şeker", "İsim", "sugar", '"şeker" (şeker — sugar)'),
    "şekiller": ("şekil", "İsim (Çoğul)", "shapes / forms", '"şekiller" (kök: şekil — forms / shapes)'),
    "şöhretin": ("şöhret", "İsim (Tamlayan)", "of fame / renown", '"şöhretin" (kök: şöhret — of fame)'),
    # T
    "tabaklar": ("tabak", "İsim (Çoğul)", "plates / dishes", '"tabaklar" (kök: tabak — plates)'),
    "tabiatın": ("tabiat", "İsim (Tamlayan)", "of nature", '"tabiatın" (kök: tabiat — of nature)'),
    "tahribatlar": ("tahribat", "İsim (Çoğul)", "destructions / damages", '"tahribatlar" (kök: tahribat — destructions)'),
    "takıntı": ("takıntı", "İsim", "obsession", '"takıntı" (takıntı — obsession)'),
    "tamir": ("tamir", "İsim", "repair / restoration", '"tamir" (tamir — repair)'),
    "tanıklarıdır": ("tanık", "İsim + Çoğul + Ek-fiil", "are the witnesses of", '"tanıklarıdır" (kök: tanık — are the witnesses of)'),
    "tanınmış": ("tanınmak", "Fiilimsi / Sıfat (Duyulan Geçmiş - Edilgen)", "renowned / well-known", '"tanınmış" (kök: tanınmak — renowned)'),
    "tanır": ("tanımak", "Fiil (Geniş Zaman)", "recognizes / knows", '"tanır" (kök: tanımak — recognizes / knows)'),
    "tapınağıdır": ("tapınak", "İsim + Ek-fiil Yüklem", "is the temple of", '"tapınağıdır" (kök: tapınak — is the temple of)'),
    "tarihçiler": ("tarihçi", "İsim (Çoğul)", "historians", '"tarihçiler" (kök: tarihçi — historians)'),
    "tarzıdır": ("tarz", "İsim + Ek-fiil Yüklem", "is the style of", '"tarzıdır" (kök: tarz — is the style of)'),
    "tasarlanmıştı": ("tasarlanmak", "Fiil (Duyulan Geçmişin Hikayesi - Edilgen)", "had been designed", '"tasarlanmıştı" (kök: tasarlanmak — had been designed)'),
    "tasvirler": ("tasvir", "İsim (Çoğul)", "depictions / descriptions", '"tasvirler" (kök: tasvir — depictions)'),
    "tattı": ("tatmak", "Fiil (Görülen Geçmiş Zaman)", "tasted / experienced", '"tattı" (kök: tatmak — tasted)'),
    "taşır": ("taşımak", "Fiil (Geniş Zaman)", "carries / bears", '"taşır" (kök: taşımak — carries)'),
    "taşırlar": ("taşımak", "Fiil (Geniş Zaman 3. Çoğul)", "they carry / transport", '"taşırlar" (kök: taşımak — they carry)'),
    "taşırlardı": ("taşımak", "Fiil (Geniş Zamanın Hikayesi 3. Çoğul)", "used to carry / transported", '"taşırlardı" (kök: taşımak — transported)'),
    "teknolojiler": ("teknoloji", "İsim (Çoğul)", "technologies", '"teknolojiler" (kök: teknoloji — technologies)'),
    "temellendirir": ("temellendirmek", "Fiil (Geniş Zaman)", "grounds / substantiates", '"temellendirir" (kök: temellendirmek — grounds)'),
    "temizlenir": ("temizlenmek", "Fiil (Geniş Zaman - Edilgen)", "is cleaned / purified", '"temizlenir" (kök: temizlenmek — is purified)'),
    "teoriler": ("teori", "İsim (Çoğul)", "theories", '"teoriler" (kök: teori — theories)'),
    "tescillenmiştir": ("tescillenmek", "Fiil (Duyulan Geçmiş + Bildirme - Edilgen)", "has been registered / certified", '"tescillenmiştir" (kök: tescillenmek — has been registered)'),
    "tespiti": ("tespit", "İsim (İyelik / Belirtme)", "identification / determination of", '"tespiti" (kök: tespit — identification)'),
    "tetikleyicisidir": ("tetikleyici", "İsim + Ek-fiil Yüklem", "is the trigger of", '"tetikleyicisidir" (kök: tetikleyici — is the trigger of)'),
    "tipler": ("tip", "İsim (Çoğul)", "types / characters", '"tipler" (kök: tip — characters / archetypes)'),
    "tiryakiler": ("tiryaki", "İsim (Çoğul)", "aficionados / devotees", '"tiryakiler" (kök: tiryaki — devotees)'),
    "topluluklar": ("topluluk", "İsim (Çoğul)", "communities", '"topluluklar" (kök: topluluk — communities)'),
    "topluluktur": ("topluluk", "İsim + Ek-fiil Yüklem", "is a community", '"topluluktur" (kök: topluluk — is a community)'),
    "truvalılar": ("Truvalı", "Özel İsim (Çoğul)", "Trojans", '"truvalılar" (kök: Truvalı — Trojans)'),
    "tutmuştur": ("tutmak", "Fiil (Duyulan Geçmiş + Bildirme)", "has held / caught", '"tutmuştur" (kök: tutmak — has held)'),
    "törendir": ("tören", "İsim + Ek-fiil Yüklem", "is a ceremony / ritual", '"törendir" (kök: tören — is a ceremony)'),
    "törenler": ("tören", "İsim (Çoğul)", "ceremonies / rituals", '"törenler" (kök: tören — rituals)'),
    "tüccar": ("tüccar", "İsim / Sıfat", "merchant / trader", '"tüccar" (tüccar — merchant)'),
    "tüketebilir": ("tüketmek", "Fiil (Yeterlik Geniş Zaman)", "can consume", '"tüketebilir" (kök: tüketmek — can consume)'),
    "türkler": ("Türk", "Özel İsim (Çoğul)", "Turks", '"türkler" (kök: Türk — Turks)'),
    "türküler": ("türkü", "İsim (Çoğul)", "folk songs", '"türküler" (kök: türkü — folk songs)'),
    "tırmanır": ("tırmanmak", "Fiil (Geniş Zaman)", "climbs / scales", '"tırmanır" (kök: tırmanmak — climbs)'),
    "tırtıllar": ("tırtıl", "İsim (Çoğul)", "caterpillars", '"tırtıllar" (kök: tırtıl — caterpillars)'),
    # U / Ü
    "unutulabilir": ("unutulmak", "Fiil (Yeterlik Geniş Zaman - Edilgen)", "can be forgotten", '"unutulabilir" (kök: unutulmak — can be forgotten)'),
    "ustalar": ("usta", "İsim (Çoğul)", "masters / artisans", '"ustalar" (kök: usta — master artisans)'),
    "uyarlamıştır": ("uyarlamak", "Fiil (Duyulan Geçmiş + Bildirme)", "has adapted", '"uyarlamıştır" (kök: uyarlamak — has adapted)'),
    "uyarılar": ("uyarı", "İsim (Çoğul)", "warnings", '"uyarılar" (kök: uyarı — warnings)'),
    "uygundur": ("uygun", "Sıfat + Ek-fiil Yüklem", "is suitable / appropriate", '"uygundur" (kök: uygun — is suitable)'),
    "ünlüdür": ("ünlü", "Sıfat + Ek-fiil Yüklem", "is famous / renowned", '"ünlüdür" (kök: ünlü — is famous)'),
    "üretilir": ("üretilmek", "Fiil (Geniş Zaman - Edilgen)", "is produced / generated", '"üretilir" (kök: üretilmek — is produced)'),
    "ürünüdür": ("ürün", "İsim + Ek-fiil Yüklem", "is the product / fruit of", '"ürünüdür" (kök: ürün — is the product of)'),
    # V
    "vahalar": ("vaha", "İsim (Çoğul)", "oases", '"vahalar" (kök: vaha — oases)'),
    "vaktim": ("vakit", "İsim + İyelik", "my time", '"vaktim" (kök: vakit — my time: vaktim var)'),
    "vapur": ("vapur", "İsim", "ferry / steamboat", '"vapur" (vapur — ferry)'),
    "vapurlar": ("vapur", "İsim (Çoğul)", "ferries", '"vapurlar" (kök: vapur — ferries)'),
    "vardır": ("var", "Sıfat + Ek-fiil Yüklem", "there is / exists", '"vardır" (kök: var — there is / exists)'),
    "varlıktır": ("varlık", "İsim + Ek-fiil Yüklem", "is an entity / existence", '"varlıktır" (kök: varlık — is an entity)'),
    "verebilir": ("vermek", "Fiil (Yeterlik Geniş Zaman)", "can give / provide", '"verebilir" (kök: vermek — can give)'),
    "vezir": ("vezir", "İsim", "vizier / prime minister", '"vezir" (vezir — vizier)'),
    "vurgulanır": ("vurgulanmak", "Fiil (Geniş Zaman - Edilgen)", "is emphasized / stressed", '"vurgulanır" (kök: vurgulanmak — is emphasized)'),
    # Y
    "yakaladı": ("yakalamak", "Fiil (Görülen Geçmiş Zaman)", "captured / attained", '"yakaladı" (kök: yakalamak — captured)'),
    "yakmayacak": ("yakmak", "Fiil (Gelecek Zaman - Olumsuz)", "will not burn", '"yakmayacak" (kök: yakmak — will not burn)'),
    "yalnızlaşmamalarıdır": ("yalnızlaşmama", "İsim-fiil + Çoğul + Ek-fiil", "is their not becoming isolated", '"yalnızlaşmamalarıdır" (kök: yalnızlaşmak — is their not becoming isolated)'),
    "yalındı": ("yalın", "Sıfat + Ek-fiil (Görülen Geçmiş)", "was plain / simple", '"yalındı" (kök: yalın — was plain / simple)'),
    "yaparlardı": ("yapmak", "Fiil (Geniş Zamanın Hikayesi 3. Çoğul)", "would make / used to do", '"yaparlardı" (kök: yapmak — would make)'),
    "yararlanmıştır": ("yararlanmak", "Fiil (Duyulan Geçmiş + Bildirme)", "utilized / benefited from", '"yararlanmıştır" (kök: yararlanmak — utilized)'),
    "yardır": ("yar", "İsim + Ek-fiil Yüklem", "is beloved / friend", '"yardır" (kök: yar — is beloved: kara toprak yardır)'),
    "yargılardır": ("yargı", "İsim + Çoğul + Ek-fiil", "are judgments", '"yargılardır" (kök: yargı — are judgments)'),
    "yarışacak": ("yarışmak", "Fiil (Gelecek Zaman / Sıfat-fiil)", "will compete / competing", '"yarışacak" (kök: yarışmak — will compete)'),
    "yasaklar": ("yasak", "İsim (Çoğul) / Fiil (Geniş Zaman)", "bans / prohibits", '"yasaklar" (kök: yasak — bans / prohibitions)'),
    "yağmur": ("yağmur", "İsim", "rain", '"yağmur" (yağmur — rain)'),
    "yaşarlardı": ("yaşamak", "Fiil (Geniş Zamanın Hikayesi 3. Çoğul)", "used to live / lived", '"yaşarlardı" (kök: yaşamak — lived)'),
    "yaşayabiliyordu": ("yaşamak", "Fiil (Yeterlik + Şimdiki Zamanın Hikayesi)", "could live / was able to live", '"yaşayabiliyordu" (kök: yaşamak — could live)'),
    "yaşlılar": ("yaşlı", "İsim (Çoğul)", "the elderly / elders", '"yaşlılar" (kök: yaşlı — the elderly)'),
    "yedirilir": ("yedirilmek", "Fiil (Geniş Zaman - Edilgen)", "is fed to", '"yedirilir" (kök: yedirilmek — is fed)'),
    "yenir": ("yenmek", "Fiil (Geniş Zaman - Edilgen)", "is eaten / consumed", '"yenir" (kök: yemek — is eaten)'),
    "yeteneğiydi": ("yetenek", "İsim + İyelik + Ek-fiil", "was the talent / ability of", '"yeteneğiydi" (kök: yetenek — was the talent of)'),
    "yetiştirilir": ("yetiştirilmek", "Fiil (Geniş Zaman - Edilgen)", "is cultivated / grown", '"yetiştirilir" (kök: yetiştirilmek — is grown)'),
    "yetiştirirler": ("yetiştirmek", "Fiil (Geniş Zaman 3. Çoğul)", "they grow / cultivate", '"yetiştirirler" (kök: yetiştirmek — they grow)'),
    "yiyecek": ("yiyecek", "İsim", "food / provisions", '"yiyecek" (yiyecek — food)'),
    "yoludur": ("yol", "İsim + Ek-fiil Yüklem", "is the way / path of", '"yoludur" (kök: yol — is the way of)'),
    "yorar": ("yormak", "Fiil (Geniş Zaman)", "tires / strains", '"yorar" (kök: yormak — tires)'),
    "yoğrulmuştur": ("yoğrulmak", "Fiil (Duyulan Geçmiş + Bildirme - Edilgen)", "has been kneaded / molded", '"yoğrulmuştur" (kök: yoğrulmak — has been kneaded)'),
    "yoğunlaştırılmış": ("yoğunlaştırılmak", "Fiilimsi / Fiil (Duyulan Geçmiş - Edilgen)", "thickened / concentrated", '"yoğunlaştırılmış" (kök: yoğunlaştırılmak — thickened)'),
    "yudum": ("yudum", "İsim", "sip / mouthful", '"yudum" (yudum — sip)'),
    "yunanlılar": ("Yunanlı", "Özel İsim (Çoğul)", "Greeks", '"yunanlılar" (kök: Yunanlı — Greeks)'),
    "yuvarlanabilecek": ("yuvarlanmak", "Fiilimsi / Sıfat-fiil", "that can be rolled", '"yuvarlanabilecek" (kök: yuvarlanmak — that can be rolled)'),
    "yöneltilmiş": ("yöneltilmek", "Fiilimsi / Fiil (Duyulan Geçmiş - Edilgen)", "directed / aimed", '"yöneltilmiş" (kök: yöneltilmek — directed / aimed)'),
    "yürür": ("yürümek", "Fiil (Geniş Zaman)", "walks / proceeds", '"yürür" (kök: yürümek — walks)'),
    "yürüyormuş": ("yürümek", "Fiil (Şimdiki Zamanın Rivayeti)", "was reportedly walking", '"yürüyormuş" (kök: yürümek — was walking)'),
    "yürüyüşler": ("yürüyüş", "İsim (Çoğul)", "walks / strolls", '"yürüyüşler" (kök: yürüyüş — walks)'),
    "yüzyıllardır": ("yüzyıl", "İsim + Çoğul + Ek-fiil (Zarf)", "for centuries", '"yüzyıllardır" (kök: yüzyıl — for centuries)'),
    "yıllardır": ("yıl", "İsim + Çoğul + Ek-fiil (Zarf)", "for years", '"yıllardır" (kök: yıl — for years)'),
    # Z
    "zehir": ("zehir", "İsim", "poison / venom", '"zehir" (zehir — poison)'),
    "zenginliğidir": ("zenginlik", "İsim + Ek-fiil Yüklem", "is the richness / wealth of", '"zenginliğidir" (kök: zenginlik — is the wealth of)'),
    "zeytinyağlılar": ("zeytinyağlı", "İsim (Çoğul)", "olive oil dishes", '"zeytinyağlılar" (kök: zeytinyağlı — olive oil dishes)'),
    "zorlardı": ("zorlamak", "Fiil (Geniş Zamanın Hikayesi)", "would force / compelled", '"zorlardı" (kök: zorlamak — would force)'),
    "zorundaydı": ("zorunda", "İsim + Bulunma + Ek-fiil", "had to / was obliged to", '"zorundaydı" (kök: zorun — had to)'),
    "zorunluluğudur": ("zorunluluk", "İsim + Ek-fiil Yüklem", "is a necessity of", '"zorunluluğudur" (kök: zorunluluk — is a necessity of)')
}


def main():
    with open(SCRATCH_FILE, "r", encoding="utf-8") as f:
        target_items = json.load(f)

    missing = []
    for k in target_items:
        if k not in CURATED_TR_MAP:
            missing.append(k)

    if missing:
        print(f"Warning: {len(missing)} keys missing from CURATED_TR_MAP: {missing[:10]}")
    else:
        print(f"✓ All {len(target_items)} keys in {SCRATCH_FILE.name} are present in CURATED_TR_MAP!")

    # Write output python module
    content = '# -*- coding: utf-8 -*-\n"""\nComprehensive verified Turkish fallthrough translations,\nlemmas, and parts of speech.\n"""\n\nTR_ADDITIONAL_FALLTHROUGH_MAP = {\n'
    for k, v in sorted(CURATED_TR_MAP.items()):
        lemma, pos, en_trans, note = v
        content += f'    "{k}": ({json.dumps(lemma, ensure_ascii=False)}, {json.dumps(pos, ensure_ascii=False)}, {json.dumps(en_trans, ensure_ascii=False)}, {json.dumps(note, ensure_ascii=False)}),\n'
    content += "}\n"

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"✓ Written {len(CURATED_TR_MAP)} verified entries to {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
