#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Builds verified German fallthrough translations, lemmas, and POS tags
for all 412 unglossed/echoed German tokens in articles.json.
Output: scripts/german_fallthrough_dict.py
"""

import json
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
SCRATCH_FILE = BASE_DIR / "scratch_de_verbs_to_patch.json"
OUTPUT_FILE = BASE_DIR / "scripts" / "german_fallthrough_dict.py"

# Curated, verified mapping for all 412 German fallthrough items
# Format: lemma, pos, tr_trans, en_trans, note
CURATED_DE_MAP = {
    "akzeptiert": ("akzeptieren", "Verb (Partizip II)", "kabul edilen / benimsenen", "accepted", '"akzeptiert" (kök: akzeptieren — kabul edilen)'),
    "anatolien": ("Anatolien", "Eigenname / Substantiv", "Anadolu", "Anatolia", '"Anatolien" (Anadolu — Anatolia)'),
    "anatolischen": ("anatolisch", "Adjektiv (Dekliniert)", "Anadolu'ya ait / Anadolu", "Anatolian", '"anatolischen" (kök: anatolisch — Anadolu)'),
    "anatomischen": ("anatomisch", "Adjektiv (Dekliniert)", "anatomik", "anatomical", '"anatomischen" (kök: anatomisch — anatomik)'),
    "andenken": ("Andenken", "Substantiv (Neut)", "anı / hatıra", "memory / memento", '"Andenken" (hatıra — memory)'),
    "anderen": ("anderer", "Pronomen / Adjektiv", "diğer / başka", "other", '"anderen" (diğer — other)'),
    "andicken": ("andicken", "Verb (Infinitiv)", "koyulaşmak / kıvam almak", "thicken", '"andicken" (kök: andicken — koyulaşmak)'),
    "angestellte": ("Angestellte", "Substantiv (Mask/Fem)", "çalışanlar / memurlar", "employees", '"Angestellte" (çalışanlar — employees)'),
    "angestrengte": ("angestrengt", "Adjektiv (Dekliniert)", "yoğun / gergin", "strained / strenuous", '"angestrengte" (kök: anstrengen — yoğun / yorucu)'),
    "angreifen": ("angreifen", "Verb (Infinitiv)", "saldırmak", "attack", '"angreifen" (kök: angreifen — saldırmak)'),
    "anlagen": ("Anlage", "Substantiv (Fem, Plural)", "tesisler / yapılar", "facilities / sites", '"Anlagen" (yapılar — sites)'),
    "anleitete": ("anleiten", "Verb (Präteritum 3sg)", "yol gösterdi / rehberlik etti", "guided / instructed", '"anleitete" (kök: anleiten — rehberlik etti)'),
    "annahmen": ("Annahme", "Substantiv (Fem, Plural)", "kabuller / varsayımlar", "assumptions / acceptances", '"Annahmen" (kabuller — acceptances)'),
    "ansehen": ("ansehen", "Verb (Infinitiv)", "bakmak / incelemek", "look at / view", '"ansehen" (kök: ansehen — bakmak)'),
    "anspielungen": ("Anspielung", "Substantiv (Fem, Plural)", "imalar / kinayeler", "allusions", '"Anspielungen" (imalar — allusions)'),
    "anspruchsvollen": ("anspruchsvoll", "Adjektiv (Dekliniert)", "iddialı / zorlu", "demanding / sophisticated", '"anspruchsvollen" (iddialı — demanding)'),
    "anstatt": ("anstatt", "Präposition / Konjunktion", "yerine", "instead of", '"anstatt" (yerine — instead of)'),
    "antiken": ("antik", "Adjektiv (Dekliniert)", "antik / eski çağlara ait", "ancient", '"antiken" (antik — ancient)'),
    "antwort": ("Antwort", "Substantiv (Fem)", "cevap / yanıt", "answer / response", '"Antwort" (yanıt — answer)'),
    "antwortet": ("antworten", "Verb (Präsens 3sg)", "cevap verir / yanıtlar", "answers / responds", '"antwortet" (kök: antworten — cevap verir)'),
    "anzubieten": ("anbieten", "Verb (zu-Infinitiv)", "sunmak / ikram etmek", "to offer", '"anzubieten" (kök: anbieten — ikram etmek)'),
    "anzupassen": ("anpassen", "Verb (zu-Infinitiv)", "uyum sağlamak / adapte olmak", "to adapt", '"anzupassen" (kök: anpassen — uyum sağlamak)'),
    "aufgesetzte": ("aufgesetzt", "Adjektiv / Partizip II", "üzerine oturtulan / yapay", "placed upon / artificial", '"aufgesetzte" (kök: aufsetzen — üzerine oturtulan)'),
    "aufleben": ("aufleben", "Verb (Infinitiv)", "canlanmak / yeniden doğmak", "revive / come alive", '"aufleben" (kök: aufleben — canlanmak)'),
    "aufmerksamkeit": ("Aufmerksamkeit", "Substantiv (Fem)", "dikkat / ilgi", "attention", '"Aufmerksamkeit" (dikkat — attention)'),
    "aufrecht": ("aufrecht", "Adverb / Adjektiv", "dik / ayakta", "upright / erect", '"aufrecht" (dik — upright: aufrecht erhalten)'),
    "aufrichtigen": ("aufrichtig", "Adjektiv (Dekliniert)", "samimi / içten", "sincere / genuine", '"aufrichtigen" (samimi — sincere)'),
    "aufzeichnungen": ("Aufzeichnung", "Substantiv (Fem, Plural)", "notlar / kayıtlar", "notes / records", '"Aufzeichnungen" (notlar — records)'),
    "aufzubauen": ("aufbauen", "Verb (zu-Infinitiv)", "inşa etmeye / kurmaya", "to build up / establish", '"aufzubauen" (kök: aufbauen — inşa etmeye)'),
    "aufzubewahren": ("aufbewahren", "Verb (zu-Infinitiv)", "saklamaya / muhafaza etmeye", "to store / preserve", '"aufzubewahren" (kök: aufbewahren — muhafaza etmeye)'),
    "aufzustehen": ("aufstehen", "Verb (zu-Infinitiv)", "ayağa kalkmaya / uyanmaya", "to get up / rise", '"aufzustehen" (kök: aufstehen — ayağa kalkmaya)'),
    "ausgangspunkt": ("Ausgangspunkt", "Substantiv (Mask)", "çıkış noktası / başlangıç", "starting point", '"Ausgangspunkt" (başlangıç noktası — starting point)'),
    "ausharren": ("ausharren", "Verb (Infinitiv)", "direnmek / sabırla beklemek", "persevere / hold out", '"ausharren" (kök: ausharren — direnmek)'),
    "ausrichteten": ("ausrichten", "Verb (Präteritum 3pl)", "düzenlediler / hizaladılar", "organized / oriented", '"ausrichteten" (kök: ausrichten — düzenlediler)'),
    "ausschalten": ("ausschalten", "Verb (Infinitiv)", "kapatmak / devre dışı bırakmak", "switch off / disable", '"ausschalten" (kök: ausschalten — kapatmak)'),
    "avancierte": ("avancieren", "Verb (Präteritum 3sg)", "yükseldi / haline geldi", "became / advanced to", '"avancierte" (kök: avancieren — haline geldi)'),
    "beamte": ("Beamter", "Substantiv (Mask, Plural)", "memurlar / bürokratlar", "officials / civil servants", '"Beamte" (memurlar — officials)'),
    "bedeutendsten": ("bedeutend", "Adjektiv (Superlativ)", "en önemli / en önde gelen", "most significant / prominent", '"bedeutendsten" (en önemli — most significant)'),
    "bedeutet": ("bedeuten", "Verb (Präsens 3sg)", "anlamına gelir / ifade eder", "means / signifies", '"bedeutet" (kök: bedeuten — anlamına gelir)'),
    "bedroht": ("bedrohen", "Verb (Präsens 3sg / Partizip II)", "tehdit eder / tehdit edilen", "threatens / threatened", '"bedroht" (kök: bedrohen — tehdit eder)'),
    "beendete": ("beenden", "Verb (Präteritum 3sg)", "bitirdi / sona erdirdi", "ended / concluded", '"beendete" (kök: beenden — bitirdi)'),
    "befallen": ("befallen", "Verb (Partizip II / Infinitiv)", "istila edilen / musallat olan", "infested / struck", '"befallen" (kök: befallen — musallat olan)'),
    "befinden": ("befinden", "Verb (Infinitiv / Präsens 3pl)", "bulunmak / yer almak", "be located / situated", '"befinden" (kök: befinden — yer almak)'),
    "befreien": ("befreien", "Verb (Infinitiv)", "özgürleştirmek / kurtarmak", "liberate / free", '"befreien" (kök: befreien — kurtarmak)'),
    "befreit": ("befreien", "Verb (Präsens 3sg / Partizip II)", "özgürleştirir / kurtarılmış", "liberates / freed", '"befreit" (kök: befreien — özgürleştirir)'),
    "befreite": ("befreien", "Verb (Präteritum 3sg)", "kurtardı / özgürleştirdi", "liberated / freed", '"befreite" (kök: befreien — kurtardı)'),
    "begannen": ("beginnen", "Verb (Präteritum 3pl)", "başladılar", "began / started", '"begannen" (kök: beginnen — başladılar)'),
    "begegnen": ("begegnen", "Verb (Infinitiv / Präsens 3pl)", "karşılaşmak", "encounter / meet", '"begegnen" (kök: begegnen — karşılaşmak)'),
    "begegnet": ("begegnen", "Verb (Präsens 3sg)", "karşılaşır", "encounters / meets", '"begegnet" (kök: begegnen — karşılaşır)'),
    "begeistert": ("begeistern", "Verb (Präsens 3sg / Adjektiv)", "heyecanlandırır / hayran", "enthusiastic / thrills", '"begeistert" (kök: begeistern — hayran)'),
    "beginnen": ("beginnen", "Verb (Infinitiv / Präsens 3pl)", "başlamak / başlarlar", "to begin / start", '"beginnen" (kök: beginnen — başlamak)'),
    "beginnt": ("beginnen", "Verb (Präsens 3sg)", "başlar", "begins / starts", '"beginnt" (kök: beginnen — başlar)'),
    "begleiten": ("begleiten", "Verb (Infinitiv / Präsens 3pl)", "eşlik etmek", "accompany", '"begleiten" (kök: begleiten — eşlik etmek)'),
    "begleitet": ("begleiten", "Verb (Präsens 3sg)", "eşlik eder", "accompanies", '"begleitet" (kök: begleiten — eşlik eder)'),
    "begrenzte": ("begrenzen", "Verb (Präteritum 3sg / Adjektiv)", "sınırlandırdı / sınırlı", "limited / restricted", '"begrenzte" (kök: begrenzen — sınırlı)'),
    "behaglichen": ("behaglich", "Adjektiv (Dekliniert)", "rahat / huzurlu", "cozy / comfortable", '"behaglichen" (huzurlu — cozy)'),
    "behalten": ("behalten", "Verb (Infinitiv / Partizip II)", "saklamak / korumak", "keep / retain", '"behalten" (kök: behalten — korumak)'),
    "beherbergten": ("beherbergen", "Verb (Präteritum 3pl)", "barındırdılar / ev sahipliği yaptılar", "housed / harbored", '"beherbergten" (kök: beherbergen — barındırdılar)'),
    "beherrschen": ("beherrschen", "Verb (Infinitiv)", "hakim olmak / yönetmek", "master / rule", '"beherrschen" (kök: beherrschen — hakim olmak)'),
    "beiden": ("beide", "Pronomen / Numerale", "her ikisi", "both", '"beiden" (her ikisi — both)'),
    "bekannt": ("bekannt", "Adjektiv / Partizip II", "tanınan / meşhur / bilinen", "famous / known", '"bekannt" (tanınan — famous)'),
    "bekannte": ("bekannt", "Adjektiv (Dekliniert)", "tanınmış / bilinen", "well-known / famous", '"bekannte" (tanınmış — well-known)'),
    "bekanntesten": ("bekannt", "Adjektiv (Superlativ)", "en tanınmış / en meşhur", "most famous", '"bekanntesten" (en meşhur — most famous)'),
    "belagerte": ("belagern", "Verb (Präteritum 3sg)", "kuşattı", "besieged", '"belagerte" (kök: belagern — kuşattı)'),
    "belagerungen": ("Belagerung", "Substantiv (Fem, Plural)", "kuşatmalar", "sieges", '"Belagerungen" (kuşatmalar — sieges)'),
    "belauscht": ("belauschen", "Verb (Präsens 3sg / Partizip II)", "kulak misafiri olur / gizlice dinler", "eavesdrops / overhears", '"belauscht" (kök: belauschen — gizlice dinler)'),
    "beleben": ("beleben", "Verb (Infinitiv)", "canlandırmak", "enliven / revive", '"beleben" (kök: beleben — canlandırmak)'),
    "belebten": ("beleben", "Verb (Präteritum 3pl / Adjektiv)", "canlandırdılar / kalabalık", "enlivened / busy", '"belebten" (kök: beleben — kalabalık)'),
    "belebtesten": ("belebt", "Adjektiv (Superlativ)", "en kalabalık / en canlı", "busiest / most vibrant", '"belebtesten" (en canlı — busiest)'),
    "belegen": ("belegen", "Verb (Infinitiv)", "kanıtlamak / belgelemek", "prove / document", '"belegen" (kök: belegen — kanıtlamak)'),
    "belegt": ("belegen", "Verb (Präsens 3sg / Partizip II)", "kanıtlar / belgelenmiş", "proves / documented", '"belegt" (kök: belegen — kanıtlar)'),
    "belegten": ("belegen", "Verb (Präteritum 3pl)", "kanıtladılar / belgelediler", "documented / proved", '"belegten" (kök: belegen — kanıtladılar)'),
    "beliebt": ("beliebt", "Adjektiv", "sevilen / popüler", "popular / beloved", '"beliebt" (popüler — popular)'),
    "bemalt": ("bemalen", "Verb (Partizip II / Präsens 3sg)", "boyanmış / boyar", "painted / adorns", '"bemalt" (kök: bemalen — boyanmış)'),
    "bemalten": ("bemalen", "Verb (Präteritum 3pl)", "boyadılar", "painted", '"bemalten" (kök: bemalen — boyadılar)'),
    "bemerkenswerte": ("bemerkenswert", "Adjektiv (Dekliniert)", "dikkate değer / kayda değer", "remarkable / noteworthy", '"bemerkenswerte" (kayda değer — remarkable)'),
    "bemerkenswerteste": ("bemerkenswert", "Adjektiv (Superlativ)", "en dikkate değer", "most remarkable", '"bemerkenswerteste" (en kayda değer — most remarkable)'),
    "bemisst": ("bemessen", "Verb (Präsens 3sg)", "ölçülür / değerlendirilir", "is measured / assessed", '"bemisst" (kök: bemessen — ölçülür)'),
    "benachrichtigungen": ("Benachrichtigung", "Substantiv (Fem, Plural)", "bildirimler", "notifications", '"Benachrichtigungen" (bildirimler — notifications)'),
    "berichten": ("berichten", "Verb (Infinitiv / Präsens 3pl)", "rapor etmek / anlatmak", "report / narrate", '"berichten" (kök: berichten — anlatmak)'),
    "beruht": ("beruhen", "Verb (Präsens 3sg)", "dayanır / temellenir", "is based on / rests on", '"beruht" (kök: beruhen — dayanır)'),
    "besagt": ("besagen", "Verb (Präsens 3sg)", "ifade eder / der ki", "states / says", '"besagt" (kök: besagen — ifade eder)'),
    "bescheidenheit": ("Bescheidenheit", "Substantiv (Fem)", "alçakgönüllülük / tevazu", "humility / modesty", '"Bescheidenheit" (tevazu — humility)'),
    "beschleunigen": ("beschleunigen", "Verb (Infinitiv)", "hızlandırmak", "accelerate / speed up", '"beschleunigen" (kök: beschleunigen — hızlandırmak)'),
    "beschleunigt": ("beschleunigen", "Verb (Präsens 3sg)", "hızlandırır", "accelerates", '"beschleunigt" (kök: beschleunigen — hızlandırır)'),
    "beschreibt": ("beschreiben", "Verb (Präsens 3sg)", "tasvir eder / anlatır", "describes", '"beschreibt" (kök: beschreiben — tasvir eder)'),
    "besiegelt": ("besiegeln", "Verb (Partizip II / Präsens 3sg)", "mühürlenmiş / mühürler", "sealed / seals", '"besiegelt" (kök: besiegeln — mühürler)'),
    "besingt": ("besingen", "Verb (Präsens 3sg)", "şarkılarla över / dile getirir", "sings of / praises in song", '"besingt" (kök: besingen — dile getirir)'),
    "besitzen": ("besitzen", "Verb (Infinitiv / Präsens 3pl)", "sahip olmak / sahiptirler", "possess / own", '"besitzen" (kök: besitzen — sahip olmak)'),
    "besonderen": ("besonderer", "Adjektiv (Dekliniert)", "özel / kendine has", "special / particular", '"besonderen" (özel — special)'),
    "bestehen": ("bestehen", "Verb (Infinitiv)", "var olmak / oluşmak", "exist / consist", '"bestehen" (kök: bestehen — var olmak)'),
    "besteht": ("bestehen", "Verb (Präsens 3sg)", "oluşur / meydana gelir / vardır", "consists / exists", '"besteht" (kök: bestehen — oluşur)'),
    "bestellen": ("bestellen", "Verb (Infinitiv)", "sipariş etmek", "order", '"bestellen" (kök: bestellen — sipariş etmek)'),
    "besteuerten": ("besteuern", "Verb (Präteritum 3pl)", "vergilendirdiler", "taxed", '"besteuerten" (kök: besteuern — vergilendirdiler)'),
    "besticht": ("bestechen", "Verb (Präsens 3sg)", "büyüler / öne çıkar", "captivates / stands out", '"besticht" (kök: bestechen — büyüler)'),
    "bestimmte": ("bestimmt", "Adjektiv / Verb (Präteritum 3sg)", "belirli / tayin etti", "certain / determined", '"bestimmte" (belirli — specific)'),
    "besucht": ("besuchen", "Verb (Präsens 3sg / Partizip II)", "ziyaret eder / ziyaret edilen", "visits / visited", '"besucht" (kök: besuchen — ziyaret eder)'),
    "besuchten": ("besuchen", "Verb (Präteritum 3pl)", "gezdiler / ziyaret ettiler", "visited / toured", '"besuchten" (kök: besuchen — gezdiler)'),
    "betont": ("betonen", "Verb (Präsens 3sg)", "vurgular", "emphasizes", '"betont" (kök: betonen — vurgular)'),
    "betrachten": ("betrachten", "Verb (Infinitiv)", "gözlemlemek / değerlendirmek", "regard / observe", '"betrachten" (kök: betrachten — değerlendirmek)'),
    "betrachtete": ("betrachten", "Verb (Präteritum 3sg)", "değerlendirdi / kabul etti", "regarded / viewed", '"betrachtete" (kök: betrachten — değerlendirdi)'),
    "betritt": ("betreten", "Verb (Präsens 3sg)", "adım atar / girer", "enters / steps into", '"betritt" (kök: betreten — adım atar)'),
    "bewahren": ("bewahren", "Verb (Infinitiv)", "korumak / muhafaza etmek", "preserve / maintain", '"bewahren" (kök: bewahren — korumak)'),
    "bewahrt": ("bewahren", "Verb (Präsens 3sg)", "korur / muhafaza eder", "preserves / maintains", '"bewahrt" (kök: bewahren — korur)'),
    "bewegen": ("bewegen", "Verb (Infinitiv)", "hareket etmek / ettirmek", "move", '"bewegen" (kök: bewegen — hareket etmek)'),
    "bewegt": ("bewegen", "Verb (Präsens 3sg)", "hareket eder / ettirir", "moves", '"bewegt" (kök: bewegen — hareket eder)'),
    "bewegten": ("bewegen", "Verb (Präteritum 3pl)", "hareket ettirdiler", "moved", '"bewegten" (kök: bewegen — hareket ettirdiler)'),
    "bewegungen": ("Bewegung", "Substantiv (Fem, Plural)", "hareketler", "movements", '"Bewegungen" (hareketler — movements)'),
    "beweist": ("beweisen", "Verb (Präsens 3sg)", "kanıtlar / ispatlar", "proves", '"beweist" (kök: beweisen — kanıtlar)'),
    "bewiesen": ("beweisen", "Verb (Partizip II)", "kanıtlanmış", "proven", '"bewiesen" (kök: beweisen — kanıtlanmış)'),
    "bewohnen": ("bewohnen", "Verb (Infinitiv)", "ikamet etmek / yaşamak", "inhabit", '"bewohnen" (kök: bewohnen — yaşamak)'),
    "bewusste": ("bewusst", "Adjektiv (Dekliniert)", "bilinçli", "conscious / deliberate", '"bewusste" (bilinçli — conscious)'),
    "bezeichnet": ("bezeichnen", "Verb (Präsens 3sg / Partizip II)", "adlandırır / nitelendirir", "designates / calls", '"bezeichnet" (kök: bezeichnen — adlandırır)'),
    "bezeugt": ("bezeugen", "Verb (Präsens 3sg)", "tanıklık eder", "testifies / witnesses", '"bezeugt" (kök: bezeugen — tanıklık eder)'),
    "blockierten": ("blockieren", "Verb (Präteritum 3pl)", "bloke ettiler / kapattılar", "blocked", '"blockierten" (kök: blockieren — kapattılar)'),
    "debattierten": ("debattieren", "Verb (Präteritum 3pl)", "tartıştılar / münazara ettiler", "debated", '"debattierten" (kök: debattieren — tartıştılar)'),
    "dokumentierte": ("dokumentieren", "Verb (Präteritum 3sg)", "belgeledi", "documented", '"dokumentierte" (kök: dokumentieren — belgeledi)'),
    "domestiziert": ("domestizieren", "Verb (Partizip II)", "evcilleştirilmiş", "domesticated", '"domestiziert" (kök: domestizieren — evcilleştirilmiş)'),
    "einfachen": ("einfach", "Adjektiv (Dekliniert)", "basit / sade", "simple", '"einfachen" (sade — simple)'),
    "einfachheit": ("Einfachheit", "Substantiv (Fem)", "sadelik / yalınlık", "simplicity", '"Einfachheit" (sadelik — simplicity)'),
    "eingerollt": ("einrollen", "Verb (Partizip II)", "kıvrılmış / toplanmış", "curled up / rolled up", '"eingerollt" (kök: einrollen — kıvrılmış)'),
    "einnehmen": ("einnehmen", "Verb (Infinitiv)", "almak / fethetmek", "take / capture", '"einnehmen" (kök: einnehmen — fethetmek)'),
    "einsamen": ("einsam", "Adjektiv (Dekliniert)", "ıssız / yalnız", "solitary / desolate", '"einsamen" (ıssız — secluded)'),
    "einsamkeit": ("Einsamkeit", "Substantiv (Fem)", "yalnızlık / inziva", "solitude / loneliness", '"Einsamkeit" (yalnızlık — solitude)'),
    "einschlafen": ("einschlafen", "Verb (Infinitiv)", "uykuya dalmak", "fall asleep", '"einschlafen" (kök: einschlafen — uykuya dalmak)'),
    "eintreffen": ("eintreffen", "Verb (Infinitiv)", "varmak / ulaşmak", "arrive", '"eintreffen" (kök: eintreffen — varmak)'),
    "einzelheiten": ("Einzelheit", "Substantiv (Fem, Plural)", "ayrıntılar / detaylar", "details", '"Einzelheiten" (ayrıntılar — details)'),
    "einzigartigen": ("einzigartig", "Adjektiv (Dekliniert)", "eşsiz / benzersiz", "unique", '"einzigartigen" (eşsiz — unique)'),
    "einzigen": ("einzig", "Adjektiv (Dekliniert)", "tek / yegane", "only / single", '"einzigen" (yegane — single)'),
    "einzuatmen": ("einatmen", "Verb (zu-Infinitiv)", "solumaya / içine çekmeye", "to inhale / breathe in", '"einzuatmen" (kök: einatmen — solumaya)'),
    "einzudicken": ("eindicken", "Verb (zu-Infinitiv)", "koyulaştırmaya", "to thicken", '"einzudicken" (kök: eindicken — koyulaştırmaya)'),
    "entdeckt": ("entdecken", "Verb (Präsens 3sg / Partizip II)", "keşfeder / keşfedilen", "discovers / discovered", '"entdeckt" (kök: entdecken — keşfeder)'),
    "entdeckte": ("entdecken", "Verb (Präteritum 3sg)", "keşfetti", "discovered", '"entdeckte" (kök: entdecken — keşfetti)'),
    "entdeckten": ("entdecken", "Verb (Präteritum 3pl)", "keşfettiler", "discovered", '"entdeckten" (kök: entdecken — keşfettiler)'),
    "entfaltet": ("entfalten", "Verb (Präsens 3sg)", "ortaya çıkarır / geliştirir", "unfolds / develops", '"entfaltet" (kök: entfalten — ortaya çıkarır)'),
    "entfernte": ("entfernen", "Verb (Präteritum 3sg / Adjektiv)", "uzaklaştırdı / uzak", "removed / distant", '"entfernte" (kök: entfernen — uzaklaştırdı)'),
    "entflohen": ("entfliehen", "Verb (Präteritum 3pl)", "kaçtılar / uzaklaştılar", "escaped / fled", '"entflohen" (kök: entfliehen — kaçtılar)'),
    "entscheidenden": ("entscheidend", "Adjektiv (Dekliniert)", "belirleyici / kritik", "decisive / crucial", '"entscheidenden" (belirleyici — decisive)'),
    "entscheidendste": ("entscheidend", "Adjektiv (Superlativ)", "en belirleyici / en kritik", "most decisive", '"entscheidendste" (en kritik — most decisive)'),
    "entspringen": ("entspringen", "Verb (Infinitiv)", "kaynaklanmak / doğmak", "originate / spring from", '"entspringen" (kök: entspringen — kaynaklanmak)'),
    "entstanden": ("entstehen", "Verb (Präteritum 3pl / Partizip II)", "ortaya çıktı / oluştu", "arose / formed", '"entstanden" (kök: entstehen — oluştu)'),
    "entstehen": ("entstehen", "Verb (Infinitiv / Präsens 3pl)", "oluşmak / ortaya çıkmak", "arise / develop", '"entstehen" (kök: entstehen — oluşmak)'),
    "entwickelte": ("entwickeln", "Verb (Präteritum 3sg)", "geliştirdi", "developed", '"entwickelte" (kök: entwickeln — geliştirdi)'),
    "entwickelten": ("entwickeln", "Verb (Präteritum 3pl)", "geliştirdiler", "developed", '"entwickelten" (kök: entwickeln — geliştirdiler)'),
    "entzogen": ("entziehen", "Verb (Präteritum 3pl / Partizip II)", "yoksun bıraktı / kaçındı", "withdrew / deprived", '"entzogen" (kök: entziehen — kaçındı)'),
    "erbaut": ("erbauen", "Verb (Partizip II)", "inşa edilmiş / yapılmış", "built / erected", '"erbaut" (kök: erbauen — inşa edilmiş)'),
    "erblichen": ("erbleichen", "Verb (Präteritum 3pl)", "solgunlaştılar", "paled", '"erblichen" (kök: erbleichen — solgunlaştılar)'),
    "erblindete": ("erblinden", "Verb (Präteritum 3sg)", "kör oldu", "went blind", '"erblindete" (kök: erblinden — kör oldu)'),
    "erdbeeren": ("Erdbeere", "Substantiv (Fem, Plural)", "çilekler", "strawberries", '"Erdbeeren" (çilekler — strawberries)'),
    "erfordert": ("erfordern", "Verb (Präsens 3sg)", "gerektirir / ister", "requires / demands", '"erfordert" (kök: erfordern — gerektirir)'),
    "erforscht": ("erforschen", "Verb (Präsens 3sg / Partizip II)", "araştırır / inceler", "explores / researches", '"erforscht" (kök: erforschen — araştırır)'),
    "erforschte": ("erforschen", "Verb (Präteritum 3sg)", "araştırdı / inceledi", "researched / explored", '"erforschte" (kök: erforschen — araştırdı)'),
    "erfrischendste": ("erfrischend", "Adjektiv (Superlativ)", "en ferahlatıcı", "most refreshing", '"erfrischendste" (en ferahlatıcı — most refreshing)'),
    "ergiebigen": ("ergiebig", "Adjektiv (Dekliniert)", "verimli / bereketli", "productive / fruitful", '"ergiebigen" (verimli — fruitful)'),
    "ergreifen": ("ergreifen", "Verb (Infinitiv)", "yakalamak / kavramak", "seize / grasp", '"ergreifen" (kök: ergreifen — yakalamak)'),
    "ergreifenden": ("ergreifend", "Adjektiv (Dekliniert)", "dokunaklı / etkileyici", "moving / poignant", '"ergreifenden" (dokunaklı — poignant)'),
    "ergriffen": ("ergreifen", "Verb (Präteritum 3pl / Partizip II)", "yakaladılar / kavradılar", "seized / gripped", '"ergriffen" (kök: ergreifen — yakaladılar)'),
    "erhebt": ("erheben", "Verb (Präsens 3sg)", "yükselir / kaldırır", "rises / lifts", '"erhebt" (kök: erheben — yükselir)'),
    "erinnert": ("erinnern", "Verb (Präsens 3sg)", "hatırlatır", "reminds", '"erinnert" (kök: erinnern — hatırlatır)'),
    "erinnerte": ("erinnern", "Verb (Präteritum 3sg)", "hatırlattı", "reminded", '"erinnerte" (kök: erinnern — hatırlattı)'),
    "erinnerungen": ("Erinnerung", "Substantiv (Fem, Plural)", "hatıralar / anılar", "memories", '"Erinnerungen" (anılar — memories)'),
    "erkannte": ("erkennen", "Verb (Präteritum 3sg)", "fark etti / tanıdı", "recognized / realized", '"erkannte" (kök: erkennen — fark etti)'),
    "erkennen": ("erkennen", "Verb (Infinitiv)", "fark etmek / tanımak", "recognize", '"erkennen" (kök: erkennen — tanımak)'),
    "erkennt": ("erkennen", "Verb (Präsens 3sg)", "fark eder / tanır", "recognizes", '"erkennt" (kök: erkennen — tanır)'),
    "erklimmt": ("erklimmen", "Verb (Präsens 3sg)", "tırmanır", "climbs / scales", '"erklimmt" (kök: erklimmen — tırmanır)'),
    "erkunden": ("erkunden", "Verb (Infinitiv)", "keşfetmek", "explore", '"erkunden" (kök: erkunden — keşfetmek)'),
    "erkundete": ("erkunden", "Verb (Präteritum 3sg)", "keşfetti", "explored", '"erkundete" (kök: erkunden — keşfetti)'),
    "erkundeten": ("erkunden", "Verb (Präteritum 3pl)", "keşfettiler", "explored", '"erkundeten" (kök: erkunden — keşfettiler)'),
    "erlaubt": ("erlauben", "Verb (Präsens 3sg)", "izin verir / olanak tanır", "allows / permits", '"erlaubt" (kök: erlauben — izin verir)'),
    "erlebte": ("erleben", "Verb (Präteritum 3sg)", "yaşadı / deneyimledi", "experienced", '"erlebte" (kök: erleben — yaşadı)'),
    "erntemaschinen": ("Erntemaschine", "Substantiv (Fem, Plural)", "biçerdöverler / hasat makineleri", "harvesters", '"Erntemaschinen" (hasat makineleri — harvesters)'),
    "erntete": ("ernten", "Verb (Präteritum 3sg)", "hasat etti / topladı", "harvested", '"erntete" (kök: ernten — hasat etti)'),
    "erprobt": ("erproben", "Verb (Partizip II / Präsens 3sg)", "sınanmış / test edilmiş", "tested / proven", '"erprobt" (kök: erproben — sınanmış)'),
    "erreichte": ("erreichen", "Verb (Präteritum 3sg)", "ulaştı", "reached", '"erreichte" (kök: erreichen — ulaştı)'),
    "erreichten": ("erreichen", "Verb (Präteritum 3pl)", "ulaştılar", "reached", '"erreichten" (kök: erreichen — ulaştılar)'),
    "errichten": ("errichten", "Verb (Infinitiv)", "inşa etmek / kurmak", "erect / build", '"errichten" (kök: errichten — inşa etmek)'),
    "errichteten": ("errichten", "Verb (Präteritum 3pl)", "inşa ettiler / kurdular", "built / erected", '"errichteten" (kök: errichten — inşa ettiler)'),
    "erringen": ("erringen", "Verb (Infinitiv)", "elde etmek / kazanmak", "achieve / win", '"erringen" (kök: erringen — elde etmek)'),
    "erscheint": ("erscheinen", "Verb (Präsens 3sg)", "görünür / ortaya çıkar", "appears / seems", '"erscheint" (kök: erscheinen — görünür)'),
    "ersetzen": ("ersetzen", "Verb (Infinitiv)", "yerine geçmek / değiştirmek", "replace", '"ersetzen" (kök: ersetzen — değiştirmek)'),
    "erstanden": ("erstehen", "Verb (Präteritum 3pl / Partizip II)", "yeniden doğdu / dirildi", "arose / resurged", '"erstanden" (kök: erstehen — yeniden doğdu)'),
    "erstehen": ("erstehen", "Verb (Infinitiv)", "yeniden doğmak / var olmak", "arise / revive", '"erstehen" (kök: erstehen — yeniden doğmak)'),
    "ersticken": ("ersticken", "Verb (Infinitiv)", "boğmak / havasız kalmak", "suffocate / choke", '"ersticken" (kök: ersticken — boğmak)'),
    "erwachen": ("erwachen", "Verb (Infinitiv)", "uyanmak", "wake up / awaken", '"erwachen" (kök: erwachen — uyanmak)'),
    "erwachten": ("erwachen", "Verb (Präteritum 3pl)", "uyandılar", "awoke", '"erwachten" (kök: erwachen — uyandılar)'),
    "erzielte": ("erzielen", "Verb (Präteritum 3sg)", "elde etti / sağladı", "achieved / attained", '"erzielte" (kök: erzielen — elde etti)'),
    "erzvorkommen": ("Erzvorkommen", "Substantiv (Neut)", "maden yatakları", "ore deposits", '"Erzvorkommen" (maden yatakları — ore deposits)'),
    "etablierte": ("etablieren", "Verb (Präteritum 3sg)", "yerleştirdi / kurdu", "established", '"etablierte" (kök: etablieren — kurdu)'),
    "existierte": ("existieren", "Verb (Präteritum 3sg)", "vardı / mevcuttu", "existed", '"existierte" (kök: existieren — vardı)'),
    "fermentierte": ("fermentiert", "Adjektiv (Dekliniert)", "fermente / mayalanmış", "fermented", '"fermentierte" (mayalanmış — fermented)'),
    "fermentierten": ("fermentiert", "Adjektiv (Dekliniert)", "fermente / mayalanmış", "fermented", '"fermentierten" (mayalanmış — fermented)'),
    "formuliert": ("formulieren", "Verb (Präsens 3sg / Partizip II)", "ifade eder / formüle eder", "formulates", '"formuliert" (kök: formulieren — formüle eder)'),
    "funktioniert": ("funktionieren", "Verb (Präsens 3sg)", "çalışır / işler", "functions / works", '"funktioniert" (kök: funktionieren — çalışır)'),
    "geachteten": ("geachtet", "Adjektiv (Dekliniert)", "saygı duyulan", "respected", '"geachteten" (saygı duyulan — respected)'),
    "gebiete": ("Gebiet", "Substantiv (Neut, Plural)", "bölgeler / alanlar", "regions / fields", '"Gebiete" (alanlar — regions)'),
    "geboren": ("gebären", "Verb (Partizip II)", "doğmuş", "born", '"geboren" (kök: gebären — doğmuş)'),
    "geborgen": ("bergen", "Verb (Partizip II) / Adjektiv", "güvende / huzurlu", "safe / sheltered", '"geborgen" (güvende — sheltered)'),
    "gedanken": ("Gedanke", "Substantiv (Mask, Plural)", "düşünceler", "thoughts", '"Gedanken" (düşünceler — thoughts)'),
    "gedankenwelt": ("Gedankenwelt", "Substantiv (Fem)", "düşünce dünyası", "intellectual world", '"Gedankenwelt" (düşünce dünyası — intellectual world)'),
    "gedeihen": ("gedeihen", "Verb (Infinitiv)", "gelişmek / serpilmek", "thrive / flourish", '"gedeihen" (kök: gedeihen — serpilmek)'),
    "gedeiht": ("gedeihen", "Verb (Präsens 3sg)", "gelişir / serpilir", "thrives / flourishes", '"gedeiht" (kök: gedeihen — serpilir)'),
    "geehrt": ("ehren", "Verb (Partizip II)", "onurlandırılmış", "honored", '"geehrt" (kök: ehren — onurlandırılmış)'),
    "gefahren": ("fahren", "Verb (Partizip II)", "sürmüş / gitmiş", "driven / traveled", '"gefahren" (kök: fahren — seyahat etmiş)'),
    "gefangen": ("fangen", "Verb (Partizip II)", "yakalanmış / tutsak", "captured / trapped", '"gefangen" (kök: fangen — tutsak)'),
    "gefiltert": ("filtern", "Verb (Partizip II)", "filtrelenmiş / süzülmüş", "filtered", '"gefiltert" (kök: filtern — filtrelenmiş)'),
    "gefrierenden": ("gefrierend", "Adjektiv (Dekliniert)", "donan / dondurucu", "freezing", '"gefrierenden" (donan — freezing)'),
    "gegenseitigen": ("gegenseitig", "Adjektiv (Dekliniert)", "karşılıklı", "mutual", '"gegenseitigen" (karşılıklı — mutual)'),
    "gegenwart": ("Gegenwart", "Substantiv (Fem)", "günümüz / şimdiki zaman", "present / modern day", '"Gegenwart" (günümüz — present)'),
    "gegessen": ("essen", "Verb (Partizip II)", "yenmiş", "eaten", '"gegessen" (kök: essen — yenmiş)'),
    "gehauen": ("hauen", "Verb (Partizip II)", "oyulmuş / yontulmuş", "carved / hewn", '"gehauen" (kök: hauen — oyulmuş)'),
    "gehirnfunktionen": ("Gehirnfunktion", "Substantiv (Fem, Plural)", "beyin fonksiyonları", "brain functions", '"Gehirnfunktionen" (beyin fonksiyonları — brain functions)'),
    "geholt": ("holen", "Verb (Partizip II)", "getirilmiş / getirdi", "fetched / brought", '"geholt" (kök: holen — getirilmiş)'),
    "geistigen": ("geistig", "Adjektiv (Dekliniert)", "zihinsel / düşünsel", "intellectual / mental", '"geistigen" (düşünsel — intellectual)'),
    "gekochte": ("gekocht", "Adjektiv (Dekliniert)", "pişmiş / kaynatılmış", "cooked / boiled", '"gekochte" (pişmiş — cooked)'),
    "gelangte": ("gelangen", "Verb (Präteritum 3sg)", "ulaştı / vardı", "reached / arrived", '"gelangte" (kök: gelangen — ulaştı)'),
    "gelassen": ("lassen", "Verb (Partizip II) / Adjektiv", "sakin / dingin", "calm / serene", '"gelassen" (sakin — serene)'),
    "gelassenen": ("gelassen", "Adjektiv (Dekliniert)", "sakin / soğukkanlı", "calm / composed", '"gelassenen" (sakin — composed)'),
    "gelassenheit": ("Gelassenheit", "Substantiv (Fem)", "sükunet / dinginlik", "serenity / composure", '"Gelassenheit" (sükunet — serenity)'),
    "gelebten": ("gelebt", "Adjektiv (Dekliniert)", "yaşanmış / tatbik edilmiş", "lived / practiced", '"gelebten" (yaşanmış — lived)'),
    "geleert": ("leeren", "Verb (Partizip II)", "boşaltılmış", "emptied", '"geleert" (kök: leeren — boşaltılmış)'),
    "gelegen": ("liegen", "Verb (Partizip II) / Adjektiv", "bulunan / yer alan", "situated / located", '"gelegen" (kök: liegen — yer alan)'),
    "gelernte": ("gelernt", "Adjektiv / Partizip II", "öğrenilen", "learned", '"gelernte" (kök: lernen — öğrenilen)'),
    "gelobt": ("loben", "Verb (Partizip II)", "övülmüş", "praised", '"gelobt" (kök: loben — övülmüş)'),
    "gemeinsamen": ("gemeinsam", "Adjektiv (Dekliniert)", "ortak / müşterek", "common / shared", '"gemeinsamen" (ortak — shared)'),
    "gemeinschaft": ("Gemeinschaft", "Substantiv (Fem)", "topluluk", "community", '"Gemeinschaft" (topluluk — community)'),
    "gemeinschaften": ("Gemeinschaft", "Substantiv (Fem, Plural)", "topluluklar", "communities", '"Gemeinschaften" (topluluklar — communities)'),
    "gemeistert": ("meistern", "Verb (Partizip II)", "ustalaşmış / üstesinden gelinmiş", "mastered", '"gemeistert" (kök: meistern — üstesinden gelinen)'),
    "genannt": ("nennen", "Verb (Partizip II)", "adlandırılan / denilen", "called / named", '"genannt" (kök: nennen — adlandırılan)'),
    "genannte": ("genannt", "Adjektiv (Dekliniert)", "adı geçen / denilen", "named / called", '"genannte" (denilen — named)'),
    "genossen": ("genießen", "Verb (Präteritum 3pl / Partizip II)", "zevk aldılar / tadını çıkardılar", "enjoyed", '"genossen" (kök: genießen — tadını çıkardılar)'),
    "geopfert": ("opfern", "Verb (Partizip II)", "feda edilmiş / kurban edilmiş", "sacrificed", '"geopfert" (kök: opfern — kurban edilmiş)'),
    "gepolte": ("gepolt", "Adjektiv (Dekliniert)", "yönlendirilmiş / kutuplanmış", "polarized / oriented", '"gepolte" (kutuplanmış — oriented)'),
    "gereicht": ("reichen", "Verb (Partizip II)", "ikram edilmiş / sunulmuş", "served / offered", '"gereicht" (kök: reichen — sunulmuş)'),
    "gereift": ("reifen", "Verb (Partizip II)", "olgunlaşmış", "ripened / matured", '"gereift" (kök: reifen — olgunlaşmış)'),
    "gericht": ("Gericht", "Substantiv (Neut)", "yemek / mahkeme", "dish / meal", '"Gericht" (yemek — dish)'),
    "gerichte": ("Gericht", "Substantiv (Neut, Plural)", "yemekler", "dishes / meals", '"Gerichte" (yemekler — dishes)'),
    "gerissen": ("reißen", "Verb (Partizip II)", "yırtılmış / kopmuş", "torn", '"gerissen" (kök: reißen — yırtılmış)'),
    "geruchsrezeptoren": ("Geruchsrezeptor", "Substantiv (Mask, Plural)", "koku reseptörleri", "olfactory receptors", '"Geruchsrezeptoren" (koku reseptörleri — olfactory receptors)'),
    "gesagt": ("sagen", "Verb (Partizip II)", "söylenmiş / dedi", "said", '"gesagt" (kök: sagen — söylenmiş)'),
    "gesamte": ("gesamt", "Adjektiv (Dekliniert)", "tüm / bütün", "entire / whole", '"gesamte" (bütün — entire)'),
    "gesamten": ("gesamt", "Adjektiv (Dekliniert)", "bütün / tüm", "entire / whole", '"gesamten" (bütün — entire)'),
    "geschickt": ("schicken", "Verb (Partizip II) / Adjektiv", "gönderilmiş / yetenekli", "sent / skillful", '"geschickt" (kök: schicken — yetenekli / gönderilmiş)'),
    "geschliffen": ("schleifen", "Verb (Partizip II)", "yontulmuş / parlatılmış", "ground / polished", '"geschliffen" (kök: schleifen — yontulmuş)'),
    "geschlossenen": ("geschlossen", "Adjektiv (Dekliniert)", "kapalı", "closed", '"geschlossenen" (kapalı — closed)'),
    "geschnitten": ("schneiden", "Verb (Partizip II)", "kesilmiş", "cut / sliced", '"geschnitten" (kök: schneiden — kesilmiş)'),
    "geschnittenen": ("geschnitten", "Adjektiv (Dekliniert)", "kesilmiş / dilimlenmiş", "sliced / cut", '"geschnittenen" (dilimlenmiş — sliced)'),
    "geschwungenen": ("geschwungen", "Adjektiv (Dekliniert)", "kıvrımlı / kavisli", "curved", '"geschwungenen" (kıvrımlı — curved: çay bardağı)'),
    "geselligkeit": ("Geselligkeit", "Substantiv (Fem)", "sosyallik / muhabbet", "conviviality / sociality", '"Geselligkeit" (sosyallik — sociability)'),
    "gesellschaften": ("Gesellschaft", "Substantiv (Fem, Plural)", "toplumlar", "societies", '"Gesellschaften" (toplumlar — societies)'),
    "gesellschaftlichen": ("gesellschaftlich", "Adjektiv (Dekliniert)", "toplumsal / sosyal", "social / societal", '"gesellschaftlichen" (toplumsal — social)'),
    "gesetzt": ("setzen", "Verb (Partizip II)", "konulmuş / yerleştirilmiş", "placed / set", '"gesetzt" (kök: setzen — yerleştirilmiş)'),
    "gesichtet": ("sichten", "Verb (Partizip II)", "görülmüş / tespit edilmiş", "sighted / spotted", '"gesichtet" (kök: sichten — görülmüş)'),
    "gespannten": ("gespannt", "Adjektiv (Dekliniert)", "gergin / meraklı", "tense / curious", '"gespannten" (gergin — tense)'),
    "gespart": ("sparen", "Verb (Partizip II)", "tasarruf edilmiş / biriktirilmiş", "saved", '"gespart" (kök: sparen — tasarruf edilmiş)'),
    "gespielt": ("spielen", "Verb (Partizip II)", "oynanmış", "played", '"gespielt" (kök: spielen — oynanmış)'),
    "gestalt": ("Gestalt", "Substantiv (Fem)", "biçim / figür / şekil", "form / figure", '"Gestalt" (figür — form)'),
    "gestalten": ("gestalten", "Verb (Infinitiv)", "şekillendirmek / tasarlamak", "shape / design", '"gestalten" (kök: gestalten — şekillendirmek)'),
    "gesucht": ("suchen", "Verb (Partizip II)", "aranmış", "sought / searched", '"gesucht" (kök: suchen — aranmış)'),
    "gesunden": ("gesund", "Adjektiv (Dekliniert)", "sağlıklı", "healthy", '"gesunden" (sağlıklı — healthy)'),
    "gesundheit": ("Gesundheit", "Substantiv (Fem)", "sağlık", "health", '"Gesundheit" (sağlık — health)'),
    "getragen": ("tragen", "Verb (Partizip II)", "taşınmış / giyilmiş", "carried / borne", '"getragen" (kök: tragen — taşınmış)'),
    "getragenen": ("getragen", "Adjektiv (Dekliniert)", "taşınan / desteklenen", "carried / supported", '"getragenen" (desteklenen — supported)'),
    "getrieben": ("treiben", "Verb (Partizip II)", "sürüklenmiş / yönlendirilmiş", "driven", '"getrieben" (kök: treiben — sürüklenmiş)'),
    "getropft": ("tropfen", "Verb (Partizip II)", "damlatılmış", "dripped", '"getropft" (kök: tropfen — damlatılmış)'),
    "getunkten": ("getunkt", "Adjektiv (Dekliniert)", "batırılmış", "dipped", '"getunkten" (batırılmış — dipped)'),
    "geweckt": ("wecken", "Verb (Partizip II)", "uyandırılmış", "awakened / aroused", '"geweckt" (kök: wecken — uyandırılmış)'),
    "geweitete": ("geweitet", "Adjektiv (Dekliniert)", "genişletilmiş", "widened / dilated", '"geweitete" (genişletilmiş — widened)'),
    "gewinnt": ("gewinnen", "Verb (Präsens 3sg)", "kazanır", "wins / gains", '"gewinnt" (kök: gewinnen — kazanır)'),
    "gewissen": ("gewiss", "Adjektiv (Dekliniert)", "belirli / kesin", "certain", '"gewissen" (belirli — certain)'),
    "gewohnheit": ("Gewohnheit", "Substantiv (Fem)", "alışkanlık", "habit", '"Gewohnheit" (alışkanlık — habit)'),
    "gewohnheiten": ("Gewohnheit", "Substantiv (Fem, Plural)", "alışkanlıklar", "habits", '"Gewohnheiten" (alışkanlıklar — habits)'),
    "gezielt": ("gezielt", "Adjektiv / Adverb", "hedefli / bilinçli", "targeted / focused", '"gezielt" (hedefli — targeted)'),
    "isoliert": ("isolieren", "Verb (Präsens 3sg / Partizip II)", "yalıtır / izole eder", "isolates / isolated", '"isoliert" (kök: isolieren — izole eder)'),
    "kalkulierte": ("kalkulieren", "Verb (Präteritum 3sg)", "hesapladı", "calculated", '"kalkulierte" (kök: kalkulieren — hesapladı)'),
    "katapultiert": ("katapultieren", "Verb (Präsens 3sg)", "fırlatır / yükseltir", "catapults", '"katapultiert" (kök: katapultieren — fırlatır)'),
    "konzentrierte": ("konzentrieren", "Verb (Präteritum 3sg)", "odaklandı", "focused / concentrated", '"konzentrierte" (kök: konzentrieren — odaklandı)'),
    "mitten": ("mitten", "Lokaladverb", "ortasında", "in the middle / midst", '"mitten" (ortasında — in the midst of)'),
    "nachbarschaft": ("Nachbarschaft", "Substantiv (Fem)", "komşuluk", "neighborhood", '"Nachbarschaft" (komşuluk — neighborhood)'),
    "nachricht": ("Nachricht", "Substantiv (Fem)", "haber / mesaj", "news / message", '"Nachricht" (mesaj / haber — message)'),
    "nachrichten": ("Nachricht", "Substantiv (Fem, Plural)", "haberler", "news", '"Nachrichten" (haberler — news)'),
    "nachzuzeichnen": ("nachzeichnen", "Verb (zu-Infinitiv)", "izini sürmeye / çizmeye", "to trace", '"nachzuzeichnen" (kök: nachzeichnen — izini sürmeye)'),
    "notierte": ("notieren", "Verb (Präteritum 3sg)", "not etti", "noted down", '"notierte" (kök: notieren — not etti)'),
    "organisierten": ("organisieren", "Verb (Präteritum 3pl)", "organize ettiler", "organized", '"organisierten" (kök: organisieren — organize ettiler)'),
    "postulierte": ("postulieren", "Verb (Präteritum 3sg)", "ileri sürdü / varsaydı", "postulated", '"postulierte" (kök: postulieren — varsaydı)'),
    "potenziert": ("potenzieren", "Verb (Präsens 3sg)", "katlar / güçlendirir", "multiplies / enhances", '"potenziert" (kök: potenzieren — güçlendirir)'),
    "probierte": ("probieren", "Verb (Präteritum 3sg)", "denedi / tattı", "tried / tasted", '"probierte" (kök: probieren — denedi)'),
    "rekonstruiert": ("rekonstruieren", "Verb (Partizip II)", "yeniden inşa edilmiş", "reconstructed", '"rekonstruiert" (kök: rekonstruieren — yeniden inşa edilmiş)'),
    "repariert": ("reparieren", "Verb (Partizip II / Präsens 3sg)", "onarılmış / onarır", "repaired / repairs", '"repariert" (kök: reparieren — onarılmış)'),
    "reparierte": ("reparieren", "Verb (Präteritum 3sg)", "onardı / tamir etti", "repaired", '"reparierte" (kök: reparieren — onardı)'),
    "reparierten": ("reparieren", "Verb (Präteritum 3pl)", "onardılar", "repaired", '"reparierten" (kök: reparieren — onardılar)'),
    "restaurierte": ("restaurieren", "Verb (Präteritum 3sg)", "restore etti", "restored", '"restaurierte" (kök: restaurieren — restore etti)'),
    "serviert": ("servieren", "Verb (Partizip II / Präsens 3sg)", "servis edilir / servis edilen", "served", '"serviert" (kök: servieren — servis edilir)'),
    "servierten": ("servieren", "Verb (Präteritum 3pl)", "servis ettiler / sundular", "served", '"servierten" (kök: servieren — servis ettiler)'),
    "symbolisiert": ("symbolisieren", "Verb (Präsens 3sg)", "simgeler / sembolize eder", "symbolizes", '"symbolisiert" (kök: symbolisieren — simgeler)'),
    "taillierten": ("tailliert", "Adjektiv (Dekliniert)", "ince belli (bardak)", "waisted / curved", '"taillierten" (ince belli — waisted)'),
    "transportiert": ("transportieren", "Verb (Partizip II / Präsens 3sg)", "taşınan / taşır", "transported / carries", '"transportiert" (kök: transportieren — taşır)'),
    "transportierten": ("transportieren", "Verb (Präteritum 3pl)", "taşıdılar", "transported", '"transportierten" (kök: transportieren — taşıdılar)'),
    "unfiltriert": ("unfiltriert", "Adjektiv", "filtrelenmemiş", "unfiltered", '"unfiltriert" (filtrelenmemiş — unfiltered)'),
    "unterbrechen": ("unterbrechen", "Verb (Infinitiv)", "bölmek / kesintiye uğratmak", "interrupt", '"unterbrechen" (kök: unterbrechen — kesmek)'),
    "untergezogen": ("unterziehen", "Verb (Partizip II)", "tabi tutulmuş / altına sokulmuş", "subjected / undergone", '"untergezogen" (kök: unterziehen — tabi tutulmuş)'),
    "unterirdischen": ("unterirdisch", "Adjektiv (Dekliniert)", "yeraltındaki", "underground / subterranean", '"unterirdischen" (yeraltı — underground)'),
    "unterliegen": ("unterliegen", "Verb (Infinitiv / Präsens 3pl)", "tabi olmak / yenik düşmek", "be subject to", '"unterliegen" (kök: unterliegen — tabi olmak)'),
    "untermauerten": ("untermauern", "Verb (Präteritum 3pl)", "desteklediler / temellendirdiler", "substantiated", '"untermauerten" (kök: untermauern — desteklediler)'),
    "unterschiedlichste": ("unterschiedlich", "Adjektiv (Superlativ)", "en çeşitli / birbirinden farklı", "most varied", '"unterschiedlichste" (en çeşitli — most diverse)'),
    "untersuchungen": ("Untersuchung", "Substantiv (Fem, Plural)", "araştırmalar / incelemeler", "examinations / studies", '"Untersuchungen" (incelemeler — studies)'),
    "unterteilen": ("unterteilen", "Verb (Infinitiv)", "bölümlere ayırmak", "subdivide", '"unterteilen" (kök: unterteilen — bölümlere ayırmak)'),
    "unterteilt": ("unterteilen", "Verb (Partizip II / Präsens 3sg)", "bölümlere ayrılmış / ayırır", "subdivided", '"unterteilt" (kök: unterteilen — bölümlere ayrılmış)'),
    "unterwerfen": ("unterwerfen", "Verb (Infinitiv)", "boyun eğdirmek / tabi kılmak", "subjugate / subject", '"unterwerfen" (kök: unterwerfen — boyun eğdirmek)'),
    "verankerte": ("verankern", "Verb (Präteritum 3sg)", "demirledi / yerleştirdi", "anchored", '"verankerte" (kök: verankern — yerleştirdi)'),
    "verarbeitet": ("verarbeiten", "Verb (Partizip II / Präsens 3sg)", "işlenmiş / işler", "processed / processes", '"verarbeitet" (kök: verarbeiten — işlenmiş)'),
    "verbannt": ("verbannen", "Verb (Partizip II)", "sürgün edilmiş", "banished", '"verbannt" (kök: verbannen — sürgün edilmiş)'),
    "verbergen": ("verbergen", "Verb (Infinitiv)", "gizlemek / saklamak", "hide / conceal", '"verbergen" (kök: verbergen — gizlemek)'),
    "verbinden": ("verbinden", "Verb (Infinitiv)", "bağlamak / birleştirmek", "connect / unite", '"verbinden" (kök: verbinden — birleştirmek)'),
    "verbindet": ("verbinden", "Verb (Präsens 3sg)", "bağlar / birleştirir", "connects / links", '"verbindet" (kök: verbinden — bağlar)'),
    "verbindungen": ("Verbindung", "Substantiv (Fem, Plural)", "bağlantılar / bileşikler", "connections", '"Verbindungen" (bağlar — connections)'),
    "verblassen": ("verblassen", "Verb (Infinitiv)", "solup gitmek", "fade", '"verblassen" (kök: verblassen — solup gitmek)'),
    "verborgen": ("verbergen", "Verb (Partizip II) / Adjektiv", "gizli / saklı", "hidden / concealed", '"verborgen" (saklı — hidden)'),
    "verborgenen": ("verborgen", "Adjektiv (Dekliniert)", "gizli / saklı olan", "hidden", '"verborgenen" (gizli — hidden)'),
    "verbote": ("Verbot", "Substantiv (Neut, Plural)", "yasaklar", "bans / prohibitions", '"Verbote" (yasaklar — bans)'),
    "verboten": ("verbieten", "Verb (Partizip II)", "yasaklanmış", "forbidden / banned", '"verboten" (kök: verbieten — yasaklanmış)'),
    "verbraucht": ("verbrauchen", "Verb (Präsens 3sg / Partizip II)", "tüketir / tükenmiş", "consumes / consumed", '"verbraucht" (kök: verbrauchen — tüketir)'),
    "verbrennungen": ("Verbrennung", "Substantiv (Fem, Plural)", "yanıklar", "burns", '"Verbrennungen" (yanıklar — burns)'),
    "verbringen": ("verbringen", "Verb (Infinitiv)", "vakit geçirmek", "spend (time)", '"verbringen" (kök: verbringen — vakit geçirmek)'),
    "verbunden": ("verbinden", "Verb (Partizip II)", "bağlı / birleşmiş", "connected / linked", '"verbunden" (kök: verbinden — bağlı)'),
    "verdanken": ("verdanken", "Verb (Infinitiv / Präsens 3pl)", "borçlu olmak", "owe to", '"verdanken" (kök: verdanken — borçlu olmak)'),
    "verdankt": ("verdanken", "Verb (Präsens 3sg)", "borçludur", "owes to", '"verdankt" (kök: verdanken — borçludur)'),
    "verderben": ("verderben", "Verb (Infinitiv)", "bozulmak / çürümek", "spoil", '"verderben" (kök: verderben — bozulmak)'),
    "verderblichste": ("verderblich", "Adjektiv (Superlativ)", "en çabuk bozulan", "most perishable", '"verderblichste" (en çabuk bozulan — most perishable)'),
    "verdickt": ("verdicken", "Verb (Präsens 3sg / Partizip II)", "koyulaşır / koyulaşmış", "thickens / thickened", '"verdickt" (kök: verdicken — koyulaşır)'),
    "verdienst": ("Verdienst", "Substantiv (Neut/Mask)", "kazanç / liyakat", "merit / earnings", '"Verdienst" (liyakat — merit)'),
    "verdorrten": ("verdorrt", "Adjektiv (Dekliniert)", "kurumuş / solmuş", "withered", '"verdorrten" (kurumuş — withered)'),
    "vereinheitlichten": ("vereinheitlichen", "Verb (Präteritum 3pl)", "standartlaştırdılar / birleştirdiler", "standardized", '"vereinheitlichten" (kök: vereinheitlichen — standartlaştırdılar)'),
    "vereinsamen": ("vereinsamen", "Verb (Infinitiv)", "yalnızlaşmak", "become lonely", '"vereinsamen" (kök: vereinsamen — yalnızlaşmak)'),
    "vereint": ("vereinen", "Verb (Präsens 3sg / Partizip II)", "birleştirir / birleşmiş", "unites / united", '"vereint" (kök: vereinen — birleştirir)'),
    "verfasste": ("verfassen", "Verb (Präteritum 3sg)", "kaleme aldı / yazdı", "authored / wrote", '"verfasste" (kök: verfassen — kaleme aldı)'),
    "verfassten": ("verfassen", "Verb (Präteritum 3pl)", "yazdılar / kaleme aldılar", "authored / wrote", '"verfassten" (kök: verfassen — kaleme aldılar)'),
    "vergangenheit": ("Vergangenheit", "Substantiv (Fem)", "geçmiş", "past", '"Vergangenheit" (geçmiş — past)'),
    "vergehen": ("vergehen", "Verb (Infinitiv)", "geçip gitmek (zaman)", "pass / elapse", '"vergehen" (kök: vergehen — geçip gitmek)'),
    "vergiftet": ("vergiften", "Verb (Partizip II)", "zehirlenmiş", "poisoned", '"vergiftet" (kök: vergiften — zehirlenmiş)'),
    "verhalten": ("Verhalten", "Substantiv (Neut)", "davranış / tutum", "behavior", '"Verhalten" (davranış — behavior)'),
    "verhaspelte": ("verhaspeln", "Verb (Präteritum 3sg)", "dili sürçtü / şaşırdı", "fumbled / misspoke", '"verhaspelte" (kök: verhaspeln — dili sürçtü)'),
    "verhindert": ("verhindern", "Verb (Präsens 3sg)", "engeller / önler", "prevents", '"verhindert" (kök: verhindern — engeller)'),
    "verlangen": ("verlangen", "Verb (Infinitiv)", "talep etmek / istemek", "demand / require", '"verlangen" (kök: verlangen — talep etmek)'),
    "verlassen": ("verlassen", "Verb (Infinitiv / Partizip II)", "terk etmek / terk edilmiş", "leave / abandoned", '"verlassen" (kök: verlassen — terk etmek)'),
    "verleihen": ("verleihen", "Verb (Infinitiv)", "bahşetmek / kazandırmak", "impart / lend", '"verleihen" (kök: verleihen — kazandırmak)'),
    "verletzen": ("verletzen", "Verb (Infinitiv)", "yaralamak / incitmek", "injure / hurt", '"verletzen" (kök: verletzen — incitmek)'),
    "verletzte": ("verletzen", "Verb (Präteritum 3sg)", "yaraladı / incitti", "injured / hurt", '"verletzte" (kök: verletzen — yaraladı)'),
    "verliehen": ("verleihen", "Verb (Präteritum 3pl / Partizip II)", "kazandırdılar / bahşettiler", "imparted / bestowed", '"verliehen" (kök: verleihen — kazandırdılar)'),
    "verlorenen": ("verloren", "Adjektiv (Dekliniert)", "kaybolan / yitirilen", "lost", '"verlorenen" (kaybolan — lost)'),
    "verlust": ("Verlust", "Substantiv (Mask)", "kayıp", "loss", '"Verlust" (kayıp — loss)'),
    "vermacht": ("vermachen", "Verb (Partizip II)", "miras bırakılmış", "bequeathed", '"vermacht" (kök: vermachen — miras bırakılmış)'),
    "vermittelt": ("vermitteln", "Verb (Präsens 3sg)", "aktarır / iletir", "conveys / imparts", '"vermittelt" (kök: vermitteln — aktarır)'),
    "vermochte": ("vermögen", "Verb (Präteritum 3sg)", "gücü yetti / başarabildi", "was able to", '"vermochte" (kök: vermögen — başarabildi)'),
    "verraten": ("verraten", "Verb (Infinitiv / Partizip II)", "ihanet etmek / ele vermek", "betray / reveal", '"verraten" (kök: verraten — ele vermek)'),
    "verrichten": ("verrichten", "Verb (Infinitiv)", "yerine getirmek / icra etmek", "perform", '"verrichten" (kök: verrichten — yerine getirmek)'),
    "verriegelten": ("verriegeln", "Verb (Präteritum 3pl)", "kilitlediler / sürgülediler", "bolted / locked", '"verriegelten" (kök: verriegeln — sürgülediler)'),
    "verringert": ("verringern", "Verb (Präsens 3sg)", "azaltır", "reduces", '"verringert" (kök: verringern — azaltır)'),
    "versammelten": ("versammeln", "Verb (Präteritum 3pl)", "toplandılar", "gathered", '"versammelten" (kök: versammeln — toplandılar)'),
    "versammlungen": ("Versammlung", "Substantiv (Fem, Plural)", "toplantılar", "assemblies / meetings", '"Versammlungen" (toplantılar — assemblies)'),
    "verschiedenen": ("verschieden", "Adjektiv (Dekliniert)", "farklı / çeşitli", "different / various", '"verschiedenen" (farklı — various)'),
    "verschlungen": ("verschlingen", "Verb (Partizip II)", "düğümlenmiş / birbirine geçmiş", "intertwined / devoured", '"verschlungen" (kök: verschlingen — birbirine geçmiş)'),
    "verschwiegenheit": ("Verschwiegenheit", "Substantiv (Fem)", "ketumluk / sır saklama", "discretion / secrecy", '"Verschwiegenheit" (ketumluk — secrecy)'),
    "verschwinden": ("verschwinden", "Verb (Infinitiv)", "kaybolmak / yok olmak", "disappear", '"verschwinden" (kök: verschwinden — kaybolmak)'),
    "versetzt": ("versetzen", "Verb (Partizip II / Präsens 3sg)", "karıştırılmış / sokar", "mixed / puts into", '"versetzt" (kök: versetzen — karıştırılmış)'),
    "versiegelt": ("versiegeln", "Verb (Partizip II)", "mühürlenmiş", "sealed", '"versiegelt" (kök: versiegeln — mühürlenmiş)'),
    "versorgen": ("versorgen", "Verb (Infinitiv)", "beslemek / tedarik etmek", "supply / provide", '"versorgen" (kök: versorgen — tedarik etmek)'),
    "verstaubten": ("verstaubt", "Adjektiv (Dekliniert)", "tozlanmış", "dusty", '"verstaubten" (tozlanmış — dusty)'),
    "versteckt": ("verstecken", "Verb (Partizip II / Präsens 3sg)", "saklanmış / saklar", "hidden / hides", '"versteckt" (kök: verstecken — saklanmış)'),
    "versteckten": ("verstecken", "Verb (Präteritum 3pl)", "saklandılar", "hid", '"versteckten" (kök: verstecken — saklandılar)'),
    "verteidigungskunst": ("Verteidigungskunst", "Substantiv (Fem)", "savunma sanatı", "art of defense", '"Verteidigungskunst" (savunma sanatı — art of defense)'),
    "verteuerte": ("verteuern", "Verb (Präteritum 3sg)", "pahalılaştırdı", "made more expensive", '"verteuerte" (kök: verteuern — pahalılaştırdı)'),
    "vertrauten": ("vertraut", "Adjektiv (Dekliniert)", "aşina / tanıdık", "familiar", '"vertrauten" (tanıdık — familiar)'),
    "verwandelt": ("verwandeln", "Verb (Präsens 3sg / Partizip II)", "dönüştürür / dönüşmüş", "transforms / transformed", '"verwandelt" (kök: verwandeln — dönüştürür)'),
    "verwandelte": ("verwandeln", "Verb (Präteritum 3sg)", "dönüştürdü", "transformed", '"verwandelte" (kök: verwandeln — dönüştürdü)'),
    "verwandelten": ("verwandeln", "Verb (Präteritum 3pl)", "dönüştürdüler", "transformed", '"verwandelten" (kök: verwandeln — dönüştürdüler)'),
    "verweisen": ("verweisen", "Verb (Infinitiv)", "işaret etmek / atıfta bulunmak", "refer / point to", '"verweisen" (kök: verweisen — işaret etmek)'),
    "verwundete": ("verwunden", "Verb (Präteritum 3sg / Adjektiv)", "yaraladı / yaralı", "wounded", '"verwundete" (kök: verwunden — yaraladı)'),
    "verzauberte": ("verzaubern", "Verb (Präteritum 3sg)", "büyüledi", "enchanted", '"verzauberte" (kök: verzaubern — büyüledi)'),
    "verzehren": ("verzehren", "Verb (Infinitiv)", "tüketmek / yemek", "consume", '"verzehren" (kök: verzehren — tüketmek)'),
    "verzehrt": ("verzehren", "Verb (Partizip II / Präsens 3sg)", "tüketilmiş / tüketir", "consumed / consumes", '"verzehrt" (kök: verzehren — tüketilir)'),
    "verzehrte": ("verzehren", "Verb (Präteritum 3sg)", "tüketti / yedi", "consumed", '"verzehrte" (kök: verzehren — tüketti)'),
    "verzerrungen": ("Verzerrung", "Substantiv (Fem, Plural)", "çarpıtmalar / bozulmalar", "distortions", '"Verzerrungen" (çarpıtmalar — distortions)'),
    "verzicht": ("Verzicht", "Substantiv (Mask)", "feragat / vazgeçme", "renunciation / waiver", '"Verzicht" (feragat — renunciation)'),
    "verzichten": ("verzichten", "Verb (Infinitiv)", "vazgeçmek / feragat etmek", "waive / do without", '"verzichten" (kök: verzichten — vazgeçmek)'),
    "verzichtete": ("verzichten", "Verb (Präteritum 3sg)", "vazgeçti / feragat etti", "did without / waived", '"verzichtete" (kök: verzichten — vazgeçti)'),
    "vorderen": ("vorderer", "Adjektiv (Dekliniert)", "ön / öndeki", "front / anterior", '"vorderen" (öndeki — front)'),
    "vorgefassten": ("vorgefasst", "Adjektiv (Dekliniert)", "önyargılı / peşin", "preconceived", '"vorgefassten" (peşin hükümlü — preconceived)'),
    "vorherrschenden": ("vorherrschend", "Adjektiv (Dekliniert)", "egemen / hakim olan", "predominant", '"vorherrschenden" (hakim — prevailing)'),
    "vorstellungen": ("Vorstellung", "Substantiv (Fem, Plural)", "tasavvurlar / fikirler / temsiller", "conceptions / ideas", '"Vorstellungen" (fikirler — ideas)'),
    "vortrugen": ("vortragen", "Verb (Präteritum 3pl)", "icra ettiler / sundular", "performed / recited", '"vortrugen" (kök: vortragen — icra ettiler)'),
    "vorzubeugen": ("vorbeugen", "Verb (zu-Infinitiv)", "önlemeye / engellemeye", "to prevent", '"vorzubeugen" (kök: vorbeugen — önlemeye)'),
    "zeremonien": ("Zeremonie", "Substantiv (Fem, Plural)", "törenler / seremoniler", "ceremonies", '"Zeremonien" (törenler — ceremonies)'),
    "zubereitet": ("zubereiten", "Verb (Partizip II / Präsens 3sg)", "hazırlanmış / hazırlar", "prepared / prepares", '"zubereitet" (kök: zubereiten — hazırlanmış)'),
    "zubereitungsarten": ("Zubereitungsart", "Substantiv (Fem, Plural)", "hazırlama yöntemleri", "preparation methods", '"Zubereitungsarten" (hazırlama yöntemleri — preparation methods)'),
    "zuerst": ("zuerst", "Temporaladverb", "öncelikle / ilk önce", "first / initially", '"zuerst" (ilk önce — first)'),
    "zuflucht": ("Zuflucht", "Substantiv (Fem)", "sığınak / melce", "refuge", '"Zuflucht" (sığınak — refuge)'),
    "zufluchten": ("Zuflucht", "Substantiv (Fem, Plural)", "sığınaklar", "refuges", '"Zufluchten" (sığınaklar — refuges)'),
    "zufluchtsort": ("Zufluchtsort", "Substantiv (Mask)", "sığınma yeri / liman", "place of refuge", '"Zufluchtsort" (sığınak — refuge)'),
    "zugunsten": ("zugunsten", "Präposition", "lehine / yararına", "in favor of", '"zugunsten" (yararına — in favor of)'),
    "zukunft": ("Zukunft", "Substantiv (Fem)", "gelecek", "future", '"Zukunft" (gelecek — future)'),
    "zusammen": ("zusammen", "Adverb", "birlikte / beraber", "together", '"zusammen" (birlikte — together)'),
    "zusammenarbeit": ("Zusammenarbeit", "Substantiv (Fem)", "işbirliği", "cooperation", '"Zusammenarbeit" (işbirliği — cooperation)'),
    "zusammenzuleben": ("zusammenleben", "Verb (zu-Infinitiv)", "birlikte yaşamaya", "to live together", '"zusammenzuleben" (kök: zusammenleben — birlikte yaşamaya)'),
    "überdauert": ("überdauern", "Verb (Präsens 3sg)", "zamana direnir / baki kalır", "outlasts / survives", '"überdauert" (kök: überdauern — zamana direnir)'),
    "überdecken": ("überdecken", "Verb (Infinitiv)", "örtmek / gizlemek", "cover up", '"überdecken" (kök: überdecken — örtmek)'),
    "überhaupt": ("überhaupt", "Adverb", "aslında / hiç / genel olarak", "at all / in general", '"überhaupt" (aslında — at all)'),
    "überheblichkeit": ("Überheblichkeit", "Substantiv (Fem)", "kibir / böbürlenme", "arrogance", '"Überheblichkeit" (kibir — arrogance)'),
    "überleben": ("überleben", "Verb (Infinitiv)", "hayatta kalmak", "survive", '"überleben" (kök: überleben — hayatta kalmak)'),
    "überlieferten": ("überliefert", "Adjektiv (Dekliniert)", "nesilden nesile aktarılan", "traditional / handed down", '"überlieferten" (aktarılan — handed down)'),
    "übernehmen": ("übernehmen", "Verb (Infinitiv)", "üstlenmek / devralmak", "take over / adopt", '"übernehmen" (kök: übernehmen — üstlenmek)'),
    "überwiegt": ("überwiegen", "Verb (Präsens 3sg)", "ağır basar", "predominates / outweighs", '"überwiegt" (kök: überwiegen — ağır basar)'),
    "überwinden": ("überwinden", "Verb (Infinitiv)", "aşmak / üstesinden gelmek", "overcome / breach", '"überwinden" (kök: überwinden — aşmak)'),
    # Common irregular & core verbs
    "gibt": ("geben", "Verb (Präsens 3sg)", "vardır / verir", "there is / gives", '"gibt" (kök: geben — vardır / verir: es gibt)'),
    "gab": ("geben", "Verb (Präteritum 3sg)", "vardı / verdi", "there was / gave", '"gab" (kök: geben — vardı / verdi: es gab)'),
    "steht": ("stehen", "Verb (Präsens 3sg)", "durur / yer alır", "stands / is located", '"steht" (kök: stehen — durur / yer alır)'),
    "stand": ("stehen", "Verb (Präteritum 3sg)", "duruyordu / durdu", "stood", '"stand" (kök: stehen — duruyordu)'),
    "liegt": ("liegen", "Verb (Präsens 3sg)", "bulunur / yer alır", "lies / is situated", '"liegt" (kök: liegen — bulunur)'),
    "lag": ("liegen", "Verb (Präteritum 3sg)", "bulunuyordu / yer alıyordu", "lay / was located", '"lag" (kök: liegen — bulunuyordu)'),
    "wusste": ("wissen", "Verb (Präteritum 3sg)", "biliyordu", "knew", '"wusste" (kök: wissen — biliyordu)'),
    "weiß": ("wissen", "Verb (Präsens 3sg)", "bilir", "knows", '"weiß" (kök: wissen — bilir)'),
    "hält": ("halten", "Verb (Präsens 3sg)", "tutar / korur", "holds / keeps", '"hält" (kök: halten — tutar)'),
    "hielt": ("halten", "Verb (Präteritum 3sg)", "tuttu / korudu", "held / kept", '"hielt" (kök: halten — tuttu)'),
    "lässt": ("lassen", "Verb (Präsens 3sg)", "bırakır / izin verir", "lets / leaves", '"lässt" (kök: lassen — bırakır)'),
    "ließ": ("lassen", "Verb (Präteritum 3sg)", "bıraktı / izin verdi", "let / left", '"ließ" (kök: lassen — bıraktı)'),
    "bringt": ("bringen", "Verb (Präsens 3sg)", "getirir", "brings", '"bringt" (kök: bringen — getirir)'),
    "brachte": ("bringen", "Verb (Präteritum 3sg)", "getirdi", "brought", '"brachte" (kök: bringen — getirdi)'),
    "nahm": ("nehmen", "Verb (Präteritum 3sg)", "aldı", "took", '"nahm" (kök: nehmen — aldı)'),
    "nimmt": ("nehmen", "Verb (Präsens 3sg)", "alır", "takes", '"nimmt" (kök: nehmen — alır)'),
    "saß": ("sitzen", "Verb (Präteritum 3sg)", "oturuyordu", "sat", '"saß" (kök: sitzen — oturuyordu)'),
    "sah": ("sehen", "Verb (Präteritum 3sg)", "gördü", "saw", '"sah" (kök: sehen — gördü)'),
    "macht": ("machen", "Verb (Präsens 3sg)", "yapar", "makes / does", '"macht" (kök: machen — yapar)'),
    "machte": ("machen", "Verb (Präteritum 3sg)", "yaptı", "made / did", '"machte" (kök: machen — yaptı)')
}


def main():
    with open(SCRATCH_FILE, "r", encoding="utf-8") as f:
        target_items = json.load(f)

    missing = []
    for k in target_items:
        if k not in CURATED_DE_MAP:
            missing.append(k)

    if missing:
        print(f"Warning: {len(missing)} keys missing from CURATED_DE_MAP: {missing[:10]}")
    else:
        print(f"✓ All {len(target_items)} German keys in {SCRATCH_FILE.name} are present in CURATED_DE_MAP!")

    content = '# -*- coding: utf-8 -*-\n"""\nComprehensive verified German fallthrough translations,\nlemmas, and parts of speech.\n"""\n\nDE_ADDITIONAL_FALLTHROUGH_MAP = {\n'
    for k, v in sorted(CURATED_DE_MAP.items()):
        lemma, pos, tr_trans, en_trans, note = v
        content += f'    "{k}": ({json.dumps(lemma, ensure_ascii=False)}, {json.dumps(pos, ensure_ascii=False)}, {json.dumps(tr_trans, ensure_ascii=False)}, {json.dumps(en_trans, ensure_ascii=False)}, {json.dumps(note, ensure_ascii=False)}),\n'
    content += "}\n"

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"✓ Written {len(CURATED_DE_MAP)} verified entries to {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
