# -*- coding: utf-8 -*-
"""
Comprehensive verified Spanish fallthrough translations,
lemmas, and parts of speech.
"""

ES_ADDITIONAL_FALLTHROUGH_MAP = {
    "aaron": ("Aaron", "Nombre Propio", "Aaron", "Aaron", "\"Aaron\" (özel isim — Aaron)"),
    "aficionados": ("aficionado", "Sustantivo / Adjetivo (Plural)", "meraklılar / tutkunlar", "enthusiasts / aficionados", "\"aficionados\" (tutkunlar — enthusiasts)"),
    "afinadas": ("afinado", "Adjetivo / Participio (Fem Plural)", "akort edilmiş / ince ayarlanmış", "tuned / refined", "\"afinadas\" (kök: afinar — akort edilmiş)"),
    "ahorrado": ("ahorrar", "Verbo (Participio)", "tasarruf edilmiş / biriktirilmiş", "saved", "\"ahorrado\" (kök: ahorrar — tasarruf edilmiş)"),
    "aislados": ("aislado", "Adjetivo / Participio (Plural)", "yalıtılmış / izole", "isolated", "\"aislados\" (kök: aislar — izole)"),
    "alineados": ("alineado", "Adjetivo / Participio (Plural)", "hizalanmış / sıralanmış", "aligned", "\"alineados\" (kök: alinear — hizalanmış)"),
    "apodada": ("apodar", "Verbo (Participio Fem)", "lakaplı / anılan", "nicknamed", "\"apodada\" (kök: apodar — lakaplı)"),
    "apurado": ("apurar", "Verbo (Participio) / Adjetivo", "acele / sıkışık", "rushed / hurried", "\"apurado\" (kök: apurar — acele)"),
    "arrancado": ("arrancar", "Verbo (Participio)", "sökülmüş / koparılmış", "torn off / plucked", "\"arrancado\" (kök: arrancar — koparılmış)"),
    "asediado": ("asediar", "Verbo (Participio)", "kuşatılmış", "besieged", "\"asediado\" (kök: asediar — kuşatılmış)"),
    "atados": ("atar", "Verbo (Participio Plural)", "bağlanmış", "tied / bound", "\"atados\" (kök: atar — bağlanmış)"),
    "aterciopelada": ("aterciopelado", "Adjetivo (Fem)", "kadifemsi / pürüzsüz", "velvety", "\"aterciopelada\" (kadifemsi — velvety)"),
    "atrancando": ("atrancar", "Verbo (Gerundio)", "sürgüleyerek / tıkayarak", "barring / bolting", "\"atrancando\" (kök: atrancar — sürgüleyerek)"),
    "atrapado": ("atrapar", "Verbo (Participio)", "yakalanmış / hapsolmuş", "trapped / caught", "\"atrapado\" (kök: atrapar — hapsolmuş)"),
    "ayuda": ("ayudar", "Verbo (Presente 3sg)", "yardım eder", "helps", "\"ayuda\" (kök: ayudar — yardım eder)"),
    "bocado": ("bocado", "Sustantivo (Masc)", "lokma / ısırık", "bite / mouthful", "\"bocado\" (lokma — bite)"),
    "bocados": ("bocado", "Sustantivo (Masc Plural)", "lokmalar", "bites / morsels", "\"bocados\" (lokmalar — bites)"),
    "bombardeado": ("bombardear", "Verbo (Participio)", "bombalanmış / yaylım ateşine tutulmuş", "bombarded", "\"bombardeado\" (kök: bombardear — bombalanmış)"),
    "brotadas": ("brotar", "Verbo (Participio Fem Plural)", "filizlenmiş / fışkırmış", "sprouted", "\"brotadas\" (kök: brotar — filizlenmiş)"),
    "buscando": ("buscar", "Verbo (Gerundio)", "arayarak / ararken", "seeking / searching", "\"buscando\" (kök: buscar — arayarak)"),
    "cableado": ("cableado", "Sustantivo (Masc)", "kablolama / nöral ağ", "wiring / circuitry", "\"cableado\" (nöral ağ — neural wiring)"),
    "calificado": ("calificar", "Verbo (Participio)", "nitelendirilmiş / tanımlanmış", "qualified / described", "\"calificado\" (kök: calificar — nitelendirilmiş)"),
    "caminando": ("caminar", "Verbo (Gerundio)", "yürüyerek / yürürken", "walking", "\"caminando\" (kök: caminar — yürüyerek)"),
    "cansado": ("cansar", "Verbo (Participio) / Adjetivo", "yorgun", "tired / weary", "\"cansado\" (yorgun — tired)"),
    "captadas": ("captar", "Verbo (Participio Fem Plural)", "yakalanmış / algılanmış", "captured / perceived", "\"captadas\" (kök: captar — algılanmış)"),
    "causados": ("causar", "Verbo (Participio Plural)", "neden olunan / kaynaklanan", "caused", "\"causados\" (kök: causar — neden olunan)"),
    "cerrados": ("cerrado", "Adjetivo / Participio (Plural)", "kapalı", "closed", "\"cerrados\" (kök: cerrar — kapalı)"),
    "cimentada": ("cimentar", "Verbo (Participio Fem)", "temellenmiş / sağlamlaştırılmış", "grounded / cemented", "\"cimentada\" (kök: cimentar — temellenmiş)"),
    "cocida": ("cocer", "Verbo (Participio Fem)", "pişmiş / kaynatılmış", "cooked / boiled", "\"cocida\" (kök: cocer — pişmiş)"),
    "cocina": ("cocinar", "Verbo (Presente 3sg) / Sustantivo", "pişirir / mutfak", "cooks / kitchen", "\"cocina\" (kök: cocinar — pişirir)"),
    "colgado": ("colgar", "Verbo (Participio)", "asılmış", "hung", "\"colgado\" (kök: colgar — asılmış)"),
    "coloreadas": ("colorear", "Verbo (Participio Fem Plural)", "renklendirilmiş / boyanmış", "colored", "\"coloreadas\" (kök: colorear — renklendirilmiş)"),
    "colorida": ("colorido", "Adjetivo (Fem)", "renkli / canlı", "colorful / vibrant", "\"colorida\" (renkli — colorful)"),
    "comida": ("comida", "Sustantivo (Fem)", "yemek / yiyecek", "food / meal", "\"comida\" (yemek — meal / food)"),
    "comienza": ("comenzar", "Verbo (Presente 3sg)", "başlar", "begins / starts", "\"comienza\" (kök: comenzar — başlar)"),
    "compartidas": ("compartir", "Verbo (Participio Fem Plural)", "paylaşılan", "shared", "\"compartidas\" (kök: compartir — paylaşılan)"),
    "comprometiendo": ("comprometer", "Verbo (Gerundio)", "tehlikeye atarak / bağlayarak", "compromising / committing", "\"comprometiendo\" (kök: comprometer — tehlikeye atarak)"),
    "concurridos": ("concurrido", "Adjektiv (Plural)", "kalabalık / işlek", "crowded / busy", "\"concurridos\" (kalabalık — busy)"),
    "confinada": ("confinar", "Verbo (Participio Fem)", "kapatılmış / sınırlandırılmış", "confined", "\"confinada\" (kök: confinar — sınırlandırılmış)"),
    "conmovido": ("conmover", "Verbo (Participio)", "duygulanmış / sarsılmış", "moved / touched", "\"conmovido\" (kök: conmover — duygulanmış)"),
    "conoce": ("conocer", "Verbo (Presente 3sg)", "tanır / bilir", "knows / recognizes", "\"conoce\" (kök: conocer — bilir / tanır)"),
    "conocida": ("conocer", "Verbo (Participio Fem)", "bilinen / tanınan", "known", "\"conocida\" (kök: conocer — tanınan)"),
    "conocido": ("conocer", "Verbo (Participio Masc)", "bilinen / tanınmış", "known / famous", "\"conocido\" (kök: conocer — tanınan)"),
    "conocidos": ("conocer", "Verbo (Participio Plural)", "tanınan / bilinen", "known", "\"conocidos\" (kök: conocer — tanınanlar)"),
    "consagrado": ("consagrar", "Verbo (Participio)", "adanmış / kutsanmış", "consecrated / devoted", "\"consagrado\" (kök: consagrar — adanmış)"),
    "conserva": ("conservar", "Verbo (Presente 3sg)", "korur / muhafaza eder", "preserves / retains", "\"conserva\" (kök: conservar — korur)"),
    "considerado": ("considerar", "Verbo (Participio)", "kabul edilen / sayılan", "considered / regarded", "\"considerado\" (kök: considerar — sayılan)"),
    "considerando": ("considerar", "Verbo (Gerundio)", "göz önüne alarak / sayarak", "considering", "\"considerando\" (kök: considerar — sayarak)"),
    "consumada": ("consumado", "Adjetivo (Fem)", "kusursuz / usta", "consummate / accomplished", "\"consumada\" (usta — consummate)"),
    "consumido": ("consumir", "Verbo (Participio)", "tüketilmiş", "consumed", "\"consumido\" (kök: consumir — tüketilmiş)"),
    "consumiendo": ("consumir", "Verbo (Gerundio)", "tüketerek", "consuming", "\"consumiendo\" (kök: consumir — tüketerek)"),
    "contrastados": ("contrastar", "Verbo (Participio Plural)", "karşılaştırılmış / tezat oluşturan", "contrasted", "\"contrastados\" (kök: contrastar — tezat oluşturan)"),
    "convocada": ("convocar", "Verbo (Participio Fem)", "çağrılmış / toplanmış", "summoned / convened", "\"convocada\" (kök: convocar — çağrılmış)"),
    "coordinado": ("coordinar", "Verbo (Participio)", "koordine edilmiş", "coordinated", "\"coordinado\" (kök: coordinar — koordine edilmiş)"),
    "cortado": ("cortar", "Verbo (Participio)", "kesilmiş / doğranmış", "cut / sliced", "\"cortado\" (kök: cortar — kesilmiş)"),
    "cribando": ("cribar", "Verbo (Gerundio)", "eleyerek / ayıklayarak", "sifting / filtering", "\"cribando\" (kök: cribar — eleyerek)"),
    "criticado": ("criticar", "Verbo (Participio)", "eleştirilmiş", "criticized", "\"criticado\" (kök: criticar — eleştirilmiş)"),
    "cuajados": ("cuajado", "Adjetivo / Participio (Plural)", "pıhtılaşmış / mayalanmış", "curdled / coagulated", "\"cuajados\" (kök: cuajar — pıhtılaşmış)"),
    "cucharada": ("cucharada", "Sustantivo (Fem)", "kaşık dolusu / yemek kaşığı", "tablespoon / spoonful", "\"cucharada\" (yemek kaşığı — spoonful)"),
    "cuidado": ("cuidado", "Sustantivo (Masc)", "özen / dikkat", "care / attention", "\"cuidado\" (özen — care)"),
    "cultivados": ("cultivar", "Verbo (Participio Plural)", "yetiştirilen / ekilen", "cultivated / grown", "\"cultivados\" (kök: cultivar — yetiştirilen)"),
    "curvado": ("curvado", "Adjetivo", "kıvrımlı / kavisli", "curved", "\"curvado\" (kıvrımlı — curved)"),
    "cálido": ("cálido", "Adjetivo", "ılık / sıcak", "warm", "\"cálido\" (ılık — warm)"),
    "dado": ("dar", "Verbo (Participio)", "verilmiş / göz önüne alındığında", "given", "\"dado\" (kök: dar — verilmiş)"),
    "deben": ("deber", "Verbo (Presente 3pl)", "zorundadırlar / -meliler", "must / should", "\"deben\" (kök: deber — zorundadırlar)"),
    "dejando": ("dejar", "Verbo (Gerundio)", "bırakarak", "leaving", "\"dejando\" (kök: dejar — bırakarak)"),
    "deliberada": ("deliberado", "Adjetivo (Fem)", "kasıtlı / bilinçli", "deliberate", "\"deliberada\" (kasıtlı — deliberate)"),
    "delicadas": ("delicado", "Adjetivo (Fem Plural)", "narin / hassas", "delicate", "\"delicadas\" (narin — delicate)"),
    "delicados": ("delicado", "Adjetivo (Masc Plural)", "narin / hassas", "delicate", "\"delicados\" (narin — delicate)"),
    "descansando": ("descansar", "Verbo (Gerundio)", "dinlenerek", "resting", "\"descansando\" (kök: descansar — dinlenerek)"),
    "descarada": ("descarado", "Adjetivo (Fem)", "küstah / açık sözlü", "brazen / outspoken", "\"descarada\" (açık sözlü — bold)"),
    "descubre": ("descubrir", "Verbo (Presente 3sg)", "keşfeder", "discovers", "\"descubre\" (kök: descubrir — keşfeder)"),
    "despertando": ("despertar", "Verbo (Gerundio)", "uyandırarak", "awakening / arousing", "\"despertando\" (kök: despertar — uyandırarak)"),
    "despiadada": ("despiadado", "Adjetivo (Fem)", "acımasız / merhametsiz", "ruthless / merciless", "\"despiadada\" (acımasız — ruthless)"),
    "destaca": ("destacar", "Verbo (Presente 3sg)", "öne çıkar / dikkat çeker", "stands out / highlights", "\"destaca\" (kök: destacar — öne çıkar)"),
    "destacados": ("destacado", "Adjetivo / Participio (Plural)", "seçkin / önde gelen", "prominent / outstanding", "\"destacados\" (kök: destacar — önde gelen)"),
    "destacando": ("destacar", "Verbo (Gerundio)", "vurgulayarak / öne çıkarak", "highlighting", "\"destacando\" (kök: destacar — vurgulayarak)"),
    "destinado": ("destinar", "Verbo (Participio)", "amaçlanan / ayrılmış", "destined / intended", "\"destinado\" (kök: destinar — ayrılmış)"),
    "detallada": ("detallado", "Adjetivo (Fem)", "ayrıntılı / detaylı", "detailed", "\"detallada\" (ayrıntılı — detailed)"),
    "divertidos": ("divertido", "Adjetivo (Plural)", "eğlenceli", "fun / amusing", "\"divertidos\" (eğlenceli — fun)"),
    "dividido": ("dividir", "Verbo (Participio)", "bölünmüş", "divided", "\"dividido\" (kök: dividir — bölünmüş)"),
    "doradas": ("dorado", "Adjetivo (Fem Plural)", "altın sarısı / yaldızlı", "golden / gilded", "\"doradas\" (altın sarısı — golden)"),
    "dorado": ("dorado", "Adjetivo / Sustantivo", "altın yaldızlı / altın tozu", "golden / gilt", "\"dorado\" (altın yaldızlı — golden)"),
    "dormidas": ("dormido", "Adjetivo / Participio (Fem Plural)", "uyuyan / uyumuş", "asleep", "\"dormidas\" (kök: dormir — uyuyan)"),
    "dormidos": ("dormido", "Adjetivo / Participio (Masc Plural)", "uyuyanlar / uyumuş", "asleep", "\"dormidos\" (kök: dormir — uyuyanlar)"),
    "dosificada": ("dosificar", "Verbo (Participio Fem)", "dozajlanmış / ölçülü", "dosed / metered", "\"dosificada\" (kök: dosificar — ölçülü)"),
    "décadas": ("década", "Sustantivo (Fem Plural)", "on yıllar", "decades", "\"décadas\" (on yıllar — decades)"),
    "elogiando": ("elogiar", "Verbo (Gerundio)", "överek", "praising", "\"elogiando\" (kök: elogiar — överek)"),
    "empanadas": ("empanada", "Sustantivo (Fem Plural)", "empanadalar (hamur işi)", "empanadas (pastries)", "\"empanadas\" (hamur işi — empanadas)"),
    "empañadas": ("empañar", "Verbo (Participio Fem Plural)", "buğulanmış / gölgelenmiş", "tarnished / clouded", "\"empañadas\" (kök: empañar — gölgelenmiş)"),
    "empeñada": ("empeñar", "Verbo (Participio Fem)", "kararlı / azimli", "determined", "\"empeñada\" (kök: empeñar — kararlı)"),
    "empinadas": ("empinado", "Adjetivo (Fem Plural)", "dik / sarp", "steep", "\"empinadas\" (sarp — steep)"),
    "empleados": ("empleado", "Sustantivo (Plural)", "çalışanlar / görevliler", "employees", "\"empleados\" (çalışanlar — employees)"),
    "emprendidas": ("emprender", "Verbo (Participio Fem Plural)", "başlatılan / çıkılan (sefer)", "undertaken / embarked upon", "\"emprendidas\" (kök: emprender — çıkılan)"),
    "encargada": ("encargar", "Verbo (Participio Fem)", "görevlendirilmiş / sorumlu", "in charge / commissioned", "\"encargada\" (kök: encargar — sorumlu)"),
    "ensanchado": ("ensanchar", "Verbo (Participio)", "genişletilmiş", "widened / expanded", "\"ensanchado\" (kök: ensanchar — genişletilmiş)"),
    "enseña": ("enseñar", "Verbo (Presente 3sg)", "öğretir / gösterir", "teaches / shows", "\"enseña\" (kök: enseñar — öğretir)"),
    "entablado": ("entablar", "Verbo (Participio)", "başlatılmış / kurulmuş", "established / engaged in", "\"entablado\" (kök: entablar — başlatılmış)"),
    "enterrados": ("enterrar", "Verbo (Participio Plural)", "gömülü / gömülmüş", "buried", "\"enterrados\" (kök: enterrar — gömülü)"),
    "entrada": ("entrada", "Sustantivo (Fem)", "giriş", "entrance", "\"entrada\" (giriş — entrance)"),
    "entradas": ("entrada", "Sustantivo (Fem Plural)", "girişler", "entrances", "\"entradas\" (girişler — entrances)"),
    "equilibrados": ("equilibrado", "Adjetivo (Plural)", "dengeli", "balanced", "\"equilibrados\" (dengeli — balanced)"),
    "erguido": ("erguir", "Verbo (Participio)", "dikilmiş / dik duran", "erect / upright", "\"erguido\" (kök: erguir — dik duran)"),
    "erigido": ("erigir", "Verbo (Participio)", "dikilmiş / inşa edilmiş", "erected / built", "\"erigido\" (kök: erigir — dikilmiş)"),
    "esculpido": ("esculpir", "Verbo (Participio)", "yontulmuş / heykeli yapılmış", "sculpted / carved", "\"esculpido\" (kök: esculpir — yontulmuş)"),
    "especializados": ("especializado", "Adjetivo (Plural)", "uzmanlaşmış", "specialized", "\"especializados\" (uzmanlaşmış — specialized)"),
    "espesada": ("espesar", "Verbo (Participio Fem)", "koyulaştırılmış / kıvamlı", "thickened", "\"espesada\" (kök: espesar — koyulaştırılmış)"),
    "espesando": ("espesar", "Verbo (Gerundio)", "koyulaşarak / kıvam alarak", "thickening", "\"espesando\" (kök: espesar — koyulaşarak)"),
    "estilizada": ("estilizado", "Adjetivo (Fem)", "stilize edilmiş", "stylized", "\"estilizada\" (stilize — stylized)"),
    "estructurada": ("estructurado", "Adjetivo (Fem)", "yapılandırılmış", "structured", "\"estructurada\" (yapılandırılmış — structured)"),
    "exhumados": ("exhumar", "Verbo (Participio Plural)", "topraktan çıkarılmış", "exhumed / unburied", "\"exhumados\" (kök: exhumar — çıkarılmış)"),
    "explica": ("explicar", "Verbo (Presente 3sg)", "açıklar / izah eder", "explains", "\"explica\" (kök: explicar — açıklar)"),
    "facultando": ("facultar", "Verbo (Gerundio)", "yetki vererek / olanak tanıyarak", "empowering / enabling", "\"facultando\" (kök: facultar — olanak tanıyarak)"),
    "fermentada": ("fermentar", "Verbo (Participio Fem)", "fermente / mayalanmış", "fermented", "\"fermentada\" (kök: fermentar — fermente)"),
    "fermentado": ("fermentar", "Verbo (Participio Masc)", "mayalanmış / fermente", "fermented", "\"fermentado\" (kök: fermentar — mayalanmış)"),
    "fermentados": ("fermentar", "Verbo (Participio Plural)", "fermente edilmiş", "fermented", "\"fermentados\" (kök: fermentar — fermente)"),
    "filtrado": ("filtrar", "Verbo (Participio)", "filtrelenmiş / süzülmüş", "filtered", "\"filtrado\" (kök: filtrar — filtrelenmiş)"),
    "fluidos": ("fluido", "Sustantivo (Masc Plural)", "sıvılar / akışkanlar", "fluids", "\"fluidos\" (akışkanlar — fluids)"),
    "forjada": ("forjar", "Verbo (Participio Fem)", "dövülmüş / şekillendirilmiş", "forged", "\"forjada\" (kök: forjar — dövülmüş)"),
    "forzados": ("forzar", "Verbo (Participio Plural)", "zorlanmış / mecbur bırakılmış", "forced", "\"forzados\" (kök: forzar — mecbur bırakılmış)"),
    "galardonado": ("galardonar", "Verbo (Participio)", "ödüllendirilmiş / ödüllü", "awarded / prizewinning", "\"galardonado\" (kök: galardonar — ödüllü)"),
    "ganado": ("ganar", "Verbo (Participio) / Sustantivo", "kazanılmış / sığır", "won / livestock", "\"ganado\" (kök: ganar — kazanılmış)"),
    "gastados": ("gastar", "Verbo (Participio Plural)", "yıpranmış / harcanmış", "worn out / spent", "\"gastados\" (kök: gastar — yıpranmış)"),
    "grabados": ("grabar", "Verbo (Participio Plural) / Sustantivo", "kazınmış / gravürler", "engraved / engravings", "\"grabados\" (kök: grabar — kazınmış)"),
    "guiando": ("guiar", "Verbo (Gerundio)", "rehberlik ederek / yol göstererek", "guiding", "\"guiando\" (kök: guiar — rehberlik ederek)"),
    "habitado": ("habitar", "Verbo (Participio)", "yerleşilmiş / ikamet edilmiş", "inhabited", "\"habitado\" (kök: habitar — yerleşilmiş)"),
    "hace": ("hacer", "Verbo (Presente 3sg)", "yapar / eder", "makes / does", "\"hace\" (kök: hacer — yapar)"),
    "hacen": ("hacer", "Verbo (Presente 3pl)", "yaparlar / ederler", "they make / do", "\"hacen\" (kök: hacer — yaparlar)"),
    "hacer": ("hacer", "Verbo (Infinitivo)", "yapmak / etmek", "to make / do", "\"hacer\" (yapmak — to make / do)"),
    "hadas": ("hada", "Sustantivo (Fem Plural)", "periler", "fairies", "\"hadas\" (periler — fairy chimneys / peribacaları)"),
    "halladas": ("hallar", "Verbo (Participio Fem Plural)", "bulunan / keşfedilen", "found / discovered", "\"halladas\" (kök: hallar — bulunan)"),
    "heredados": ("heredar", "Verbo (Participio Plural)", "miras kalan / devralınan", "inherited", "\"heredados\" (kök: heredar — miras kalan)"),
    "herida": ("herida", "Sustantivo (Fem) / Participio", "yara / yaralanmış", "wound / injured", "\"herida\" (yara — wound)"),
    "heridas": ("herida", "Sustantivo (Fem Plural)", "yaralar", "wounds", "\"heridas\" (yaralar — wounds)"),
    "herido": ("herir", "Verbo (Participio)", "yaralanmış / yaralı", "wounded / hurt", "\"herido\" (kök: herir — yaralı)"),
    "homogeneizados": ("homogeneizar", "Verbo (Participio Plural)", "homojenleştirilmiş", "homogenized", "\"homogeneizados\" (kök: homogeneizar — homojenleştirilmiş)"),
    "horneado": ("hornear", "Verbo (Participio)", "fırınlanmış / pişirilmiş", "baked", "\"horneado\" (kök: hornear — fırınlanmış)"),
    "iluminando": ("iluminar", "Verbo (Gerundio)", "aydınlatırken / aydınlatarak", "illuminating", "\"iluminando\" (kök: iluminar — aydınlatarak)"),
    "ilíada": ("Ilíada", "Nombre Propio", "İlyada", "Iliad", "\"Ilíada\" (İlyada destanı — Iliad)"),
    "inadvertida": ("inadvertido", "Adjetivo (Fem)", "fark edilmeyen / gözden kaçan", "unnoticed", "\"inadvertida\" (fark edilmeyen — unnoticed)"),
    "ininterrumpido": ("ininterrumpido", "Adjetivo", "kesintisiz / aralıksız", "uninterrupted", "\"ininterrumpido\" (kesintisiz — uninterrupted)"),
    "intenta": ("intentar", "Verbo (Presente 3sg)", "dener / çabalar", "tries / attempts", "\"intenta\" (kök: intentar — çabalar)"),
    "interconectada": ("interconectar", "Verbo (Participio Fem)", "birbirine bağlı", "interconnected", "\"interconectada\" (kök: interconectar — birbirine bağlı)"),
    "interconectados": ("interconectar", "Verbo (Participio Plural)", "birbirine bağlanmış", "interconnected", "\"interconectados\" (kök: interconectar — birbirine bağlı)"),
    "invertido": ("invertir", "Verbo (Participio)", "ters çevrilmiş / yatırılmış", "inverted / invested", "\"invertido\" (kök: invertir — ters çevrilmiş)"),
    "invitados": ("invitado", "Sustantivo / Participio (Plural)", "davetliler / misafirler", "guests / invited", "\"invitados\" (misafirler — guests)"),
    "invitando": ("invitar", "Verbo (Gerundio)", "davet ederek", "inviting", "\"invitando\" (kök: invitar — davet ederek)"),
    "jornada": ("jornada", "Sustantivo (Fem)", "gün / mesai / sefer", "day / journey", "\"jornada\" (gün / yolculuk — journey)"),
    "lado": ("lado", "Sustantivo (Masc)", "yan / taraf", "side", "\"lado\" (taraf — side)"),
    "legado": ("legado", "Sustantivo (Masc)", "miras / kültürel miras", "legacy / heritage", "\"legado\" (miras — legacy)"),
    "levantados": ("levantar", "Verbo (Participio Plural)", "kaldırılmış / dikilmiş", "raised / erected", "\"levantados\" (kök: levantar — dikilmiş)"),
    "liderados": ("liderar", "Verbo (Participio Plural)", "önderlik edilen", "led", "\"liderados\" (kök: liderar — önderliğinde)"),
    "limitado": ("limitar", "Verbo (Participio) / Adjetivo", "sınırlı / kısıtlı", "limited", "\"limitado\" (kök: limitar — sınırlı)"),
    "llama": ("llamar", "Verbo (Presente 3sg)", "çağırır / adlandırır", "calls / names", "\"llama\" (kök: llamar — adlandırır)"),
    "llamada": ("llamar", "Verbo (Participio Fem)", "adlandırılan / denilen", "called / named", "\"llamada\" (kök: llamar — denilen)"),
    "llamadas": ("llamar", "Verbo (Participio Fem Plural)", "denilen / adlandırılan", "called", "\"llamadas\" (kök: llamar — adlandırılanlar)"),
    "llamado": ("llamar", "Verbo (Participio Masc)", "denilen / adlandırılan", "called / named", "\"llamado\" (kök: llamar — adlandırılan)"),
    "llamados": ("llamar", "Verbo (Participio Plural)", "adlandırılan / denilen", "called / named", "\"llamados\" (kök: llamar — adı verilenler)"),
    "llevada": ("llevar", "Verbo (Participio Fem)", "götürülmüş / taşınmış", "carried / taken", "\"llevada\" (kök: llevar — taşınmış)"),
    "llevado": ("llevar", "Verbo (Participio Masc)", "taşınmış / götürülmüş", "carried / taken", "\"llevado\" (kök: llevar — götürülmüş)"),
    "llevando": ("llevar", "Verbo (Gerundio)", "taşıyarak / götürerek", "carrying / taking", "\"llevando\" (kök: llevar — taşıyarak)"),
    "líquido": ("líquido", "Sustantivo / Adjetivo", "sıvı", "liquid", "\"líquido\" (sıvı — liquid)"),
    "lúcida": ("lúcido", "Adjetivo (Fem)", "berrak / aklı başında", "lucid / clear", "\"lúcida\" (berrak — lucid)"),
    "maleducadas": ("maleducado", "Adjetivo (Fem Plural)", "kaba / terbiyesiz", "rude / ill-mannered", "\"maleducadas\" (kaba — ill-mannered)"),
    "mando": ("mando", "Sustantivo (Masc)", "komuta / kontrol", "command / control", "\"mando\" (komuta — command)"),
    "mantiene": ("mantener", "Verbo (Presente 3sg)", "korur / muhafaza eder", "maintains / keeps", "\"mantiene\" (kök: mantener — korur)"),
    "marmoleado": ("marmolear", "Verbo (Participio) / Adjetivo", "mermer desenli (ebru)", "marbled", "\"marmoleado\" (mermer desenli — marbled)"),
    "mediados": ("mediados", "Sustantivo Plural (Locución)", "ortaları (yüzyıl vb.)", "middle / mid", "\"mediados\" (ortaları — mid: a mediados de)"),
    "medida": ("medida", "Sustantivo (Fem)", "ölçü / önlem", "measure", "\"medida\" (ölçü — measure)"),
    "mencionadas": ("mencionar", "Verbo (Participio Fem Plural)", "bahsedilen / anılan", "mentioned", "\"mencionadas\" (kök: mencionar — bahsedilen)"),
    "mercados": ("mercado", "Sustantivo (Plural)", "pazarlar / piyasalar", "markets", "\"mercados\" (pazarlar — markets)"),
    "mezcla": ("mezclar", "Verbo (Presente 3sg) / Sustantivo", "karıştırır / karışım", "mixes / mixture", "\"mezcla\" (kök: mezclar — karıştırır)"),
    "mezclada": ("mezclar", "Verbo (Participio Fem)", "karıştırılmış", "mixed / blended", "\"mezclada\" (kök: mezclar — karıştırılmış)"),
    "mirada": ("mirada", "Sustantivo (Fem)", "bakış / nazar", "gaze / look", "\"mirada\" (bakış — gaze)"),
    "modulados": ("modular", "Verbo (Participio Plural)", "ayarlanmış / modüle edilmiş", "modulated", "\"modulados\" (kök: modular — ayarlanmış)"),
    "mojada": ("mojado", "Adjetivo / Participio (Fem)", "ıslak / ıslatılmış", "wet / soaked", "\"mojada\" (ıslak — wet)"),
    "mudando": ("mudar", "Verbo (Gerundio)", "değiştirerek / taşınarak", "moving / shedding", "\"mudando\" (kök: mudar — değiştirerek)"),
    "muestra": ("mostrar", "Verbo (Presente 3sg)", "gösterir / sergiler", "shows / displays", "\"muestra\" (kök: mostrar — sergiler / gösterir)"),
    "nacido": ("nacer", "Verbo (Participio)", "doğmuş", "born", "\"nacido\" (kök: nacer — doğmuş)"),
    "narrada": ("narrar", "Verbo (Participio Fem)", "anlatılan / rivayet edilen", "narrated", "\"narrada\" (kök: narrar — anlatılan)"),
    "nutridas": ("nutrido", "Adjetivo (Fem Plural)", "beslenen / zengin", "nourished / copious", "\"nutridas\" (zengin / beslenen — nourished)"),
    "nítido": ("nítido", "Adjetivo", "net / berrak", "clear / sharp", "\"nítido\" (net — clear)"),
    "nómadas": ("nómada", "Sustantivo / Adjetivo (Plural)", "göçebeler", "nomads", "\"nómadas\" (göçebeler — nomads)"),
    "obligando": ("obligar", "Verbo (Gerundio)", "zorlayarak / mecbur bırakarak", "forcing / compelling", "\"obligando\" (kök: obligar — mecbur bırakarak)"),
    "ofrece": ("ofrecer", "Verbo (Presente 3sg)", "sunar / takdim eder", "offers / presents", "\"ofrece\" (kök: ofrecer — sunar)"),
    "olvida": ("olvidar", "Verbo (Presente 3sg)", "unutur", "forgets", "\"olvida\" (kök: olvidar — unutur)"),
    "olvidado": ("olvidar", "Verbo (Participio)", "unutulmuş", "forgotten", "\"olvidado\" (kök: olvidar — unutulmuş)"),
    "olvidados": ("olvidar", "Verbo (Participio Plural)", "unutulmuşlar", "forgotten", "\"olvidados\" (kök: olvidar — unutulmuş)"),
    "organizada": ("organizar", "Verbo (Participio Fem)", "düzenlenmiş / organize", "organized", "\"organizada\" (kök: organizar — düzenlenmiş)"),
    "originado": ("originar", "Verbo (Participio)", "kaynaklanan / doğan", "originated / stemmed", "\"originado\" (kök: originar — kaynaklanan)"),
    "ornamentado": ("ornamentar", "Verbo (Participio)", "süslenmiş / bezeli", "ornamented", "\"ornamentado\" (kök: ornamentar — bezeli)"),
    "partida": ("partida", "Sustantivo (Fem)", "ayrılış / kalkış / parti", "departure / match", "\"partida\" (ayrılış — departure: punto de partida)"),
    "pasado": ("pasado", "Sustantivo / Participio", "geçmiş", "past", "\"pasado\" (geçmiş — past)"),
    "paseando": ("pasear", "Verbo (Gerundio)", "gezinirken / dolaşarak", "strolling / walking", "\"paseando\" (kök: pasear — dolaşarak)"),
    "pausado": ("pausado", "Adjetivo", "aheste / yavaş tempolu", "deliberate / unhurried", "\"pausado\" (aheste — unhurried)"),
    "permite": ("permitir", "Verbo (Presente 3sg)", "olanak tanır / sağlar", "allows / enables", "\"permite\" (kök: permitir — olanak tanır)"),
    "pesada": ("pesado", "Adjetivo (Fem)", "ağır", "heavy", "\"pesada\" (ağır — heavy)"),
    "pesadas": ("pesado", "Adjetivo (Fem Plural)", "ağır", "heavy", "\"pesadas\" (ağır — heavy)"),
    "pesticidas": ("pesticida", "Sustantivo (Plural)", "tarım ilaçları / pestisitler", "pesticides", "\"pesticidas\" (pestisitler — pesticides)"),
    "picado": ("picar", "Verbo (Participio)", "kıyılmış / doğranmış", "minced / chopped", "\"picado\" (kök: picar — kıyılmış)"),
    "pintado": ("pintar", "Verbo (Participio)", "boyanmış / resmi yapılmış", "painted", "\"pintado\" (kök: pintar — boyanmış)"),
    "planteada": ("plantear", "Verbo (Participio Fem)", "ortaya atılan / ileri sürülen", "posited / put forward", "\"planteada\" (kök: plantear — ileri sürülen)"),
    "popularizada": ("popularizar", "Verbo (Participio Fem)", "popülerleştirilmiş / yaygınlaştırılmış", "popularized", "\"popularizada\" (kök: popularizar — yaygınlaştırılmış)"),
    "posada": ("posada", "Sustantivo (Fem)", "han / kervansaray", "inn", "\"posada\" (han — inn)"),
    "precipitados": ("precipitado", "Adjetivo (Plural)", "aceleci / fevri", "hasty / rushed", "\"precipitados\" (aceleci — rushed)"),
    "prepara": ("preparar", "Verbo (Presente 3sg)", "hazırlar", "prepares", "\"prepara\" (kök: preparar — hazırlar)"),
    "preparada": ("preparar", "Verbo (Participio Fem)", "hazırlanmış", "prepared", "\"preparada\" (kök: preparar — hazırlanmış)"),
    "presentados": ("presentar", "Verbo (Participio Plural)", "sunulan", "presented", "\"presentados\" (kök: presentar — sunulan)"),
    "privado": ("privado", "Adjetivo", "özel / mahrem", "private", "\"privado\" (özel — private)"),
    "prolongados": ("prolongado", "Adjetivo (Plural)", "uzun süreli / uzatılmış", "prolonged", "\"prolongados\" (uzun süreli — prolonged)"),
    "propiciada": ("propiciar", "Verbo (Participio Fem)", "sağlanan / teşvik edilen", "facilitated / fostered", "\"propiciada\" (kök: propiciar — sağlanan)"),
    "puede": ("poder", "Verbo (Presente 3sg)", "-ebilir (yeterlilik)", "can / is able to", "\"puede\" (kök: poder — -ebilir)"),
    "pueden": ("poder", "Verbo (Presente 3pl)", "-ebilirler (yeterlilik)", "can / are able to", "\"pueden\" (kök: poder — -ebilirler)"),
    "purificado": ("purificar", "Verbo (Participio)", "arındırılmış / saflaştırılmış", "purified", "\"purificado\" (kök: purificar — arındırılmış)"),
    "párpados": ("párpado", "Sustantivo (Masc Plural)", "göz kapakları", "eyelids", "\"párpados\" (göz kapakları — eyelids)"),
    "pérdida": ("pérdida", "Sustantivo (Fem)", "kayıp", "loss", "\"pérdida\" (kayıp — loss)"),
    "querido": ("querer", "Verbo (Participio) / Adjetivo", "sevgili / sevilen", "beloved / dear", "\"querido\" (sevilen — beloved)"),
    "ratificada": ("ratificar", "Verbo (Participio Fem)", "onaylanmış / teyit edilmiş", "ratified / confirmed", "\"ratificada\" (kök: ratificar — onaylanmış)"),
    "recargada": ("recargar", "Verbo (Participio Fem)", "aşırı süslü / aşırı yüklü", "overloaded / baroque", "\"recargada\" (kök: recargar — aşırı süslü)"),
    "recibe": ("recibir", "Verbo (Presente 3sg)", "alır / kabul eder", "receives", "\"recibe\" (kök: recibir — alır)"),
    "recordado": ("recordar", "Verbo (Participio)", "hatırlanan / anılan", "remembered", "\"recordado\" (kök: recordar — hatırlanan)"),
    "recortadas": ("recortar", "Verbo (Participio Fem Plural)", "kesilip çıkarılmış", "cut out", "\"recortadas\" (kök: recortar — kesilmiş)"),
    "recuerda": ("recordar", "Verbo (Presente 3sg)", "hatırlatır / hatırlar", "reminds / remembers", "\"recuerda\" (kök: recordar — hatırlatır)"),
    "reducido": ("reducir", "Verbo (Participio)", "azaltılmış / ufak", "reduced / small", "\"reducido\" (kök: reducir — azaltılmış)"),
    "refinado": ("refinar", "Verbo (Participio)", "rafine / arıtılmış", "refined", "\"refinado\" (kök: refinar — rafine)"),
    "refleja": ("reflejar", "Verbo (Presente 3sg)", "yansıtır", "reflects", "\"refleja\" (kök: reflejar — yansıtır)"),
    "reflejando": ("reflejar", "Verbo (Gerundio)", "yansıtarak", "reflecting", "\"reflejando\" (kök: reflejar — yansıtarak)"),
    "refugiadas": ("refugiar", "Verbo (Participio Fem Plural)", "sığınan", "sheltered / taking refuge", "\"refugiadas\" (kök: refugiar — sığınan)"),
    "refundado": ("refundar", "Verbo (Participio)", "yeniden kurulmuş", "refounded", "\"refundado\" (kök: refundar — yeniden kurulmuş)"),
    "relajada": ("relajado", "Adjetivo (Fem)", "rahat / gevşemiş", "relaxed", "\"relajada\" (rahat — relaxed)"),
    "renovada": ("renovar", "Verbo (Participio Fem)", "yenilenmiş", "renewed", "\"renovada\" (kök: renovar — yenilenmiş)"),
    "reparados": ("reparar", "Verbo (Participio Plural)", "onarılmış / tamir edilmiş", "repaired", "\"reparados\" (kök: reparar — onarılmış)"),
    "representa": ("representar", "Verbo (Presente 3sg)", "temsil eder", "represents", "\"representa\" (kök: representar — temsil eder)"),
    "representado": ("representar", "Verbo (Participio)", "temsil edilmiş", "represented", "\"representado\" (kök: representar — temsil edilmiş)"),
    "resistiendo": ("resistir", "Verbo (Gerundio)", "direnerek", "resisting", "\"resistiendo\" (kök: resistir — direnerek)"),
    "respetado": ("respetar", "Verbo (Participio)", "saygı duyulan", "respected", "\"respetado\" (kök: respetar — saygı duyulan)"),
    "restaurado": ("restaurar", "Verbo (Participio)", "restore edilmiş / onarılmış", "restored", "\"restaurado\" (kök: restaurar — restore edilmiş)"),
    "reveladas": ("revelar", "Verbo (Participio Fem Plural)", "ortaya çıkarılan / açıklanan", "revealed", "\"reveladas\" (kök: revelar — ortaya çıkarılan)"),
    "ruidos": ("ruido", "Sustantivo (Masc Plural)", "sesler / gürültüler", "noises", "\"ruidos\" (gürültüler — noises)"),
    "rápida": ("rápido", "Adjetivo (Fem)", "hızlı", "fast / quick", "\"rápida\" (hızlı — fast)"),
    "rápido": ("rápido", "Adjetivo / Adverbio", "hızlı / hızla", "fast / quickly", "\"rápido\" (hızlı — fast)"),
    "sacando": ("sacar", "Verbo (Gerundio)", "çıkararak", "taking out", "\"sacando\" (kök: sacar — çıkararak)"),
    "sacrificada": ("sacrificar", "Verbo (Participio Fem)", "feda edilen / kurban edilen", "sacrificed", "\"sacrificada\" (kök: sacrificar — feda edilen)"),
    "sagrado": ("sagrado", "Adjetivo", "kutsal", "sacred", "\"sagrado\" (kutsal — sacred)"),
    "salidas": ("salida", "Sustantivo (Fem Plural)", "çıkışlar / bacalar", "exits / vents", "\"salidas\" (çıkışlar — exits)"),
    "salpicando": ("salpicar", "Verbo (Gerundio)", "sıçratarak / damlatarak", "splattering / splashing", "\"salpicando\" (kök: salpicar — sıçratarak)"),
    "saturadas": ("saturado", "Adjetivo (Fem Plural)", "doymuş (yağlar)", "saturated", "\"saturadas\" (doymuş — saturated)"),
    "seguido": ("seguir", "Verbo (Participio)", "takip edilen / ardı ardına", "followed / continuous", "\"seguido\" (kök: seguir — takip edilen)"),
    "seleccionados": ("seleccionar", "Verbo (Participio Plural)", "seçilmiş", "selected", "\"seleccionados\" (kök: seleccionar — seçilmiş)"),
    "sellado": ("sellar", "Verbo (Participio)", "mühürlenmiş", "sealed", "\"sellado\" (kök: sellar — mühürlenmiş)"),
    "sentidas": ("sentido", "Adjetivo (Fem Plural)", "içten / derinden hissedilen", "heartfelt / felt", "\"sentidas\" (kök: sentir — içten)"),
    "sentido": ("sentido", "Sustantivo (Masc) / Participio", "anlam / his", "meaning / sense", "\"sentido\" (anlam — sense / meaning)"),
    "servido": ("servir", "Verbo (Participio)", "servis edilmiş / sunulmuş", "served", "\"servido\" (kök: servir — sunulmuş)"),
    "señaladas": ("señalar", "Verbo (Participio Fem Plural)", "işaret edilen / gösterilen", "indicated / marked", "\"señaladas\" (kök: señalar — işaret edilen)"),
    "significado": ("significado", "Sustantivo (Masc)", "anlam", "meaning", "\"significado\" (anlam — meaning)"),
    "simboliza": ("simbolizar", "Verbo (Presente 3sg)", "simgeler / sembolize eder", "symbolizes", "\"simboliza\" (kök: simbolizar — simgeler)"),
    "sirve": ("servir", "Verbo (Presente 3sg)", "hizmet eder / yarar", "serves", "\"sirve\" (kök: servir — hizmet eder)"),
    "situada": ("situar", "Verbo (Participio Fem)", "bulunan / yer alan", "situated / located", "\"situada\" (kök: situar — yer alan)"),
    "situado": ("situar", "Verbo (Participio Masc)", "bulunan / yer alan", "situated / located", "\"situado\" (kök: situar — bulunan)"),
    "sosegada": ("sosegado", "Adjetivo (Fem)", "dingin / sakin", "peaceful / calm", "\"sosegada\" (dingin — calm)"),
    "sosegado": ("sosegado", "Adjetivo (Masc)", "dingin / sakin", "serene / calm", "\"sosegado\" (dingin — serene)"),
    "supermercado": ("supermercado", "Sustantivo (Masc)", "süpermarket", "supermarket", "\"supermercado\" (süpermarket — supermarket)"),
    "suspendiendo": ("suspender", "Verbo (Gerundio)", "askıya alarak / durdurarak", "suspending", "\"suspendiendo\" (kök: suspender — askıya alarak)"),
    "susurradas": ("susurrar", "Verbo (Participio Fem Plural)", "fısıldanan", "whispered", "\"susurradas\" (kök: susurrar — fısıldanan)"),
    "talladas": ("tallar", "Verbo (Participio Fem Plural)", "oyulmuş / yontulmuş", "carved", "\"talladas\" (kök: tallar — oyulmuş)"),
    "tallados": ("tallar", "Verbo (Participio Masc Plural)", "yontulmuş / oyulmuş", "carved", "\"tallados\" (kök: tallar — yontulmuş)"),
    "tejado": ("tejado", "Sustantivo (Masc)", "çatı", "roof", "\"tejado\" (çatı — roof)"),
    "temperado": ("temperar", "Verbo (Participio)", "ılıtılmış / terbiye edilmiş", "tempered", "\"temperado\" (kök: temperar — ılıtılmış)"),
    "temporada": ("temporada", "Sustantivo (Fem)", "mevsim / sezon", "season", "\"temporada\" (sezon — season)"),
    "tener": ("tener", "Verbo (Infinitivo)", "sahip olmak", "to have", "\"tener\" (sahip olmak — to have)"),
    "teñidas": ("teñir", "Verbo (Participio Fem Plural)", "boyanmış", "dyed / stained", "\"teñidas\" (kök: teñir — boyanmış)"),
    "tiene": ("tener", "Verbo (Presente 3sg)", "sahiptir / var", "has", "\"tiene\" (kök: tener — sahiptir)"),
    "tienen": ("tener", "Verbo (Presente 3pl)", "sahiptirler / var", "they have", "\"tienen\" (kök: tener — sahiptirler)"),
    "tocando": ("tocar", "Verbo (Gerundio)", "dokunarak / çalarak (enstrüman)", "playing / touching", "\"tocando\" (kök: tocar — çalarak)"),
    "toneladas": ("tonelada", "Sustantivo (Fem Plural)", "tonlarca / ton", "tons", "\"toneladas\" (tonlar — tons)"),
    "transfiriendo": ("transferir", "Verbo (Gerundio)", "aktarırken / aktararak", "transferring", "\"transfiriendo\" (kök: transferir — aktararak)"),
    "transforma": ("transformar", "Verbo (Presente 3sg)", "dönüştürür", "transforms", "\"transforma\" (kök: transformar — dönüştürür)"),
    "transitadas": ("transitar", "Verbo (Participio Fem Plural)", "üzerinden geçilen / işlek", "traveled / frequented", "\"transitadas\" (kök: transitar — işlek)"),
    "transmitido": ("transmitir", "Verbo (Participio)", "aktarılmış / iletilmiş", "transmitted", "\"transmitido\" (kök: transmitir — aktarılmış)"),
    "transmitiendo": ("transmitir", "Verbo (Gerundio)", "aktararak / ileterek", "transmitting", "\"transmitiendo\" (kök: transmitir — aktararak)"),
    "transportados": ("transportar", "Verbo (Participio Plural)", "taşınan", "transported", "\"transportados\" (kök: transportar — taşınan)"),
    "transportando": ("transportar", "Verbo (Gerundio)", "taşıyarak", "transporting", "\"transportando\" (kök: transportar — taşıyarak)"),
    "trasladando": ("trasladar", "Verbo (Gerundio)", "taşıyarak / naklederek", "moving / transferring", "\"trasladando\" (kök: trasladar — taşıyarak)"),
    "tratados": ("tratar", "Verbo (Participio Plural) / Sustantivo", "muamele edilmiş / antlaşmalar", "treated / treaties", "\"tratados\" (kök: tratar — işlenmiş)"),
    "truncados": ("truncar", "Verbo (Participio Plural)", "yarım kalmış / kesintiye uğramış", "truncated / cut short", "\"truncados\" (kök: truncar — yarım kalmış)"),
    "usando": ("usar", "Verbo (Gerundio)", "kullanarak", "using", "\"usando\" (kök: usar — kullanarak)"),
    "van": ("ir", "Verbo (Presente 3pl)", "giderler", "they go", "\"van\" (kök: ir — giderler)"),
    "variados": ("variado", "Adjetivo (Plural)", "çeşitli / muhtelif", "varied", "\"variados\" (çeşitli — varied)"),
    "visitada": ("visitar", "Verbo (Participio Fem)", "ziyaret edilen", "visited", "\"visitada\" (kök: visitar — ziyaret edilen)"),
    "vívida": ("vívido", "Adjetivo (Fem)", "canlı / parlak", "vivid", "\"vívida\" (canlı — vivid)"),
    "ácido": ("ácido", "Sustantivo / Adjetivo", "asit / ekşi", "acid", "\"ácido\" (asit — acid)"),
    "ácidos": ("ácido", "Sustantivo (Masc Plural)", "asitler", "acids", "\"ácidos\" (asitler — acids)"),
    "áridas": ("árido", "Adjetivo (Fem Plural)", "kurak / çorak", "arid / barren", "\"áridas\" (kurak — arid)"),
}
