# -*- coding: utf-8 -*-
"""
Curated linguistic lexicon data for Spanish token gloss generation.
Covers all verbs, nouns, adjectives, pronouns, and function words across Leenardo articles.
"""

# Format: "lowercase_token": (lemma, pos, en_gloss, tr_gloss, note)
ES_CURATED_MAP = {
    # Words from user screenshots and Gobeklitepe / Steve Jobs stories
    "levantó": ("levantar", "Verbo (Pretérito Indefinido)", "raised / built / erected", "dikti / ayağa kaldırdı / inşa etti", "levantar (geçmiş zaman 3. tekil)"),
    "levantaron": ("levantar", "Verbo (Pretérito Indefinido)", "raised / built", "diktiler / inşa ettiler", "levantar (geçmiş zaman 3. çoğul)"),
    "vestía": ("vestir", "Verbo (Pretérito Imperfecto)", "wore / was wearing", "giyiyordu / giyerdi", "vestir (şimdiki zamanın hikayesi 3. tekil)"),
    "concentraba": ("concentrar", "Verbo (Pretérito Imperfecto)", "concentrated / was focusing", "odaklanıyordu / yoğunlaşıyordu", "concentrar (şimdiki zamanın hikayesi 3. tekil)"),
    "concentrarse": ("concentrar", "Verbo Reflexivo", "to focus / concentrate", "odaklanmak / yoğunlaşmak", "dönüşlü mastar"),
    "se": ("se", "Pronombre Reflexivo", "himself / herself / itself / themselves / each other", "kendisi / kendini / (dönüşlülük zamiri)", "pronombre reflexivo"),
    "su": ("su", "Posesivo", "his / her / its / their", "onun", "tekil iyelik sıfatı"),
    "sus": ("su", "Posesivo (Plural)", "his / her / their", "onun / onların", "çoğul iyelik sıfatı"),
    "mi": ("mi", "Posesivo", "my", "benim", "tekil iyelik sıfatı"),
    "mis": ("mi", "Posesivo (Plural)", "my", "benim", "çoğul nesneler için iyelik sıfatı"),
    "tu": ("tu", "Posesivo", "your", "senin", "tekil iyelik sıfatı"),
    "tus": ("tu", "Posesivo (Plural)", "your", "senin", "çoğul nesneler için iyelik sıfatı"),
    "nuestro": ("nuestro", "Posesivo", "our", "bizim", "eril iyelik sıfatı"),
    "nuestra": ("nuestro", "Posesivo (Fem)", "our", "bizim", "dişil iyelik sıfatı"),
    "nuestros": ("nuestro", "Posesivo (Plur)", "our", "bizim", "çoğul eril iyelik sıfatı"),
    "nuestras": ("nuestro", "Posesivo (Fem Plur)", "our", "bizim", "çoğul dişil iyelik sıfatı"),
    "mejor": ("mejor", "Adverbio / Adjetivo", "better / best", "daha iyi / en iyi", "karşılaştırma zarfı/sıfatı"),
    "peor": ("peor", "Adverbio / Adjetivo", "worse / worst", "daha kötü / en kötü", "karşılaştırma zarfı/sıfatı"),
    "más": ("más", "Adverbio", "more", "daha / daha fazla", "üstünlük zarfı"),
    "menos": ("menos", "Adverbio", "less", "daha az", "azlık zarfı"),
    "muy": ("muy", "Adverbio", "very", "çok / pek", "derecelendirme zarfı"),
    "mucho": ("mucho", "Adverbio / Adjetivo", "much / a lot", "çok / bol", "zarf/sıfat"),
    "muchos": ("mucho", "Adjetivo / Pronombre (Plural)", "many", "birçok / pek çok", "çoğul sıfat"),
    "muchas": ("mucho", "Adjetivo / Pronombre (Fem Plural)", "many", "birçok / pek çok", "dişil çoğul sıfat"),
    "poco": ("poco", "Adverbio / Adjetivo", "little / few", "az", "zarf/sıfat"),
    "pocos": ("poco", "Adjetivo (Plural)", "few", "az sayıda / birkaç", "çoğul sıfat"),
    "pocas": ("poco", "Adjetivo (Fem Plural)", "few", "az sayıda / birkaç", "dişil çoğul sıfat"),
    "ahorraba": ("ahorrar", "Verbo (Pretérito Imperfecto)", "saved / was saving", "tasarruf ediyordu / kazanıyordu", "ahorrar (şimdiki zamanın hikayesi 3. tekil)"),
    "proyectos": ("proyecto", "Sustantivo (Plural)", "projects", "projeler", "çoğul isim"),
    "proyecto": ("proyecto", "Sustantivo", "project", "proje", "tekil isim"),
    "pilares": ("pilar", "Sustantivo (Plural)", "pillars / columns", "sütunlar / direkler", "çoğul isim"),
    "pilar": ("pilar", "Sustantivo", "pillar / column", "sütun / direk", "tekil isim"),
    "piedras": ("piedra", "Sustantivo (Plural)", "stones", "taşlar", "çoğul isim"),
    "piedra": ("piedra", "Sustantivo", "stone", "taş", "tekil isim"),
    "grandes": ("grande", "Adjetivo (Plural)", "big / large", "büyükler / büyük", "çoğul sıfat"),
    "grande": ("grande", "Adjetivo", "big / large", "büyük", "tekil sıfat"),
    "antigua": ("antiguo", "Adjetivo (Fem)", "ancient / antique", "eski / antik", "dişil sıfat"),
    "antiguo": ("antiguo", "Adjetivo (Masc)", "ancient / antique", "eski / antik", "eril sıfat"),
    "antiguos": ("antiguo", "Adjetivo (Plural)", "ancient / antique", "eskiler / antik", "çoğul sıfat"),
    "antiguas": ("antiguo", "Adjetivo (Fem Plural)", "ancient / antique", "eskiler / antik", "dişil çoğul sıfat"),
    "gente": ("gente", "Sustantivo", "people", "insanlar / halk", "topluluk ismi"),
    "aquí": ("aquí", "Adverbio", "here", "burada", "yer zarfı"),
    "allí": ("allí", "Adverbio", "there", "orada", "yer zarfı"),
    "ahí": ("ahí", "Adverbio", "there (nearby)", "orada", "yer zarfı"),
    "siempre": ("siempre", "Adverbio", "always", "her zaman / daima", "zaman zarfı"),
    "nunca": ("nunca", "Adverbio", "never", "hiçbir zaman / asla", "zaman zarfı"),
    "jamás": ("jamás", "Adverbio", "never", "asla", "zaman zarfı"),
    "suéter": ("suéter", "Sustantivo", "sweater", "kazak", "tekil isim"),
    "negro": ("negro", "Adjetivo", "black", "siyah / kara", "eril sıfat"),
    "negra": ("negro", "Adjetivo (Fem)", "black", "siyah / kara", "dişil sıfat"),
    "negros": ("negro", "Adjetivo (Plural)", "black", "siyahlar / kara", "çoğul sıfat"),
    "negras": ("negro", "Adjetivo (Fem Plural)", "black", "siyahlar / kara", "dişil çoğul sıfat"),
    "tiempo": ("tiempo", "Sustantivo", "time / weather", "zaman / vakit", "tekil isim"),
    "cada": ("cada", "Determinante", "each / every", "her / her bir", "belirteç"),
    "mañana": ("mañana", "Sustantivo / Adverbio", "morning / tomorrow", "sabah / yarın", "isim/zarf"),
    "ropa": ("ropa", "Sustantivo", "clothes / clothing", "kıyafet / giysi", "tekil isim"),
    "ayuda": ("ayudar", "Verbo / Sustantivo", "helps / help", "yardım eder / yardım", "fiil/isim"),
    "calmarse": ("calmar", "Verbo Reflexivo", "to calm down", "sakinleşmek", "dönüşlü mastar"),
    "importante": ("importante", "Adjetivo", "important", "önemli", "sıfat"),
    "importantes": ("importante", "Adjetivo (Plural)", "important", "önemliler / önemli", "çoğul sıfat"),
    "trabajo": ("trabajo", "Sustantivo", "work / job", "iş / çalışma", "tekil isim"),
    "parecen": ("parecer", "Verbo (Presente 3pl)", "seem / look like", "benziyorlar / gibi görünüyorlar", "parecer (geniş zaman 3. çoğul)"),
    "parece": ("parecer", "Verbo (Presente 3sg)", "seems / looks like", "benziyor / gibi görünüyor", "parecer (geniş zaman 3. tekil)"),
    "letras": ("letra", "Sustantivo (Plural)", "letters", "harfler", "çoğul isim"),
    "letra": ("letra", "Sustantivo", "letter", "harf", "tekil isim"),
    "gigantes": ("gigante", "Adjetivo (Plural)", "giant / gigantic", "dev / devasa", "çoğul sıfat"),
    "gigante": ("gigante", "Adjetivo / Sustantivo", "giant / gigantic", "dev / devasa", "sıfat/isim"),
    "hay": ("haber", "Verbo Impersonal (Presente)", "there is / there are", "var / vardır", "mevcudiyet fiili"),

    # Proper nouns and -ía nouns wrongly flagged as verbs before
    "turquía": ("Turquía", "Nombre Propio", "Turkey", "Türkiye", "özel isim"),
    "aaron": ("Aaron", "Nombre Propio", "Aaron", "Harun", "özel isim"),
    "alegría": ("alegría", "Sustantivo", "joy / happiness", "neşe / sevinç", "tekil isim"),
    "armonía": ("armonía", "Sustantivo", "harmony", "uyum / ahenk", "tekil isim"),
    "arqueología": ("arqueología", "Sustantivo", "archaeology", "arkeoloji", "tekil isim"),
    "artesanía": ("artesanía", "Sustantivo", "craftsmanship / handcraft", "zanaat / el sanatı", "tekil isim"),
    "autonomía": ("autonomía", "Sustantivo", "autonomy", "özerklik / bağımsızlık", "tekil isim"),
    "categoría": ("categoría", "Sustantivo", "category", "kategori", "tekil isim"),
    "dicotomía": ("dicotomía", "Sustantivo", "dichotomy", "ikilik / dikotomi", "tekil isim"),
    "etimología": ("etimología", "Sustantivo", "etymology", "kökenbilim / etimoloji", "tekil isim"),
    "filosofía": ("filosofía", "Sustantivo", "philosophy", "felsefe", "tekil isim"),
    "fotografía": ("fotografía", "Sustantivo", "photography / photo", "fotoğraf / fotoğrafçılık", "tekil isim"),
    "ganadería": ("ganadería", "Sustantivo", "livestock farming", "hayvancılık", "tekil isim"),
    "gastronomía": ("gastronomía", "Sustantivo", "gastronomy", "gastronomi / mutfak sanatı", "tekil isim"),
    "geografía": ("geografía", "Sustantivo", "geography", "coğrafya", "tekil isim"),
    "guía": ("guía", "Sustantivo", "guide", "rehber / kılavuz", "tekil isim"),
    "haba": ("haba", "Sustantivo", "broad bean", "bakla", "tekil isim"),
    "historiografía": ("historiografía", "Sustantivo", "historiography", "tarih yazımı", "tekil isim"),
    "ironía": ("ironía", "Sustantivo", "irony", "ironi / ince alay", "tekil isim"),
    "maestría": ("maestría", "Sustantivo", "mastery / skill", "ustalık / maharet", "tekil isim"),
    "mayoría": ("mayoría", "Sustantivo", "majority", "çoğunluk", "tekil isim"),
    "minería": ("minería", "Sustantivo", "mining", "madencilik", "tekil isim"),
    "mitología": ("mitología", "Sustantivo", "mythology", "mitoloji", "tekil isim"),
    "orfebrería": ("orfebrería", "Sustantivo", "goldsmithing", "kuyumculuk / maden sanatı", "tekil isim"),
    "psicología": ("psicología", "Sustantivo", "psychology", "psikoloji", "tekil isim"),
    "sabiduría": ("sabiduría", "Sustantivo", "wisdom", "bilgelik / irfan", "tekil isim"),
    "sequía": ("sequía", "Sustantivo", "drought", "kuraklık", "tekil isim"),
    "soberanía": ("soberanía", "Sustantivo", "sovereignty", "egemenlik / hakimiyet", "tekil isim"),
    "tecnología": ("tecnología", "Sustantivo", "technology", "teknoloji", "tekil isim"),
    "teoría": ("teoría", "Sustantivo", "theory", "kuram / teori", "tekil isim"),
    "tía": ("tía", "Sustantivo", "aunt", "teyze / hala", "tekil isim"),
    "vía": ("vía", "Sustantivo", "way / route / track", "yol / hat / güzergah", "tekil isim"),

    # All 235 verbs from the previous audit
    "abrieron": ("abrir", "Verbo (Pretérito Indefinido)", "opened", "açtılar", "abrir (geçmiş zaman 3. çoğul)"),
    "abrió": ("abrir", "Verbo (Pretérito Indefinido)", "opened", "açtı", "abrir (geçmiş zaman 3. tekil)"),
    "acarrearía": ("acarrear", "Verbo (Condicional)", "would entail / bring", "beraberinde getirirdi", "acarrear (koşul kipi)"),
    "acechaba": ("acechar", "Verbo (Pretérito Imperfecto)", "lurked / stalked", "pusudaydı / kol geziyordu", "acechar (şimdiki zamanın hikayesi)"),
    "acumularon": ("acumular", "Verbo (Pretérito Indefinido)", "accumulated", "biriktirdiler / topladılar", "acumular (geçmiş zaman 3. çoğul)"),
    "adoptó": ("adoptar", "Verbo (Pretérito Indefinido)", "adopted", "benimsedi / kabul etti", "adoptar (geçmiş zaman 3. tekil)"),
    "afirmaban": ("afirmar", "Verbo (Pretérito Imperfecto)", "affirmed / stated", "öne sürüyorlardı / belirtiyorlardı", "afirmar (şimdiki zamanın hikayesi 3. çoğul)"),
    "agotarían": ("agotar", "Verbo (Condicional)", "would exhaust", "tüketirlerdi", "agotar (koşul kipi 3. çoğul)"),
    "agudizaba": ("agudizar", "Verbo (Pretérito Imperfecto)", "worsened / sharpened", "şiddetlendiriyordu / derinleştiriyordu", "agudizar (şimdiki zamanın hikayesi)"),
    "aislaron": ("aislar", "Verbo (Pretérito Indefinido)", "isolated", "izole ettiler / yalıttılar", "aislar (geçmiş zaman 3. çoğul)"),
    "albergaban": ("albergar", "Verbo (Pretérito Imperfecto)", "housed / sheltered", "barındırıyorlardı", "albergar (şimdiki zamanın hikayesi 3. çoğul)"),
    "amaba": ("amar", "Verbo (Pretérito Imperfecto)", "loved", "seviyordu", "amar (şimdiki zamanın hikayesi 3. tekil)"),
    "anotó": ("anotar", "Verbo (Pretérito Indefinido)", "noted / wrote down", "not etti / kaydetti", "anotar (geçmiş zaman 3. tekil)"),
    "ansiaban": ("ansiar", "Verbo (Pretérito Imperfecto)", "yearned for / longed for", "can atıyorlardı / arzuluyorlardı", "ansiar (şimdiki zamanın hikayesi 3. çoğul)"),
    "apagaba": ("apagar", "Verbo (Pretérito Imperfecto)", "extinguished / turned off", "söndürüyordu / kapatıyordu", "apagar (şimdiki zamanın hikayesi 3. tekil)"),
    "aportaron": ("aportar", "Verbo (Pretérito Indefinido)", "contributed", "katkıda bulundular / sağladılar", "aportar (geçmiş zaman 3. çoğul)"),
    "aportó": ("aportar", "Verbo (Pretérito Indefinido)", "contributed", "katkı sağladı / sundu", "aportar (geçmiş zaman 3. tekil)"),
    "aprendió": ("aprender", "Verbo (Pretérito Indefinido)", "learned", "öğrendi", "aprender (geçmiş zaman 3. tekil)"),
    "bajó": ("bajar", "Verbo (Pretérito Indefinido)", "went down / descended", "indi / azaldı", "bajar (geçmiş zaman 3. tekil)"),
    "bloqueaban": ("bloquear", "Verbo (Pretérito Imperfecto)", "blocked", "engelliyorlardı / tıkıyorlardı", "bloquear (şimdiki zamanın hikayesi 3. çoğul)"),
    "buscaban": ("buscar", "Verbo (Pretérito Imperfecto)", "were looking for / sought", "arıyorlardı", "buscar (şimdiki zamanın hikayesi 3. çoğul)"),
    "cabalgaría": ("cabalgar", "Verbo (Condicional)", "would ride", "at binerdi / sürerdi", "cabalgar (koşul kipi)"),
    "caerían": ("caer", "Verbo (Condicional)", "would fall", "düşerlerdi", "caer (koşul kipi 3. çoğul)"),
    "calentaban": ("calentar", "Verbo (Pretérito Imperfecto)", "heated / were warming", "ısıtıyorlardı", "calentar (şimdiki zamanın hikayesi 3. çoğul)"),
    "canalizaba": ("canalizar", "Verbo (Pretérito Imperfecto)", "channeled", "yönlendiriyordu / kanalize ediyordu", "canalizar (şimdiki zamanın hikayesi)"),
    "canalizó": ("canalizar", "Verbo (Pretérito Indefinido)", "channeled", "yönlendirdi / aktardı", "canalizar (geçmiş zaman 3. tekil)"),
    "cantó": ("cantar", "Verbo (Pretérito Indefinido)", "sang", "şarkı söyledi / öttü", "cantar (geçmiş zaman 3. tekil)"),
    "causó": ("causar", "Verbo (Pretérito Indefinido)", "caused", "yol açtı / neden oldu", "causar (geçmiş zaman 3. tekil)"),
    "cedieron": ("ceder", "Verbo (Pretérito Indefinido)", "yielded / gave in", "boyun eğdiler / yer verdiler", "ceder (geçmiş zaman 3. çoğul)"),
    "clausuraban": ("clausurar", "Verbo (Pretérito Imperfecto)", "closed off", "kapatıyorlardı / mühürlüyorlardı", "clausurar (şimdiki zamanın hikayesi)"),
    "clausuraron": ("clausurar", "Verbo (Pretérito Indefinido)", "closed off", "kapattılar / mühürlediler", "clausurar (geçmiş zaman 3. çoğul)"),
    "comenzaron": ("comenzar", "Verbo (Pretérito Indefinido)", "began / started", "başladılar", "comenzar (geçmiş zaman 3. çoğul)"),
    "comenzó": ("comenzar", "Verbo (Pretérito Indefinido)", "began / started", "başladı", "comenzar (geçmiş zaman 3. tekil)"),
    "compartimentaban": ("compartimentar", "Verbo (Pretérito Imperfecto)", "compartmentalized", "bölümlere ayırıyorlardı", "compartimentar (şimdiki zamanın hikayesi)"),
    "comparó": ("comparar", "Verbo (Pretérito Indefinido)", "compared", "karşılaştırdı / kıyasladı", "comparar (geçmiş zaman 3. tekil)"),
    "competían": ("competir", "Verbo (Pretérito Imperfecto)", "competed", "yarışıyorlardı / rekabet ediyorlardı", "competir (şimdiki zamanın hikayesi 3. çoğul)"),
    "concebía": ("concebir", "Verbo (Pretérito Imperfecto)", "conceived / understood", "tasarlıyordu / kavrıyordu", "concebir (şimdiki zamanın hikayesi)"),
    "confirió": ("conferir", "Verbo (Pretérito Indefinido)", "conferred / bestowed", "bahşetti / kazandırdı", "conferir (geçmiş zaman 3. tekil)"),
    "consideraban": ("considerar", "Verbo (Pretérito Imperfecto)", "considered", "kabul ediyorlardı / sayıyorlardı", "considerar (şimdiki zamanın hikayesi 3. çoğul)"),
    "constató": ("constatar", "Verbo (Pretérito Indefinido)", "verified / observed", "tespit etti / saptadı", "constatar (geçmiş zaman 3. tekil)"),
    "constituía": ("constituir", "Verbo (Pretérito Imperfecto)", "constituted", "oluşturuyordu / teşkil ediyordu", "constituir (şimdiki zamanın hikayesi)"),
    "construyó": ("construir", "Verbo (Pretérito Indefinido)", "built / constructed", "inşa etti / yaptı", "construir (geçmiş zaman 3. tekil)"),
    "consumían": ("consumir", "Verbo (Pretérito Imperfecto)", "consumed", "tüketiyorlardı", "consumir (şimdiki zamanın hikayesi 3. çoğul)"),
    "contenían": ("contener", "Verbo (Pretérito Imperfecto)", "contained", "içeriyorlardı / kapsıyorlardı", "contener (şimdiki zamanın hikayesi 3. çoğul)"),
    "convertirían": ("convertir", "Verbo (Condicional)", "would convert / transform", "dönüştürürlerdi", "convertir (koşul kipi 3. çoğul)"),
    "convirtieron": ("convertir", "Verbo (Pretérito Indefinido)", "transformed / converted", "dönüştürdüler", "convertir (geçmiş zaman 3. çoğul)"),
    "convirtió": ("convertir", "Verbo (Pretérito Indefinido)", "transformed / converted", "dönüştürdü", "convertir (geçmiş zaman 3. tekil)"),
    "crearon": ("crear", "Verbo (Pretérito Indefinido)", "created", "yarattılar / oluşturdular", "crear (geçmiş zaman 3. çoğul)"),
    "creó": ("crear", "Verbo (Pretérito Indefinido)", "created", "yarattı / oluşturdu", "crear (geçmiş zaman 3. tekil)"),
    "cuajaba": ("cuajar", "Verbo (Pretérito Imperfecto)", "curdled / set", "pıhtılaşıyordu / tutuyordu", "cuajar (şimdiki zamanın hikayesi)"),
    "debatían": ("debatir", "Verbo (Pretérito Imperfecto)", "debated", "tartışıyorlardı", "debatir (şimdiki zamanın hikayesi 3. çoğul)"),
    "debían": ("deber", "Verbo (Pretérito Imperfecto)", "had to / owed", "zorunda idiler / borçluydular", "deber (şimdiki zamanın hikayesi 3. çoğul)"),
    "decidieron": ("decidir", "Verbo (Pretérito Indefinido)", "decided", "karar verdiler", "decidir (geçmiş zaman 3. çoğul)"),
    "decidió": ("decidir", "Verbo (Pretérito Indefinido)", "decided", "karar verdi", "decidir (geçmiş zaman 3. tekil)"),
    "dejaron": ("dejar", "Verbo (Pretérito Indefinido)", "left / allowed", "bıraktılar / terk ettiler", "dejar (geçmiş zaman 3. çoğul)"),
    "dejó": ("dejar", "Verbo (Pretérito Indefinido)", "left / allowed", "bıraktı / terk etti", "dejar (geçmiş zaman 3. tekil)"),
    "demostraron": ("demostrar", "Verbo (Pretérito Indefinido)", "demonstrated / showed", "kanıtladılar / gösterdiler", "demostrar (geçmiş zaman 3. çoğul)"),
    "demostró": ("demostrar", "Verbo (Pretérito Indefinido)", "demonstrated / showed", "kanıtladı / gösterdi", "demostrar (geçmiş zaman 3. tekil)"),
    "desafió": ("desafiar", "Verbo (Pretérito Indefinido)", "challenged / defied", "meydan okudu", "desafiar (geçmiş zaman 3. tekil)"),
    "desaparecieron": ("desaparecer", "Verbo (Pretérito Indefinido)", "disappeared", "kayboldular", "desaparecer (geçmiş zaman 3. çoğul)"),
    "desarrollaron": ("desarrollar", "Verbo (Pretérito Indefinido)", "developed", "geliştirdiler", "desarrollar (geçmiş zaman 3. çoğul)"),
    "desbloquearon": ("desbloquear", "Verbo (Pretérito Indefinido)", "unlocked", "kilidini açtılar / serbest bıraktılar", "desbloquear (geçmiş zaman 3. çoğul)"),
    "descendían": ("descender", "Verbo (Pretérito Imperfecto)", "descended", "iniyorlardı", "descender (şimdiki zamanın hikayesi 3. çoğul)"),
    "describió": ("describir", "Verbo (Pretérito Indefinido)", "described", "betimledi / tarif etti", "describir (geçmiş zaman 3. tekil)"),
    "descubrieron": ("descubrir", "Verbo (Pretérito Indefinido)", "discovered", "keşfettiler", "descubrir (geçmiş zaman 3. çoğul)"),
    "descubrió": ("descubrir", "Verbo (Pretérito Indefinido)", "discovered", "keşfetti", "descubrir (geçmiş zaman 3. tekil)"),
    "dibujaban": ("dibujar", "Verbo (Pretérito Imperfecto)", "drew / were sketching", "çiziyorlardı / resmediyorlardı", "dibujar (şimdiki zamanın hikayesi 3. çoğul)"),
    "distinguió": ("distinguir", "Verbo (Pretérito Indefinido)", "distinguished", "ayırt etti / fark etti", "distinguir (geçmiş zaman 3. tekil)"),
    "domesticaban": ("domesticar", "Verbo (Pretérito Imperfecto)", "domesticated", "evcilleştiriyorlardı", "domesticar (şimdiki zamanın hikayesi 3. çoğul)"),
    "durmió": ("dormir", "Verbo (Pretérito Indefinido)", "slept", "uyudu", "dormir (geçmiş zaman 3. tekil)"),
    "elegía": ("elegir", "Verbo (Pretérito Imperfecto)", "chose / was choosing", "seçiyordu", "elegir (şimdiki zamanın hikayesi)"),
    "eligieron": ("elegir", "Verbo (Pretérito Indefinido)", "chose", "seçtiler", "elegir (geçmiş zaman 3. çoğul)"),
    "emprendió": ("emprender", "Verbo (Pretérito Indefinido)", "undertook / set out", "girişti / yola çıktı", "emprender (geçmiş zaman 3. tekil)"),
    "encareció": ("encarecer", "Verbo (Pretérito Indefinido)", "made expensive", "pahalılaştırdı", "encarecer (geçmiş zaman 3. tekil)"),
    "encarnó": ("encarnar", "Verbo (Pretérito Indefinido)", "embodied", "somutlaştırdı / canlandırdı", "encarnar (geçmiş zaman 3. tekil)"),
    "encontraba": ("encontrar", "Verbo (Pretérito Imperfecto)", "was located / found", "bulunuyordu / yer alıyordu", "encontrar (şimdiki zamanın hikayesi)"),
    "encontró": ("encontrar", "Verbo (Pretérito Indefinido)", "found", "buldu", "encontrar (geçmiş zaman 3. tekil)"),
    "enfría": ("enfriar", "Verbo (Presente 3sg)", "cools", "soğutur", "enfriar (geniş zaman 3. tekil)"),
    "enseñó": ("enseñar", "Verbo (Pretérito Indefinido)", "taught / showed", "öğretti / gösterdi", "enseñar (geçmiş zaman 3. tekil)"),
    "entraron": ("entrar", "Verbo (Pretérito Indefinido)", "entered", "girdiler", "entrar (geçmiş zaman 3. çoğul)"),
    "envía": ("enviar", "Verbo (Presente 3sg)", "sends", "gönderir / yollar", "enviar (geniş zaman 3. tekil)"),
    "envían": ("enviar", "Verbo (Presente 3pl)", "send", "gönderirler / yollarlar", "enviar (geniş zaman 3. çoğul)"),
    "erigía": ("erigir", "Verbo (Pretérito Imperfecto)", "erected / stood", "yükseliyordu / dikiliyordu", "erigir (şimdiki zamanın hikayesi)"),
    "escondieron": ("esconder", "Verbo (Pretérito Indefinido)", "hid", "sakladılar / gizlediler", "esconder (geçmiş zaman 3. çoğul)"),
    "escondían": ("esconder", "Verbo (Pretérito Imperfecto)", "were hiding", "saklıyorlardı / gizliyorlardı", "esconder (şimdiki zamanın hikayesi 3. çoğul)"),
    "escribió": ("escribir", "Verbo (Pretérito Indefinido)", "wrote", "yazdı", "escribir (geçmiş zaman 3. tekil)"),
    "escribieron": ("escribir", "Verbo (Pretérito Indefinido)", "wrote", "yazdılar", "escribir (geçmiş zaman 3. çoğul)"),
    "escribían": ("escribir", "Verbo (Pretérito Imperfecto)", "were writing", "yazıyorlardı", "escribir (şimdiki zamanın hikayesi 3. çoğul)"),
    "excavaron": ("excavar", "Verbo (Pretérito Indefinido)", "excavated", "kazdılar / gün yüzüne çıkardılar", "excavar (geçmiş zaman 3. çoğul)"),
    "exclamó": ("exclamar", "Verbo (Pretérito Indefinido)", "exclaimed", "haykırdı / ünledi", "exclamar (geçmiş zaman 3. tekil)"),
    "explicó": ("explicar", "Verbo (Pretérito Indefinido)", "explained", "açıkladı / izah etti", "explicar (geçmiş zaman 3. tekil)"),
    "exploró": ("explorar", "Verbo (Pretérito Indefinido)", "explored", "keşfetti / araştırdı", "explorar (geçmiş zaman 3. tekil)"),
    "expresaron": ("expresar", "Verbo (Pretérito Indefinido)", "expressed", "ifade ettiler / dile getirdiler", "expresar (geçmiş zaman 3. çoğul)"),
    "fermentaron": ("fermentar", "Verbo (Pretérito Indefinido)", "fermented", "mayaladılar / fermente ettiler", "fermentar (geçmiş zaman 3. çoğul)"),
    "floreció": ("florecer", "Verbo (Pretérito Indefinido)", "flourished / bloomed", "çiçek açtı / serpildi", "florecer (geçmiş zaman 3. tekil)"),
    "flotaba": ("flotar", "Verbo (Pretérito Imperfecto)", "floated", "yüzüyordu / süzülüyordu", "flotar (şimdiki zamanın hikayesi)"),
    "fortalecieron": ("fortalecer", "Verbo (Pretérito Indefinido)", "strengthened", "güçlendirdiler", "fortalecer (geçmiş zaman 3. çoğul)"),
    "funcionaba": ("funcionar", "Verbo (Pretérito Imperfecto)", "worked / functioned", "işliyordu / çalışıyordu", "funcionar (şimdiki zamanın hikayesi)"),
    "fundaron": ("fundar", "Verbo (Pretérito Indefinido)", "founded", "kurdular", "fundar (geçmiş zaman 3. çoğul)"),
    "ganó": ("ganar", "Verbo (Pretérito Indefinido)", "won / earned", "kazandı", "ganar (geçmiş zaman 3. tekil)"),
    "gastaban": ("gastar", "Verbo (Pretérito Imperfecto)", "spent", "harcıyorlardı", "gastar (şimdiki zamanın hikayesi 3. çoğul)"),
    "generó": ("generar", "Verbo (Pretérito Indefinido)", "generated / caused", "üretti / yol açtı", "generar (geçmiş zaman 3. tekil)"),
    "gobernaba": ("gobernar", "Verbo (Pretérito Imperfecto)", "ruled / governed", "yönetiyordu / hükmediyordu", "gobernar (şimdiki zamanın hikayesi)"),
    "gozó": ("gozar", "Verbo (Pretérito Indefinido)", "enjoyed", "tadını çıkardı / sefasını sürdü", "gozar (geçmiş zaman 3. tekil)"),
    "guardaba": ("guardar", "Verbo (Pretérito Imperfecto)", "kept / saved", "saklıyordu / koruyordu", "guardar (şimdiki zamanın hikayesi)"),
    "gustó": ("gustar", "Verbo (Pretérito Indefinido)", "pleased / liked", "hoşuna gitti / beğenildi", "gustar (geçmiş zaman 3. tekil)"),
    "hablaba": ("hablar", "Verbo (Pretérito Imperfecto)", "was speaking", "konuşuyordu", "hablar (şimdiki zamanın hikayesi 3. tekil)"),
    "hablaban": ("hablar", "Verbo (Pretérito Imperfecto)", "were speaking", "konuşuyorlardı", "hablar (şimdiki zamanın hikayesi 3. çoğul)"),
    "habló": ("hablar", "Verbo (Pretérito Indefinido)", "spoke", "konuştu", "hablar (geçmiş zaman 3. tekil)"),
    "halló": ("hallar", "Verbo (Pretérito Indefinido)", "found", "buldu", "hallar (geçmiş zaman 3. tekil)"),
    "hicieron": ("hacer", "Verbo (Pretérito Indefinido)", "made / did", "yaptılar", "hacer (geçmiş zaman 3. çoğul)"),
    "huían": ("huir", "Verbo (Pretérito Imperfecto)", "were fleeing", "kaçıyorlardı", "huir (şimdiki zamanın hikayesi 3. çoğul)"),
    "ideó": ("idear", "Verbo (Pretérito Indefinido)", "devised / conceived", "tasarladı / akıl etti", "idear (geçmiş zaman 3. tekil)"),
    "imitaba": ("imitar", "Verbo (Pretérito Imperfecto)", "imitated", "taklit ediyordu", "imitar (şimdiki zamanın hikayesi)"),
    "impulsó": ("impulsar", "Verbo (Pretérito Indefinido)", "boosted / prompted", "teşvik etti / ivme kazandırdı", "impulsar (geçmiş zaman 3. tekil)"),
    "incluían": ("incluir", "Verbo (Pretérito Imperfecto)", "included", "içeriyorlardı / kapsıyorlardı", "incluir (şimdiki zamanın hikayesi 3. çoğul)"),
    "investigó": ("investigar", "Verbo (Pretérito Indefinido)", "investigated / researched", "araştırdı / inceledi", "investigar (geçmiş zaman 3. tekil)"),
    "invitaron": ("invitar", "Verbo (Pretérito Indefinido)", "invited", "davet ettiler", "invitar (geçmiş zaman 3. çoğul)"),
    "irrumpía": ("irrumpir", "Verbo (Pretérito Imperfecto)", "burst into", "aniden girdi / patlak verdi", "irrumpir (şimdiki zamanın hikayesi)"),
    "latían": ("latir", "Verbo (Pretérito Imperfecto)", "were beating", "atıyorlardı / çarpıyorlardı", "latir (şimdiki zamanın hikayesi 3. çoğul)"),
    "liberó": ("liberar", "Verbo (Pretérito Indefinido)", "freed / released", "serbest bıraktı / kurtardı", "liberar (geçmiş zaman 3. tekil)"),
    "llamaban": ("llamar", "Verbo (Pretérito Imperfecto)", "used to call", "adlandırırlardı / derlerdi", "llamar (şimdiki zamanın hikayesi 3. çoğul)"),
    "llamaron": ("llamar", "Verbo (Pretérito Indefinido)", "called / named", "adlandırdılar / çağırdılar", "llamar (geçmiş zaman 3. çoğul)"),
    "llegaron": ("llegar", "Verbo (Pretérito Indefinido)", "arrived", "vardılar / ulaştılar", "llegar (geçmiş zaman 3. çoğul)"),
    "llevó": ("llevar", "Verbo (Pretérito Indefinido)", "took / carried", "götürdü / taşıdı", "llevar (geçmiş zaman 3. tekil)"),
    "localizaron": ("localizar", "Verbo (Pretérito Indefinido)", "located / pinpointed", "yerini tespit ettiler", "localizar (geçmiş zaman 3. çoğul)"),
    "logró": ("lograr", "Verbo (Pretérito Indefinido)", "achieved / managed", "başardı / elde etti", "lograr (geçmiş zaman 3. tekil)"),
    "marcaron": ("marcar", "Verbo (Pretérito Indefinido)", "marked", "işaretlediler / damgasını vurdular", "marcar (geçmiş zaman 3. çoğul)"),
    "metieron": ("meter", "Verbo (Pretérito Indefinido)", "put inside", "içine koydular / soktular", "meter (geçmiş zaman 3. çoğul)"),
    "modeló": ("modelar", "Verbo (Pretérito Indefinido)", "modeled", "biçimlendirdi / modelledi", "modelar (geçmiş zaman 3. tekil)"),
    "mojó": ("mojar", "Verbo (Pretérito Indefinido)", "wetted", "ıslattı", "mojar (geçmiş zaman 3. tekil)"),
    "moraba": ("morar", "Verbo (Pretérito Imperfecto)", "dwelt / resided", "yaşıyordu / ikamet ediyordu", "morar (şimdiki zamanın hikayesi)"),
    "movían": ("mover", "Verbo (Pretérito Imperfecto)", "were moving", "hareket ettiriyorlardı", "mover (şimdiki zamanın hikayesi 3. çoğul)"),
    "nació": ("nacer", "Verbo (Pretérito Indefinido)", "was born", "doğdu", "nacer (geçmiş zaman 3. tekil)"),
    "navegaba": ("navegar", "Verbo (Pretérito Imperfecto)", "sailed", "denize açılıyordu / yelken açıyordu", "navegar (şimdiki zamanın hikayesi)"),
    "obligaban": ("obligar", "Verbo (Pretérito Imperfecto)", "obliged / compelled", "zorunlu kılıyorlardı / mecbur ediyorlardı", "obligar (şimdiki zamanın hikayesi 3. çoğul)"),
    "observaron": ("observar", "Verbo (Pretérito Indefinido)", "observed", "gözlemlediler", "observar (geçmiş zaman 3. çoğul)"),
    "observó": ("observar", "Verbo (Pretérito Indefinido)", "observed", "gözlemledi", "observar (geçmiş zaman 3. tekil)"),
    "ocultaron": ("ocultar", "Verbo (Pretérito Indefinido)", "hid / concealed", "gizlediler / sakladılar", "ocultar (geçmiş zaman 3. çoğul)"),
    "ocurriría": ("ocurrir", "Verbo (Condicional)", "would occur / happen", "meydana gelirdi / olurdu", "ocurrir (koşul kipi)"),
    "operó": ("operar", "Verbo (Pretérito Indefinido)", "operated", "çalıştı / ameliyat etti", "operar (geçmiş zaman 3. tekil)"),
    "organizaban": ("organizar", "Verbo (Pretérito Imperfecto)", "organized", "düzenliyorlardı / örgütlüyorlardı", "organizar (şimdiki zamanın hikayesi 3. çoğul)"),
    "paseaba": ("pasear", "Verbo (Pretérito Imperfecto)", "strolled / walked", "geziniyordu / dolaşıyordu", "pasear (şimdiki zamanın hikayesi)"),
    "pasó": ("pasar", "Verbo (Pretérito Indefinido)", "passed / happened", "geçti / oldu", "pasar (geçmiş zaman 3. tekil)"),
    "perdió": ("perder", "Verbo (Pretérito Indefinido)", "lost", "kaybetti", "perder (geçmiş zaman 3. tekil)"),
    "permaneció": ("permanecer", "Verbo (Pretérito Indefinido)", "remained", "kaldı / varlığını korudu", "permanecer (geçmiş zaman 3. tekil)"),
    "permitió": ("permitir", "Verbo (Pretérito Indefinido)", "allowed / enabled", "izin verdi / olanak tanıdı", "permitir (geçmiş zaman 3. tekil)"),
    "permitían": ("permitir", "Verbo (Pretérito Imperfecto)", "allowed / enabled", "izin veriyorlardı / sağlıyorlardı", "permitir (şimdiki zamanın hikayesi 3. çoğul)"),
    "perseguían": ("perseguir", "Verbo (Pretérito Imperfecto)", "pursued / chased", "kovalıyorlardı / peşindeydiler", "perseguir (şimdiki zamanın hikayesi 3. çoğul)"),
    "pidió": ("pedir", "Verbo (Pretérito Indefinido)", "asked for / requested", "istedi / talep etti", "pedir (geçmiş zaman 3. tekil)"),
    "pintaron": ("pintar", "Verbo (Pretérito Indefinido)", "painted", "boyadılar / resmettiler", "pintar (geçmiş zaman 3. çoğul)"),
    "pintó": ("pintar", "Verbo (Pretérito Indefinido)", "painted", "boyadı / resmetti", "pintar (geçmiş zaman 3. tekil)"),
    "planteó": ("plantear", "Verbo (Pretérito Indefinido)", "posed / raised", "ortaya koydu / öne sürdü", "plantear (geçmiş zaman 3. tekil)"),
    "plasmó": ("plasmar", "Verbo (Pretérito Indefinido)", "captured / expressed", "yansıttı / somutlaştırdı", "plasmar (geçmiş zaman 3. tekil)"),
    "podría": ("poder", "Verbo (Condicional)", "could / might", "yapabilirdi / olabilirdi", "poder (koşul kipi)"),
    "podía": ("poder", "Verbo (Pretérito Imperfecto)", "could / was able to", "yapabiliyordu / -ebiliyordu", "poder (şimdiki zamanın hikayesi 3. tekil)"),
    "podían": ("poder", "Verbo (Pretérito Imperfecto)", "could / were able to", "yapabiliyorlardı", "poder (şimdiki zamanın hikayesi 3. çoğul)"),
    "poseían": ("poseer", "Verbo (Pretérito Imperfecto)", "possessed / owned", "sahiptiler", "poseer (şimdiki zamanın hikayesi 3. çoğul)"),
    "precedieron": ("preceder", "Verbo (Pretérito Indefinido)", "preceded", "önce geldiler", "preceder (geçmiş zaman 3. çoğul)"),
    "precedió": ("preceder", "Verbo (Pretérito Indefinido)", "preceded", "önce geldi", "preceder (geçmiş zaman 3. tekil)"),
    "probó": ("probar", "Verbo (Pretérito Indefinido)", "tasted / tried", "denedi / tattı", "probar (geçmiş zaman 3. tekil)"),
    "proclamó": ("proclamar", "Verbo (Pretérito Indefinido)", "proclaimed", "ilan etti / duyurdu", "proclamar (geçmiş zaman 3. tekil)"),
    "protegieron": ("proteger", "Verbo (Pretérito Indefinido)", "protected", "korudular", "proteger (geçmiş zaman 3. çoğul)"),
    "publicaron": ("publicar", "Verbo (Pretérito Indefinido)", "published", "yayımladılar", "publicar (geçmiş zaman 3. çoğul)"),
    "pudieron": ("poder", "Verbo (Pretérito Indefinido)", "could / were able to", "başarabildiler / yapabildiler", "poder (geçmiş zaman 3. çoğul)"),
    "pudría": ("pudrir", "Verbo (Pretérito Imperfecto)", "rotted / decayed", "çürüyordu", "pudrir (şimdiki zamanın hikayesi)"),
    "quedarían": ("quedar", "Verbo (Condicional)", "would remain", "kalırlardı", "quedar (koşul kipi 3. çoğul)"),
    "quería": ("querer", "Verbo (Pretérito Imperfecto)", "wanted", "istiyordu", "querer (şimdiki zamanın hikayesi 3. tekil)"),
    "querían": ("querer", "Verbo (Pretérito Imperfecto)", "wanted", "istiyorlardı", "querer (şimdiki zamanın hikayesi 3. çoğul)"),
    "rechazaron": ("rechazar", "Verbo (Pretérito Indefinido)", "rejected", "reddettiler / geri çevirdiler", "rechazar (geçmiş zaman 3. çoğul)"),
    "rechazó": ("rechazar", "Verbo (Pretérito Indefinido)", "rejected", "reddetti / geri çevirdi", "rechazar (geçmiş zaman 3. tekil)"),
    "recitaban": ("recitar", "Verbo (Pretérito Imperfecto)", "recited", "ezberden okuyorlardı / terennüm ediyorlardı", "recitar (şimdiki zamanın hikayesi 3. çoğul)"),
    "recordaba": ("recordar", "Verbo (Pretérito Imperfecto)", "remembered", "hatırlıyordu / anımsıyordu", "recordar (şimdiki zamanın hikayesi)"),
    "recorrían": ("recorrer", "Verbo (Pretérito Imperfecto)", "traversed / toured", "kat ediyorlardı / geziyorlardı", "recorrer (şimdiki zamanın hikayesi 3. çoğul)"),
    "recurría": ("recurrir", "Verbo (Pretérito Imperfecto)", "resorted to", "başvuruyordu", "recurrir (şimdiki zamanın hikayesi)"),
    "refugiaban": ("refugiar", "Verbo (Pretérito Imperfecto)", "sheltered", "sığınıyorlardı", "refugiar (şimdiki zamanın hikayesi 3. çoğul)"),
    "regaló": ("regalar", "Verbo (Pretérito Indefinido)", "gifted / gave", "hediye etti / bağışladı", "regalar (geçmiş zaman 3. tekil)"),
    "registró": ("registrar", "Verbo (Pretérito Indefinido)", "recorded / registered", "kaydetti / tescilledi", "registrar (geçmiş zaman 3. tekil)"),
    "repararon": ("reparar", "Verbo (Pretérito Indefinido)", "repaired", "tamir ettiler / onardılar", "reparar (geçmiş zaman 3. çoğul)"),
    "reparó": ("reparar", "Verbo (Pretérito Indefinido)", "repaired", "tamir etti / onardı", "reparar (geçmiş zaman 3. tekil)"),
    "resurgieron": ("resurgir", "Verbo (Pretérito Indefinido)", "re-emerged", "yeniden doğdular / canlandılar", "resurgir (geçmiş zaman 3. çoğul)"),
    "reunían": ("reunir", "Verbo (Pretérito Imperfecto)", "gathered / assembled", "toplanırlardı / bir araya gelirlerdi", "reunir (şimdiki zamanın hikayesi 3. çoğul)"),
    "reunió": ("reunir", "Verbo (Pretérito Indefinido)", "gathered / assembled", "topladı / bir araya getirdi", "reunir (geçmiş zaman 3. tekil)"),
    "revivieron": ("revivir", "Verbo (Pretérito Indefinido)", "revived", "canlandırdılar / yeniden canlandılar", "revivir (geçmiş zaman 3. çoğul)"),
    "sabía": ("saber", "Verbo (Pretérito Imperfecto)", "knew", "biliyordu", "saber (şimdiki zamanın hikayesi 3. tekil)"),
    "sacó": ("sacar", "Verbo (Pretérito Indefinido)", "took out", "çıkardı / aldı", "sacar (geçmiş zaman 3. tekil)"),
    "salieron": ("salir", "Verbo (Pretérito Indefinido)", "went out / left", "çıktılar", "salir (geçmiş zaman 3. çoğul)"),
    "sanó": ("sanar", "Verbo (Pretérito Indefinido)", "healed", "iyileşti / şifa buldu", "sanar (geçmiş zaman 3. tekil)"),
    "satirizaba": ("satirizar", "Verbo (Pretérito Imperfecto)", "satirized", "hicvediyordu / taşlıyordu", "satirizar (şimdiki zamanın hikayesi)"),
    "sentaba": ("sentar", "Verbo (Pretérito Imperfecto)", "sat / established", "oturtuyordu / temellendiriyordu", "sentar (şimdiki zamanın hikayesi)"),
    "sentenció": ("sentenciar", "Verbo (Pretérito Indefinido)", "sentenced / ruled", "hükmetti / karar bağladı", "sentenciar (geçmiş zaman 3. tekil)"),
    "sintió": ("sentir", "Verbo (Pretérito Indefinido)", "felt", "hissetti", "sentir (geçmiş zaman 3. tekil)"),
    "sitió": ("sitiar", "Verbo (Pretérito Indefinido)", "besieged", "kuşattı / ablukaya aldı", "sitiar (geçmiş zaman 3. tekil)"),
    "sostuvieron": ("sostener", "Verbo (Pretérito Indefinido)", "held / maintained", "savundular / tuttular", "sostener (geçmiş zaman 3. çoğul)"),
    "sufrió": ("sufrir", "Verbo (Pretérito Indefinido)", "suffered", "acı çekti / maruz kaldı", "sufrir (geçmiş zaman 3. tekil)"),
    "suministraban": ("suministrar", "Verbo (Pretérito Imperfecto)", "supplied", "tedarik ediyorlardı / sağlıyorlardı", "suministrar (şimdiki zamanın hikayesi 3. çoğul)"),
    "suscitaron": ("suscitar", "Verbo (Pretérito Indefinido)", "aroused / sparked", "uyandırdılar / yol açtılar", "suscitar (geçmiş zaman 3. çoğul)"),
    "susurraba": ("susurrar", "Verbo (Pretérito Imperfecto)", "whispered", "fısıldıyordu", "susurrar (şimdiki zamanın hikayesi)"),
    "tallaron": ("tallar", "Verbo (Pretérito Indefinido)", "carved", "yonttular / oydular", "tallar (geçmiş zaman 3. çoğul)"),
    "terminó": ("terminar", "Verbo (Pretérito Indefinido)", "ended / finished", "bitti / sona erdi", "terminar (geçmiş zaman 3. tekil)"),
    "tomó": ("tomar", "Verbo (Pretérito Indefinido)", "took / drank", "aldı / içti", "tomar (geçmiş zaman 3. tekil)"),
    "tornó": ("tornar", "Verbo (Pretérito Indefinido)", "turned into", "dönüştü / döndü", "tornar (geçmiş zaman 3. tekil)"),
    "trabajaban": ("trabajar", "Verbo (Pretérito Imperfecto)", "worked", "çalışıyorlardı", "trabajar (şimdiki zamanın hikayesi 3. çoğul)"),
    "trabó": ("trabar", "Verbo (Pretérito Indefinido)", "engaged in / locked", "tutuştu / kilitlendi", "trabar (geçmiş zaman 3. tekil)"),
    "transformaron": ("transformar", "Verbo (Pretérito Indefinido)", "transformed", "dönüştürdüler", "transformar (geçmiş zaman 3. çoğul)"),
    "transformó": ("transformar", "Verbo (Pretérito Indefinido)", "transformed", "dönüştürdü", "transformar (geçmiş zaman 3. tekil)"),
    "transmitió": ("transmitir", "Verbo (Pretérito Indefinido)", "transmitted", "aktardı / iletti", "transmitir (geçmiş zaman 3. tekil)"),
    "transportaban": ("transportar", "Verbo (Pretérito Imperfecto)", "transported", "taşıyorlardı", "transportar (şimdiki zamanın hikayesi 3. çoğul)"),
    "transportó": ("transportar", "Verbo (Pretérito Indefinido)", "transported", "taşıdı / nakletti", "transportar (geçmiş zaman 3. tekil)"),
    "trascendió": ("trascender", "Verbo (Pretérito Indefinido)", "transcended", "aştı / ötesine geçti", "trascender (geçmiş zaman 3. tekil)"),
    "trasladó": ("trasladar", "Verbo (Pretérito Indefinido)", "moved / relocated", "taşıdı / nakletti", "trasladar (geçmiş zaman 3. tekil)"),
    "trató": ("tratar", "Verbo (Pretérito Indefinido)", "treated / tried", "denedi / ele aldı / muamele etti", "tratar (geçmiş zaman 3. tekil)"),
    "turbó": ("turbar", "Verbo (Pretérito Indefinido)", "disturbed", "huzurunu kaçırdı / bulandırdı", "turbar (geçmiş zaman 3. tekil)"),
    "usaban": ("usar", "Verbo (Pretérito Imperfecto)", "used / were using", "kullanıyorlardı", "usar (şimdiki zamanın hikayesi 3. çoğul)"),
    "usaron": ("usar", "Verbo (Pretérito Indefinido)", "used", "kullandılar", "usar (geçmiş zaman 3. çoğul)"),
    "vetaron": ("vetar", "Verbo (Pretérito Indefinido)", "vetoed / banned", "veto ettiler / yasakladılar", "vetar (geçmiş zaman 3. çoğul)"),
    "veían": ("ver", "Verbo (Pretérito Imperfecto)", "saw / were seeing", "görüyorlardı", "ver (şimdiki zamanın hikayesi 3. çoğul)"),
    "viajaban": ("viajar", "Verbo (Pretérito Imperfecto)", "were traveling", "seyahat ediyorlardı / geziyorlardı", "viajar (şimdiki zamanın hikayesi 3. çoğul)"),
    "viajó": ("viajar", "Verbo (Pretérito Indefinido)", "traveled", "seyahat etti / yolculuk yaptı", "viajar (geçmiş zaman 3. tekil)"),
    "visitaban": ("visitar", "Verbo (Pretérito Imperfecto)", "used to visit", "ziyaret ederlerdi / ziyaret ediyorlardı", "visitar (şimdiki zamanın hikayesi 3. çoğul)"),
    "visitaron": ("visitar", "Verbo (Pretérito Indefinido)", "visited", "ziyaret ettiler", "visitar (geçmiş zaman 3. çoğul)"),
    "vivieron": ("vivir", "Verbo (Pretérito Indefinido)", "lived", "yaşadılar", "vivir (geçmiş zaman 3. çoğul)"),
    "vivió": ("vivir", "Verbo (Pretérito Indefinido)", "lived", "yaşadı", "vivir (geçmiş zaman 3. tekil)"),
    "vivían": ("vivir", "Verbo (Pretérito Imperfecto)", "were living", "yaşıyorlardı", "vivir (şimdiki zamanın hikayesi 3. çoğul)"),
    "yacía": ("yacer", "Verbo (Pretérito Imperfecto)", "lay / was lying", "yatıyordu / uzanıyordu", "yacer (şimdiki zamanın hikayesi)")
}
